### ISSUE TITLE
Move command-line entry point to __main__.py in the multiqc module

### ISSUE THREAD

**Issue by KerstenBreuer** [ewels/MultiQC#1002]
Hi,

I really enjoy using multiqc and I would like to integrate it into my new tool which is currently under development at https://github.com/CompEpigen/CWLab.

I would like to use multiqc from within python as a module. However, the main function `multiqc()` is at `scripts/multiqc`. Moreover, the people at our lab would also like to use multiqc on their windows computers. Both could be addressed by moving the content of `scripts/multiqc` to `multiqc/__main__.py` and use the default way of specifying command-line entry point in the `setup.py`.

I already tried out these mild changes in my fork https://github.com/ewels/MultiQC/compare/master...CompEpigen:master.

The advantages are:

- you can use mutliqc from within python as any other module:
```
from multiqc import multiqc
multiqc("/path/to/dir")
```

- you can invoke multiqc with `python -m` and address a specific python interpreter:
```
python -m multiqc .
python3 -m multiqc .
~/my_env/bin/python -m multqc .
```

- you gain windows compatibility

The only problem I have so far is that the logger display `__main__` instead of `multiqc`. However, this should be easy to fix.

Thanks a lot for your support

**Comment by ewels** [comment]
Hi @KerstenBreuer,

This would be nice, thanks for the suggestion! I've had vague thoughts of doing this before (people have enquired about being able to launch MultiQC from within Jupyter Lab sessions for example), but never got around to sitting down and figuring out how to actually do it. I've always struggled with Windows support too as I don't really use it anywhere - it vaguely works (see the [AppVeyor tests](https://github.com/ewels/MultiQC/blob/master/appveyor.yml)) but it's pretty hacky and nasty. So if this also gives better Windows support then that would definitely be a plus!

I've made a PR to a branch with your changes so that we can play with the code and see if tests pass etc. See https://github.com/ewels/MultiQC/pull/1003

Phil

**Comment by ewels** [comment]
ps. CWLab looks very nice!

**Comment by KerstenBreuer** [comment]
Hi @ewels,

Thanks a lot for your fast response and the great support. I've seen some of the tests have failed. I will do my best to figure out the problems in the coming days.

Thanks,
Kersten
