### ISSUE TITLE
Allow _trimmed in sample file names

### ISSUE THREAD

**Issue by MariusGheorghe** [ewels/MultiQC#1018]
Hi,

First of all, great job with MultiQC. Really handy!

I was running it on our results from `fastQC` which consist of samples pre- and post-trimming. I saw that in the MultiQC report some of the samples are ignored/overwritten and there is no way to know which were the ones trimmed and untrimmed. For instance:

Raw report filename: SAMPLE1_R2_fastqc.zip
Parsed report filename: SAMPLE1_R2
Resulting entry in `fastqc_data.keys()`: **SAMPLE1.L001.R2**

Raw report filename: SAMPLE1_R2_trimmed_fastqc.zip
Parsed report filename: SAMPLE1_R2_trimmed
Resulting entry in `fastqc_data.keys()`: **SAMPLE1.L001.R2**

This results in non unique keys in the `fastqc_data` dictionary and some report files are then omitted. 

After eyeballing the MultiQC source code, I see that  the `./utils/config_defaults.yaml` config file has flags to prettify the sample names (`fn_clean_sample_names`), but more specifically the `fn_clean_trim` option explicitly checks for the substring `_trimmed` or `.trimmed` to be removed from the sample filename.

For now, I just commented out those two values from the `fn_clean_trim` option. But is it really necessary? Can those two values be left out from `fn_clean_trim` for good ?
Read trimming is a really standard step in most data processing pipelines and the output filenames are generally named accordingly. As in our case, we would like to see the differences between pre- and post- trimming in the report.  

We are using MultiQC in a continuous integration manner and with each release we check for the newest MultiQC version to include it in our pipeline. That would mean every time modify the `./utils/config_defaults.yaml` file. Or do you guys have another solution or workaround ?

Looking forward to your reply. Thanks!

**Comment by ewels** [comment]
Hi @MariusGheorghe,

Thanks for the issue - it's an interesting point! The reason that these are in place is because filenames in the downstream steps often contain these strings. The aim of `fn_clean_sample_names` is to try to work back from a long filename back to the core unique string if possible. This is the only way that MultiQC can associate samples from different steps in an analysis. When it works well, the _General Statistics_ table has a single row for every sample with the columns summarising each step in the pipeline.

If I remove these defaults then this will break this table structure for many users, so it's not something I'm keen to do I'm afraid. Essentially ignoring FastQC results from trimmed files was a decision I took in the early days and I think I'm still happy with that decision.

Having said this, I totally understand your use case - it's a very common scenario and something I've been thinking about for years now. I have a draft PR open to introduce new functionality to group samples. This would allow the structure of reports to still be clean, but wouldn't ignore data from trimmed / paired read results. I think that this should give the best of both worlds. The PR has been stale for a while now (wow, 2 years??) but I hope to find time to work on it soon now that I'm back at work again after my paternity leave. See https://github.com/ewels/MultiQC/pull/576 - you can see from all of the tagged issues that this comes up a lot!

For your CI/CD I would recommend using a custom config file instead of editing the defaults. There are quite a few places you can keep this, see https://multiqc.info/docs/#configuring-multiqc . The only problem with this is that you'll need to overwrite the entire `fn_clean_trim` array in your config file (presumably with the copy + pasted defaults, minus the `_trimmed` keys). This isn't perfect as this list could change in future updates. But it probably won't change much and is easier than having to edit the source code every time.

I'll close this issue for now in favour of the grouped samples PR, but feedback on these thoughts is welcome.

Phil

**Comment by MariusGheorghe** [comment]
Hi Phil,

Thank you very much for your time to provide all these details. I understand your perspective and it does make sense when working with multiple samples. I guess for our use case, we'll just stick to a workaround using a custom config file for continuous integration. 

Congrats for the baby BTW and keep up the good work :] 

Marius

**Comment by ewels** [comment]
No worries - thanks for raising the issue! It's good to review these decisions occasionally, and remind me that I need to finish that ancient PR..! 😅

**Comment by MariusGheorghe** [comment]
Glad to be of help as a reminder :trollface: :stuck_out_tongue:
