### ISSUE TITLE
Rsubread

### ISSUE THREAD

**Issue by dktanwar** [ewels/MultiQC#1022]
Adding feature for Rsubread would be nice. It runs alignment and also featureCounts

https://bioconductor.org/packages/release/bioc/html/Rsubread.html

**Comment by ewels** [comment]
Does Rsubread give different outputs to Subread? http://subread.sourceforge.net/

If not, then featureCounts is already supported: https://multiqc.info/docs/#featurecounts

The Subread aligner is not supported yet. Feel free to open a new issue for that, using the issue template and supplying the required information: https://github.com/ewels/MultiQC/issues/new?template=module-request.md

I'll close this issue for now, but please let me know if the featurecounts output from Rsubread does not work with MultiQC.

Cheers,

Phil

**Comment by AgazW** [comment]
It doesn't seem to work with Rsubread (R package) or I am missing something. I used output statistics information which looks like 

               Status           S1          S2         S3              S4
             Assigned        5109833      5156481      5115389      5076715
    Unassigned_Unmapped       0            0            0            0
    Unassigned_MappingQuality 0            0            0            0
    Unassigned_Chimera        0            0            0            0
    Unassigned_FragmentLength 0            0            0            0
    Unassigned_Duplicate      0            0            0            0

I changed the name to *.summary as mentioned [here](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L32-L33)

**Comment by ewels** [comment]
Ah, thanks @AgazW. Your output looks a lot like that from the regular featureCounts - for example, one of the files that we use for automated testing here: https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/featureCounts/multiple_files.counts.txt.summary

The main thing that I can see that is different is that the columns in your file are delimited with spaces instead of tab characters. You also have additional whitespace in some places, for example before `Status` on the first line. Both of these things will break the featureCounts module parsing code as it stands.

Is the above output _exactly_ as it is generated by the tool, or is that due to something that happened when entering into the GitHub comment? Does Rsubread generate output files directly or is this produced inside your R environment?

Thanks,

Phil

**Comment by AgazW** [comment]
Thanks, @ewels for your comment. Sorry about the additional spaces, it is due to my bad formating in Github comment.  `Rsubread` will produce everything in the R environment. It produces a list having counts, counts summary, etc. User needs to save it for example in .csv or .txt format. I saved using `write.table`, which is tab-delimited, but `MultiQC` didn't recognize that. 

Thanks,
Agaz

**Comment by ewels** [comment]
Could you zip + attach the file that came form `write.table` please? I can take a look at it and perhaps make the parsing code a little more forgiving..

**Comment by AgazW** [comment]
Please find a sample file attached. 
[counts.zip](https://github.com/ewels/MultiQC/files/4395105/counts.zip)

**Comment by ewels** [comment]
Hi all,

Thank you for your input in this. The featureCounts module now supports both styles of RSubread output described above (MultiQC v1.10dev) - note that filenames must end in `.summary` to be found (you can [customise this though](https://multiqc.info/docs/#module-search-patterns)).

Let me know if you find any problems!

Phil
