### ISSUE TITLE
Can't find the file pattern

### ISSUE THREAD

**Issue by dingdingziyun** [ewels/MultiQC#1039]
My search pattern is `fn="read*"`, and there's one existing in the right directory, however it raise this error. 
Attached is my config content:

```yaml
custom_data:
  sequencing_stats:
    id: "sequencing_stats"
    pconfig:
      id: "barplot_config_only"
      title: "MultiQC Config Data Plot"
      ylab: "Number of things"
    plot_type: "table"
    section_name: "Read/Lane Matrix"
sp:
  sequencing_stats:
    fn: "read*"
```

It raised following error:
```python
Module custom_content raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/custom_content/custom_content.py", line 226, in custom_module_classes
    parsed_modules.append( MultiqcModule(k, mod) )
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/custom_content/custom_content.py", line 272, in __init__
    self.write_data_file( mod['data'], "multiqc_{}".format(modname.lower().replace(' ', '_')) )
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/base_module.py", line 332, in write_data_file
    util_functions.write_data_file(data, fn, sort_cols, data_format)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/utils/util_functions.py", line 68, in write_data_file
    with io.open (os.path.join(config.data_dir, fn), 'w', encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/tmp/tmpC0rC_H/multiqc_data/multiqc_read/lane_matrix.txt'
```

**Comment by ewels** [comment]
Hi @dingdingziyun,

This is a strange error. It's nothing to do with your custom config or your search pattern, the error is happening after that when it's trying to write the parsed data to a file. MultiQC works by first saving everything in a temporary directory whilst it works, then copying these results to your output directory when it is finished.

Here, the temporary file is not found. This could be some kind of weird permissions error that you have with your `/tmp` directory? Does this same error always happen when you run MultiQC? How is it installed / how are you running it?

Phil

**Comment by ewels** [comment]
Ok great. Firstly, installing MultiQC (or any Python package) with `sudo pip` is almost always a bad idea and often causes difficult errors (see https://multiqc.info/docs/#system-python). But given that this error is dependent on a config file I think it's probably not related to that.

I still have absolutely no idea how the search pattern could have any effect on the temporary files, so the only thing is for me to try to replicate the same error. Could you please send some data files that work with the config so that I can try running MultiQC with exactly your setup myself please? Ideally as a zip of two directories with all files contained, so I can just run MultiQC in both folders and have one work and one fail.

Thanks,

Phil

**Comment by ewels** [comment]
Hi @dingdingziyun,

I'm closing this issue now as I can't help any further without replicating the error using some example files. Let me know if there's anything I can do and I will be happy to reopen.

Phil
