### ISSUE TITLE
multiqc 1.8 errs out with salmon 0.14.1

### ISSUE THREAD

**Issue by tamuanand** [ewels/MultiQC#1067]
Hi

I recently updated multiqc to version 1.8 

what used to work with salmon (version 0.14.1) before does not work..

it gives an error like below

"this version of salmon does not support indexing using the RapMap index" 

Thanks in advance

**Comment by ewels** [comment]
Hi @tamuanand,

Please attach one of the Salmon log files / directories so that I can test this and see the error for myself. Or if that’s not possible, please attach the full MultiQC log file - `multiqc_data/multiqc.log` (the GitHub issue template for bugs asks for these things because I need them to be able to help).

The error text is not from MultiQC (you can search the source code - that string is not present), so I’m a little confused.

Thanks,

Phil

**Comment by lucky295** [comment]
Thanks @tamuanand, Thanks for taking the ownership of this issue and posting here to this GitHub forum.

Hi @ewels,

I'm closely working with @tamuanand, So just trying to reply you.

We found the cause where we actually went wrong with. Like you said, the issue is not coming from MultiQC and the error was producing because of the incompatible salmon version-1.0.0 with MultiQC1.8 . when I'm updating MultiQC from 1.7 -> 1.8, then my salmon has also updated to latest version1.0.0 and this takes us into trouble.  Sorry about that it's totally my fault for not checking this.     

Observations:
•	As per my test, I noticed that the latest MultiQC version 1.8 doesn’t support python2.7
•	Multiqc1.8 is incompatible with latest salmon version - 1.0.0 where it is fine with salmon version - 0.14.1  


-Srini

**Comment by tamuanand** [comment]
Hi @lucky295 

thanks for filling in the details here.

@ewels - sorry this was a false alarm - turns out that salmon got inadvertently updated when we updated multiqc 

we have some pre built salmon indices where we used salmon 0.14.1 and hence, i am assuming those would not work with the inadvertent update to salmon v1.0. 

therefore, my best guess is @lucky295 is wrong that multiqc is incompatible with salmon 1.0.0 I think the errors encountered by @lucky295 are because the indices were built with 0.14.1

@ewels on a different note, based on what @lucky295 says - does it mean we update all python to 3.6?

thanks

**Comment by ewels** [comment]
Ah ok, I didn’t know that Salmon had changed their log file format. I’ll need to update the MultiQC module to maintain support then. Thanks for letting me know!

Regarding Python 3.6 - it’s good to upgrade to Python 3 soon, yes. MultiQC will drop support for Python 2 probably in the next rerelease. It’s getting very difficult to keep all of the package requirements working because so many other dependencies MultiQC uses are switching to Python 3 only.

**Comment by ewels** [comment]
x-ref https://github.com/ewels/MultiQC/issues/1068

**Comment by tamuanand** [comment]
Phil

looks like we (me and Srini) might have royally confused you

there is no change in salmon logs

the error we were encountering was because we were using salmon 0.14.1 pre built indices but were doing "salmon quant" using salmon 1.0

And this happened when we updated multiqc via bioconda and in the process we overlooked the conda message that it was also updating salmon.

I apologize for the confusion..In my opinion, multiqc will also work well with salmon 1.0

Thanks

**Comment by ewels** [comment]
Aha! Ok then great! Thanks for letting me know and clarifying.
