### ISSUE TITLE
Biotypes from featureCounts

### ISSUE THREAD

**Issue by CuriusScientist** [ewels/MultiQC#1078]
**Tool Details**
 - Name of tool: featureCounts
 - Tool homepage: http://bioinf.wehi.edu.au/featureCounts/
 - Tool description: featureCounts: a ultrafast and accurate read summarization program
 - Data suitable for MultiQC plot(s): Gene Biotype

**Tool output:**
 - Log filename pattern: [eg. `*_biotype_counts.txt`]
     
 - File contents
[10459-TB-RNA_S68_biotype_counts.txt](https://github.com/ewels/MultiQC/files/3949948/10459-TB-RNA_S68_biotype_counts.txt)

will be cool to parse this file in order to plot the biotype counts.

**Comment by ewels** [comment]
Hi @CuriusScientist,

FeatureCounts summaries are already supported by MultiQC. I don't really want to add support for parsing the full files because it's highly dependent on custom usage by end-users and it's not a default summary output from the tool.

The good news is that the @nf-core [rnaseq pipeline](https://github.com/nf-core/rnaseq/) already has this functionality, so you can just copy that. It uses the MultiQC [custom content](https://multiqc.info/docs/#custom-content) feature and appends [this config header file](https://github.com/nf-core/rnaseq/blob/master/assets/biotypes_header.txt) to the counts file [here](https://github.com/nf-core/rnaseq/blob/3b6df9bd104927298fcdf69e97cca7ff1f80527c/main.nf#L1402):

```bash
cut -f 1,7 biotype.featureCounts.txt | tail -n +3 | cat biotypes_header.txt - >> biotype_counts_mqc.txt
```

The second bit of that command (omitted in the paste above) is a [custom script](https://github.com/nf-core/rnaseq/blob/master/bin/mqc_features_stat.py) to pull the rRNA percentages in to the General Statistics table.

Phil
