### ISSUE TITLE
FastQC: Sequence Duplication Levels interactive dialog indexing error

### ISSUE THREAD

**Issue by kohlkopf** [ewels/MultiQC#1092]
**Description of bug:**
The hovering dialog on the interactive version of  *FastQC: Sequence Duplication Levels* is one off, perhaps an indexing error

This error is in two reports with very different data run at different times.

For example, the mouse if hovering at position 3 but the dialog indicates 2.

![image](https://user-images.githubusercontent.com/28633777/71936224-0e9fcb80-3166-11ea-9f7e-6246e29b5e1a.png)

**MultiQC details**
multiqc, version 1.8

**Comment by ewels** [comment]
Ah, good spot. What happens when you hover over to the far right where it says `>50` etc?

I guess that it’s showing the category index, and will just say `10`, `11`, `12` etc..

**Comment by ewels** [comment]
Hi @kohlkopf,

I think that this should now be fixed in v1.9dev - let me know if you spot any more problems.

Note that if you run MultiQC on multiple FastQC reports that were generated using different versions and/or different settings for the sequence duplication data, you might get slightly strange results. I haven't been able to find anything specific that breaks though - let me know if you find a reproducible error.

Thanks,

Phil
