### ISSUE TITLE
Tag ewels/multiqc docker with version 1.8

### ISSUE THREAD

**Issue by PubuduSaneth** [ewels/MultiQC#1095]
Will you be able to tag the docker image in the dockerhub (https://hub.docker.com/r/ewels/multiqc) with the version number 1.8 

- For example - ewels/multiqc:1.8

**Comment by ewels** [comment]
Yes, certainly. That should have happened automatically when I pushed the GitHub release. I’ll look in to it.

Thanks for letting me know!

**Comment by nkrumm** [comment]
Hi,
I think this is still pending-- 

```bash
docker pull ewels/multiqc:1.8
Error response from daemon: manifest for ewels/multiqc:1.8 not found: manifest unknown: manifest unknown
```
 and I can't seem to find it on https://hub.docker.com/r/ewels/multiqc/tags.

Thanks for a great tool!

**Comment by ewels** [comment]
Hi both,

Sorry about this. I have just manually rebuilt this image and pushed to dockerhub. You should now find tags for `1:8` and `latest`.

It looks like the automated builds weren't working because I have been tagging MultiQC releases on GitHub as `v1.8` and the build rule was looking for `1.8`. I have added new build / tag rules now so it should hopefully trigger properly in the future :+1:

Phil
