### ISSUE TITLE
Add -h flag

### ISSUE THREAD

**Issue by s-andrews** [ewels/MultiQC#110]
Stupid but simple request - is there any reason why -h isn't equivalent to --help?  It doesn't seem to be used for anything else.

**Comment by ewels** [comment]
Yes, this has been bugging me as well, but not enough to do anything about it yet. We switched the package used to handle command line arguments (now click instead of argparse) and help is a special case.

Anyway - I just did a bit of googling and found out how to add -h ([here](http://click.pocoo.org/5/documentation/#help-parameter-customization)) so will do this.

**Comment by ewels** [comment]
(Stupid and simple but surprisingly difficult to change!)
