### ISSUE TITLE
VerifyBamID2 FREEMIX header incompatibility

### ISSUE THREAD

**Issue by klannert** [ewels/MultiQC#1112]
**Description of bug:**
Using VerifyBamID2 uses the header `FREEMIX(alpha)` for the contamination estimate, which MultiQC doesn't recognize. The freemix/contamination field isn't populated to the MultiQC report. 

**File that triggers the error:**

[sample.verifybamid.result.selfSM.txt](https://github.com/ewels/MultiQC/files/4232824/sample.verifybamid.result.selfSM.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: multiqc .
 - MultiQC Version: 1.8
 - Operating System: MacOS 10.14.6
 - Python Version: 3.7.6
 - Method of MultiQC installation: pip

 **Additional context**
I've tried editing the MultiQC config file to include `FREEMIX(alpha)` but it doesn't seem to work. If I manually edit the header and remove `(alpha)` it works as expected. I can't find a way to tell VerifyBamID2 not to add it in the first place.

**Comment by ewels** [comment]
Hi @klannert,

Thanks for reporting this. Looking at the code quickly I guess that the data is being parsed properly, but because the field names are generated from the header automatically and the code [refers to `FREEMIX`](https://github.com/ewels/MultiQC/blob/ce4a2c493ee2b458ae3026119e31715c990e6114/multiqc/modules/verifybamid/verifybamid.py#L135) when creating the table column, it won't be found.

Should be a fairly simple fix - just need to add to the parsing code to find a header called `FREEMIX(alpha)` and rename it to `FREEMIX`. Then the rest of the code should behave as expected.

Phil

**Comment by ewels** [comment]
Hi @klannert,

This is now fixed in MultiQC v1.9dev - the general stats table now correctly shows the contamination:

![image](https://user-images.githubusercontent.com/465550/83149751-c411f200-a0fa-11ea-874f-1eb9ff3d6ee1.png)

Thanks for reporting, let me know if you spot any problems!

Phil
