### ISSUE TITLE
Flash read combination statistics plot is misinformative when -O option is not used.

### ISSUE THREAD

**Issue by mahesh-panchal** [ewels/MultiQC#1173]
Hi,

I think the default way of capturing data for the Flash module assumes certain flags are set when running. One example is the Combined innie pairs and Combined outie pairs are only available when -O is used ( I think).

When called like this (nextflow):

```bash
flash -t ${task.cpus} -o $sample_name -z $reads 2>&1 | tee ${sample_name}.log
```

This is the relevant part of the log that's output: 
```
[FLASH]  
[FLASH] Read combination statistics:
[FLASH]     Total pairs:      18836854
[FLASH]     Combined pairs:   18472165
[FLASH]     Uncombined pairs: 364689
[FLASH]     Percent combined: 98.06%
[FLASH]  
```
which makes the Flash read combination statistics plot look like this:
![flash_combo_stats_plot](https://user-images.githubusercontent.com/15652539/80685560-b0597880-8ac7-11ea-8181-0b29edf43d36.png)

I think this plot is misleading compared to the stats in the General statistics table. 
The hover over text also says that 100% are uncombined, only because the other categories are not there.

**Comment by ewels** [comment]
Please can you make a PR to https://github.com/ewels/MultiQC_TestData with a full log file in this mode? And a PR to fix it if you fancy 😉 

Thanks!

**Comment by mahesh-panchal** [comment]
I just saw this error in my multiqc log for this style of flash logs.
```
[2020-05-13 02:23:01,028] multiqc.modules.flash.flash                        [ERROR  ]  'bool' object has no attribute 'items'
[2020-05-13 02:23:01,030] multiqc.modules.flash.flash                        [DEBUG  ]  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/multiqc/modules/flash/flash.py", line 49, in __init__
    plot=self.summary_plot(self.flash_data))
  File "/usr/local/lib/python3.8/site-packages/multiqc/modules/flash/flash.py", line 176, in summary_plot
    return bargraph.plot(data, cats, splotconfig)
  File "/usr/local/lib/python3.8/site-packages/multiqc/plots/bargraph.py", line 60, in plot
    for k, v in config.custom_plot_config[pconfig['id']].items():
AttributeError: 'bool' object has no attribute 'items'

```

**Comment by ewels** [comment]
Thanks for reporting this @mahesh-panchal - now resolved:

![flash_combo_stats_plot](https://user-images.githubusercontent.com/465550/82903821-d3aa0300-9f61-11ea-9f42-235e6d81866e.png)

Unused categories are now hidden and if innie or outie uncombined pairs are not reported but uncombined is, then that is plotted. I think that should handle both use cases.

I wasn't able to reproduce the `AttributeError` problem or spot anything suspicious from the code for that. If you can find a log file that triggers it so that I can reproduce then please open a new issue for it.

Thanks!

Phil
