### ISSUE TITLE
remove_sections not working when multiple FastQC

### ISSUE THREAD

**Issue by lcabus-flomics** [ewels/MultiQC#1184]
Hi!

I'm working on a pipeline based on nf-core that has a FastQC as a first step and afterwards it has the Trim Galore, that does the trimming and has another FastQC step. I wanted to report the first full FastQC and in the second one report only the steps of Sequence Quality Histograms and Adapter Content.

I tried to do it by setting in the `multiqc_config.yaml` the remove sections like this:

```yaml
remove_sections:
    - 'fastqc_sequence_counts-1'
    - 'fastqc_per_base_sequence_content-1'
    - 'fastqc_per_base_sequence_content-1'
    - 'fastqc_per_sequence_gc_content-1'
    - 'fastqc_per_base_n_content-1'
    - 'fastqc_sequence_length_distribution-1'
    - 'fastqc_sequence_length_distribution-1'
    - 'fastqc_sequence_duplication_levels-1'
```

But when I run the program again it doesn't seem to work.

Those lines were the links to the different parts of the FastQC.

Also, I noticed that if I added `'fastqc_sequence_counts'`, which is only for the first FastQC it removed that part for the second FastQC also.

Do you know a way to solve this?
Thank you very much!

**Comment by ewels** [comment]
Hi @lcabus-flomics,

Could you give a little more details on what you mean by "not working" please?

Phil

**Comment by ewels** [comment]
Ok, so looking at your config file I guess you mean that the sections are not being removed? This ties in with the fact that giving a section ID without the `-1` suffix removes it from both of the module runs.

Looking at the code, I can see that the `remove_sections` check is done before the HTML ID is checked for uniqueness:

https://github.com/ewels/MultiQC/blob/afbb316e12e7821b783ff0fa443ef458745027e7/multiqc/modules/base_module.py#L152-L158

It's this second bit that adds the `-1` prefix, so that explains both parts of the problem.

I should be able to swap these bits of code around and it will hopefully solve your problem.

Phil

**Comment by ewels** [comment]
Ok, fix pushed - please try again with the latest version of MultiQC v1.9dev and see if that works for you now.. 👍

**Comment by lcabus-flomics** [comment]
Okay, I will try, thank you very much!
