### ISSUE TITLE
Module PycoQC: Display read length on log scale

### ISSUE THREAD

**Issue by caspargross** [ewels/MultiQC#1214]
Thanks for the implementation of the module.

Currently read length distribution has a linear scale
![grafik](https://user-images.githubusercontent.com/10211013/83491239-c33ddf00-a4b1-11ea-9902-c91a0c7f2ea7.png)

Personally, I think it would be better to display the read lenghts on logarithmic scale, similar to the internal PycoQC report:

![grafik](https://user-images.githubusercontent.com/10211013/83491412-013b0300-a4b2-11ea-86e8-cfa6ce32a0e2.png)

What is your opinion on this?

_Originally posted by @caspargross in https://github.com/ewels/MultiQC/issues/1075#issuecomment-637342569_

**Comment by ewels** [comment]
Ah good spot - yes we should mimic the main PycoQC report - a log scale certainly looks more useful 👍 

I guess that this was missed because the [test data](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/pycoqc) I have looks fine with a regular x-axis:

![image](https://user-images.githubusercontent.com/465550/83508554-626ed080-a4ca-11ea-80ca-24f9bd3efd4c.png)

**Comment by ewels** [comment]
Updated in v1.10dev

![image](https://user-images.githubusercontent.com/465550/83508963-f771c980-a4ca-11ea-836e-d1fba6d64463.png)
