### ISSUE TITLE
Multiqc error for new json format

### ISSUE THREAD

**Issue by YolandiSwart** [ewels/MultiQC#1237]
Hi, I used HTSream version 1.3.1 to do quality control on my RNA sequencing data and used the MutliQC's added HTStream module to generate reports of the statistics. I however receive an error (see screenshot below) and says I should update to newer version of HTStream. If somoene could maybe help me resolve this issue. Thank you.

**MultiQC Error log:**

```


```

**File that triggers the error:**
[SampleC_RSEQ250_htsStats.log](https://github.com/ewels/MultiQC/files/4831787/SampleC_RSEQ250_htsStats.log)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: multiqc . 
* MultiQC Version: multiqc, version 1.9.dev0
* Operating System: macOS Catalina Version 10.15.5
* Python Version: Python version 3.7.7
* Method of MultiQC installation: pip

**Additional context**
 
<img width="948" alt="Screenshot 2020-06-24 at 09 07 11" src="https://user-images.githubusercontent.com/49681556/85734034-fa905c00-b6fc-11ea-95eb-734ae8426f74.png">

**Comment by ewels** [comment]
Hi @YolandiSwart,

I've never heard of HTStream before - it's not supported by MultiQC yet, which makes your issue a little confusing! 😅 

After a quick google I found https://github.com/s4hts/HTStream/issues/207 saying that someone is working on a new module to support HTStream. I guess this is what you're using?

As this code is not yet part of the core MultiQC package yet, I'm afraid that I can't help you with your issue. Please contact whoever is writing this new module for help.

Thanks,

Phil

**Comment by ewels** [comment]
Maybe @msettles or @bnjenner may be able to help?

**Comment by msettles** [comment]
hello @YolandiSwart @ewels is correct, we are currently forked off of the main multiQC branch with plans to submit a pull request in the next couple weeks. If you'd like you can make an issue here https://github.com/s4hts/MultiQC and we can work on the problem. BUT quick look at the output suggests you've used different htstream workflows across your samples "Inconsistent Order of HTStream applications", all samples should be using the same workflow in order to collate and compare. Thanks @ewels
