### ISSUE TITLE
 The 'fastqc' MultiQC module broke

### ISSUE THREAD

**Issue by dancahda** [ewels/MultiQC#1249]
```
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/home/my/miniconda3/envs/python2/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/home/my/miniconda3/envs/python2/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 91, in __init__
    self.fastqc_general_stats()
  File "/home/my/miniconda3/envs/python2/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 200, in fastqc_general_stats
    'avg_sequence_length': bs['avg_sequence_length'],
KeyError: 'avg_sequence_length'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Hi @dancahda,

When you clicked "New issue" there was a template for a bug report. Please don't ignore it, as I need the answers to the questions in that template to help.

Here it is again for reference:

---

**Description of bug:**
_A clear and concise description of what the bug is._

**MultiQC Error log:**
_Please paste your MultiQC log within the triple backticks below for code formatting
(use a blank line before and after your log)_

**File that triggers the error:**
_Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error._

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: _[eg. `multiqc .`]_
* MultiQC Version: _[eg. MultiQC v1.1]_
* Operating System: _[eg. macOS Sierra 10.12.5]_
* Python Version: _[eg. Python 3.8.4]_
* Method of MultiQC installation: _[eg. pip, conda, manual]_

**Additional context**
_Add any other context about the problem here._

---

Note that I have edited your original issue to put the MultiQC log in the backticks. However, as it's truncated it's difficult to to know what's going wrong.

Going from the MultiQC path (`/home/my/miniconda3/envs/python2/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/`) it looks like:

* You're using a development version of MultiQC v1.0, so code that is pre-May 2017 (very old)
* You're using Python 2.7, which is [no longer supported](https://multiqc.info/docs/#python-2).

If you are using `v1.0dev` then please try upgrading to the latest release.

Phil
