### ISSUE TITLE
report - Oops! The 'tophat' MulitQC module broke

### ISSUE THREAD

**Issue by N11V** [ewels/MultiQC#131]
```
============================================================
Module tophat raised an exception: Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/bin/multiqc", line 210, in multiqc
    report.modules_output.append(mod())
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/multiqc/modules/tophat/tophat.py", line 30, in __init__
    parsed_data = self.parse_tophat_log(f['f'])
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/multiqc/modules/tophat/tophat.py", line 82, in parse_tophat_log
    parsed_data['unaligned_total'] = parsed_data['total_reads'] - parsed_data['aligned_total']
KeyError: 'total_reads'
============================================================
```

Example log file attached below.

**Comment by N11V** [comment]
Attached a file.
[align_summary.txt](https://github.com/ewels/MultiQC/files/95398/align_summary.txt)

**Comment by N11V** [comment]
I suspect that the regex on line 70 in tophat.py is causing the problem.

[Rr]eads:\n\s+Input\s+:\s+(\d+)

The whitespace after Input and before the colon doesn't match my files. I'd need the regex to be [Rr]eads:\n\s+Input:\s+(\d+). Unfortunately I don't have root access to the machine with MulitQC installed so I can't test this out.

**Comment by N11V** [comment]
Yep that fixed it for me.

**Comment by ewels** [comment]
Hi @N11V - thanks for doing this investigative work! Weird that our files look different - [this](https://github.com/ewels/MultiQC_TestData/blob/master/data/ERR458837_1_val_tophat.align_summary.txt) is the one I've been using for testing.

Anyway, I'll modify the regex to have optional whitespace so that it works on both types of output. This will go out in the next release, which should be relatively soon.

Thanks again!
