### ISSUE TITLE
Help using multiqc

### ISSUE THREAD

**Issue by mbartl13** [ewels/MultiQC#1350]
Having issues installing and using in a cluster environment. Installed locally per admins suggestion but the script isn't finding modules that I can see in the installed directory:

```console
$ multiqc.py .
Traceback (most recent call last):
  File "/dcl02/leased/giffin/MultiQC-master/multiqc/multiqc.py", line 38, in <module>
    from .plots import table
ModuleNotFoundError: No module named '__main__.plots'; '__main__' is not a package

```

**Comment by ewels** [comment]
Hi @mbartl13,

I'm going to need more details about what you've done in order to help sorry. It looks like you might be running the `multiqc.py` script directly? Which is not how you install or run MultiQC. Please see the docs: https://multiqc.info/docs/#installing-multiqc

I'll close this now but please feel free to comment / open a new issue if you're still having problems.

Phil
