### ISSUE TITLE
missing some samples in figures

### ISSUE THREAD

**Issue by zpingfeng** [ewels/MultiQC#1382]
Hi Phil,

Thanks for this nice package! But I found many samples are missing from the figures, both for fastqc report and featureCounts. Is this due to the figure size limit? I have 224 PE  RNAseq samples.

Zhiping

**Comment by zpingfeng** [comment]
I found this from log file:
[ERROR  ]       linegraph : ############### Error making MatPlotLib figure! Falling back to HighCharts.
[INFO   ]         multiqc : Compressing plot data

How do I adjust the Figure height to include all the samples?

**Comment by ewels** [comment]
Hi @zpingfeng,

Please see the docs for:

* Not enough samples found: https://multiqc.info/docs/#not-enough-samples-found
* Large sample numbers: https://multiqc.info/docs/#large-sample-numbers

If you're still having problems after this, please create a new issue, using the template to give information like MultiQC version, command, output, example data etc so that I can help 👍🏻 

Phil

**Comment by zpingfeng** [comment]
Thank you very much Phil! I use interactive plots now.  It looks great!
