### ISSUE TITLE
MultiQC Module broke

### ISSUE THREAD

**Issue by areeyadis** [ewels/MultiQC#1392]
Errors on 'MultiQC module broke' were detected while running multiqc. A report file contains only information about duplicate reads.

```console
srl@srl-Precision-3630-Tower:~/Miseq_MTB2562$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.10.dev0
[INFO   ]         multiqc : Template    : default
[WARNING]         multiqc : You are running MultiQC with Python 2.7.17
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
[INFO   ]         multiqc : Searching   : /home/srl/Miseq_MTB2562
Searching 2458 files..  [####################################]  100%          
[ERROR  ]         multiqc : Oops! The 'hops' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module hops raised an exception: Traceback (most recent call last):
  File "/home/srl/.local/lib/python2.7/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/home/srl/.local/lib/python2.7/site-packages/multiqc/modules/hops/hops.py", line 24, in __init__
    for f in self.find_log_files('hops',filehandles=True):
  File "/home/srl/.local/lib/python2.7/site-packages/multiqc/modules/base_module.py", line 97, in find_log_files
    for f in report.files[sp_key]:
KeyError: 'hops'
============================================================
[ERROR  ]         multiqc : Oops! The 'somalier' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/home/srl/.local/lib/python2.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/home/srl/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/srl/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/srl/.local/lib/python2.7/site-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/home/srl/.local/lib/python2.7/site-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
============================================================
[INFO   ]          picard : Found 117 MarkDuplicates reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
[multiqc.log](https://github.com/ewels/MultiQC/files/6128208/multiqc.log)
```

**Comment by ewels** [comment]
Hi @areeyadis,

Please fill in the issue template provided - I need this information to be able to help. You're missing the following:

**File that triggers the error:**

_Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error._

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: _[eg. `multiqc .`]_
- MultiQC Version: _[eg. MultiQC v1.1]_
- Operating System: _[eg. macOS Sierra 10.12.5]_
- Python Version: _[eg. Python 3.8.4]_
- Method of MultiQC installation: _[eg. pip, conda, manual]_

Most important is an example file so that I can replicate the error myself. Without this it's extremely difficult to track down and fix bugs.

**Comment by ewels** [comment]
ps. I just noticed that the log you pasted says that you are running with Python `2.7.17`. A minimum of Python 3.6 is now required for MultiQC, so that's the first place to start.

https://multiqc.info/docs/#python-2

The log message should be reworded as this is no longer "soon", this has already happened.

**Comment by jfy133** [comment]
Hi @areeyadis in addition to above, there was an upstream bug in HOPs that was fixed (literally!) yesterday (https://github.com/bioconda/bioconda-recipes/pull/27311)! 

Please install the latest version (0.35) and the JSON output should be again be MultiQC compatible

**Comment by ewels** [comment]
Closing as - `v1.10.dev0` MultiQC version, not stable `v1.10` release and using Python 2.7.

I'm pretty sure that at least the Somalier error is related to the Python version. The HOPS error makes no sense and could be either, or something else.

@areeyadis if you upgrade both MultiQC and Python and still get these errors please let us know and I can reopen the issue.

Phil
