### ISSUE TITLE
Aggregate previous MultiQC reports

### ISSUE THREAD

**Issue by a-frantz** [ewels/MultiQC#1396]
Our quality check WDL workflow generates per-sample MultiQC reports, and we also run MultiQC on the entire batch/cohort once they've finished running. Our workflow outputs some tools reports as tarballs, so before we can run batch level MultiQC we need to untar a bunch of results which takes some (small) effort and disk space. However MultiQC has already been run on these samples and the full reports are available.

It would be great if MultiQC could recognize its own output, and aggregate its own reports.

**Comment by ewels** [comment]
This is not an uncommon request but is a monumentally huge task. I am slowly collecting thoughts for a v2.0 rewrite and this would be one feature that would be added as part of that. Probably best not to hold your breath though :)

Could potentially implement some of this in the mean time, I think the strategy would be to get the core functions to output _Custom Content_ files to the data directory. It won't work for some modules though and gets very complicated quickly when thinking about organisation of modules, sections and additional content around the plots. So basically it would be pretty rubbish which is why I haven't done it yet.

You may also be interested in https://github.com/ewels/MegaQC

**Comment by a-frantz** [comment]
Thanks! MegaQC looks pretty awesome, I'm going to try and play around with it when I have some time.

**Comment by ewels** [comment]
Merging into https://github.com/ewels/MultiQC/issues/1256 which describes the same idea.

**Comment by quantumkisa** [comment]
@a-frantz, I ran into same problem with my reports: they are also generated per-sample. Maybe you found solution to this issue? Are you using MegaQC?

**Comment by serge2016** [comment]
Does anybody knows about MegaQC plans to release? It's still beta?
