### ISSUE TITLE
Oops! The 'picard' MultiQC module broke

### ISSUE THREAD

**Issue by zmiimz** [ewels/MultiQC#1397]
**Description of bug:**
[ERROR  ]  Oops! The 'picard' MultiQC module broke...

**MultiQC Error log:**

```
============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "/home/zmi/Programs/conda/miniconda3/lib/python3.7/site-packages/multiqc/multiqc.py", line 579, in run
    output = mod()
  File "/home/zmi/Programs/conda/miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/picard.py", line 117, in __init__
    n["ValidateSamFile"] = ValidateSamFile.parse_reports(self)
  File "/home/zmi/Programs/conda/miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/ValidateSamFile.py", line 90, in parse_reports
    data = _parse_reports_by_type(self)
  File "/home/zmi/Programs/conda/miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/ValidateSamFile.py", line 132, in _parse_reports_by_type
    sample_data = _parse_summary_report(filehandle)
  File "/home/zmi/Programs/conda/miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/ValidateSamFile.py", line 165, in _parse_summary_report
    for problem_type, name, count in _histogram_data(filehandle):
  File "/home/zmi/Programs/conda/miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/ValidateSamFile.py", line 187, in _histogram_data
    problem_type, name = values[0].split(":")
ValueError: not enough values to unpack (expected 2, got 1)
============================================================
```

**File that triggers the error:**

content of the file E086.TI.FFPE.WES.paired.sorted.bam.picard.ValidateSamFile.stats
```


## HISTOGRAM	java.lang.String
Error Type	Count
ERROR:MATE_NOT_FOUND	584906
```
**MultiQC run details (please complete the following):**

- Command used to run MultiQC: `multiqc  <path1> <path2>`
- MultiQC Version: MultiQC v1.10
- Operating System:  Ubuntu 18.04
- Python Version: Python 3.7.8
- Method of MultiQC installation: conda

**Additional context**

**Comment by zmiimz** [comment]
Ok, it looks like I have duplicated picard reports for some samples including the mentioned one.
But I am still wondering why this triggers error in the module and not a simple warning etc...

**Comment by ewels** [comment]
I agree that it shouldn't cause this crash when that happens so have reopened.

Is this really the entire contents of the file `E086.TI.FFPE.WES.paired.sorted.bam.picard.ValidateSamFile.stats`?

```
## HISTOGRAM	java.lang.String
Error Type	Count
ERROR:MATE_NOT_FOUND	584906
```

And it crashes when you have two files with this identical contents?

It would be best if you could get two files that cause this error and zip them and drop that zip file on to this issue if possible. That makes it easy for me to replicate the error and then fix it.

Thanks!

Phil

**Comment by aarawles** [comment]
Same problem.
[picardBroke.txt](https://github.com/ewels/MultiQC/files/6229811/picardBroke.txt)

**Comment by ewels** [comment]
@aarawles - same MultiQC module, different problem. The file that triggered your error is called `./lib/python3.8/site-packages/multiqc/modules/picard/__pycache__/ValidateSamFile.cpython-38.pyc` which looks a lot like a file from the MultiQC installation. I guess that you're running MultiQC in the installation directory somehow.

Please take a look at the docs for instructions: https://multiqc.info/docs/#running-multiqc

**Comment by ewels** [comment]
@zmiimz I just had a play with your example files but I can't replicate the error sorry. I made a file with the same filename and same file contents but for me, MultiQC runs without problem on the one file, runs fine when it's copied and even runs fine when it has an identical filename in two directories. I'm not able to get the same crash.

From looking at the traceback alone, I guess that this happens when the file contains error codes that don't follow the `TYPE:NAME` convention with the `:` character. Sure enough, if I modify your file to look like this:

```
## HISTOGRAM	java.lang.String
Error Type	Count
ERROR-MATE_NOT_FOUND	584906
```

Then I get the same error + traceback. And after a bit more playing, I realised that if I added additional whitespace lines to the bottom of the file then that also causes the error 😱 

Anyway, I've just pushed 1509d54a495a61c1f6ed1a2fdc25cf4d63ef6494 that handles both of these - ignoring lines with the wrong format with an error message and skipping blank lines. It's available if you install the dev version now and should hopefully that solve your problems.

Thanks for reporting! Let me know how you get on with this.

Phil

**Comment by aarawles** [comment]
Indeed I was, thanks for the pointer and reference!
