### ISSUE TITLE
Multiqc input filename

### ISSUE THREAD

**Issue by MichWeb75** [ewels/MultiQC#1478]
### Description of bug

Hi, I recognized that multiqc is sensitive to the suffix of the input file name. If this is desired behaviour please highlight this in the documentation. 

```bash
multiqc --filename multiqc_test --outdir multiqc results/results.txt
## WARNING: No analysis results found. Cleaning up.
```

```bash
multiqc --filename multiqc_test --outdir multiqc results/merged_mqc.txt
## WORKS
```

**Comment by ewels** [comment]
Not always, it is module specific. This is already pretty well highlighted in the documentation already I think - docs for every list the search parameters (including filename pattern if relevant):

https://multiqc.info/docs/#multiqc-modules

Your example is specifically for Custom Content files, where again it is documented: https://multiqc.info/docs/#multiqc-specific-data-file

I don't really want to mention it more broadly than this, because there are plenty of tool outputs that MultiQC can find irrespective of the filename used. So it's not generally applicable.

Having said this, I'm always open to improving the docs. So if you have any specific suggestions of what could be written where then please let me know (or even better, make a PR).

Cheers,

Phil
