### ISSUE TITLE
multiqc | No analysis results found. Cleaning up..

### ISSUE THREAD

**Issue by strayologist** [ewels/MultiQC#1493]
I'm trying to run `multiqc .` in a directory that contains the results of **fastp** in .json and .html format. It's showing the message 

>  /// MultiQC 🔍 | v1.11
> 
>           multiqc | Search path : media/strayologist/work/genomics/metagenomes/fastp-reports
> searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 85/85  
>           multiqc | No analysis results found. Cleaning up..
>           multiqc | MultiQC complete

Am I missing something?
Please help.

**Comment by ErikDanielsson** [comment]
The `fastp` MultiQC module finds `fastp` logs using the glob pattern `*fastp.json`. If your files don't match this pattern they won't be recognised by MultiQC. If the filenames do follow the pattern, the error could be due to something else. Could you in that case provide a file so I can reproduce the issue?

**Comment by ewels** [comment]
Yup, see the troubleshooting docs: https://multiqc.info/docs/#no-logs-found-for-a-tool

Also the fastp module docs: https://multiqc.info/docs/#fastp (which shows the search pattern mentioned by @ErikDanielsson).

In the future, please use the [Bug template](https://github.com/ewels/MultiQC/issues/new?assignees=&labels=&template=bug_report.yml) when creating an issue like this, as it helps to make sure that we have all of the information that we will need.

Thanks,

Phil

**Comment by ewels** [comment]
Closing as no response
