### ISSUE TITLE
RSeQC geneBodyCoverage percentage bug 

### ISSUE THREAD

**Issue by uros-absci** [ewels/MultiQC#1538]
### Description of bug

For the RSeQC geneBodyCoverage module, when calculating the percentage for the histogram on the y axis, the code is:
```python
total = sum(self.gene_body_cov_hist_counts[s_name].values())
for k, v in self.gene_body_cov_hist_counts[s_name].items():
    self.gene_body_cov_hist_percent[s_name][k] = (v / total) * 100
```
I believe the division should be by max value and not by total, in order for the y axis percentages to scale to 100. 
This way they scale to arbitrary numbers (like 1.25% or so, depending on the data)

**Comment by ewels** [comment]
Thanks for opening the issue @uros-absci - I see your point, but I'm not entirely sure which approach is best. With your suggestion the relative scaling of each sample will change so that every line touches 100%. Personally I find that harder to look at / interpret. The values on the y-axis are kind of meaningless anyway, it's the shape of the curve which is interesting.

I'm inclined to say that this is a feature, not a bug..
