### ISSUE TITLE
Somalier module: the label on y-axis is incorrect

### ISSUE THREAD

**Issue by leonorpalmeira** [ewels/MultiQC#1546]
### Description of bug

In the Somalier module (MultiQC v1.9), the label on the y-axis reads: "Scaled mean depth on X" (which should be around 2 for females and 1 for males given that this is computed by **Somalier** as `"x_depth_mean": 2 * stats[i].x_dp.mean / stats[i].gtdp.mean`). However, the value which is plotted is `X_mean_depth`, see below:

![Screenshot from 2021-09-09 14-36-34](https://user-images.githubusercontent.com/7592317/132686919-cdb81f92-18fe-4e41-b1e0-87bb4110356d.png)

I believe the y-label should be modified.

**Comment by leonorpalmeira** [comment]
From what I see in the current code, the label is still incorrect in the current code base:

![Screenshot from 2021-09-09 14-47-16](https://user-images.githubusercontent.com/7592317/132688419-eaad1050-29e2-44fb-b6a3-58806ab35826.png)

**Comment by ewels** [comment]
oof, so this is a difference between `x_depth_mean` and `x_mean_depth`? I can see why that was confused! 😅 

Fixing the plot axis is easy, but it might be nicer to have the scaled version which is not sequencing-depth dependent. It should be possible to replicate the formula that you quoted from Somalier above.

With the example data I then get this:
![somalier_sex_check_plot](https://user-images.githubusercontent.com/465550/151344783-9071b61a-44d8-434d-944d-75caa0883e29.png)

Instead of the original:
![somalier_sex_check_plot (1)](https://user-images.githubusercontent.com/465550/151344802-242dd04d-f680-4674-9929-1cf46364cd9c.png)

I guess that this was the original intention, so let's go with this..

**Comment by ewels** [comment]
Ok, changes made in 63749396309bf9488c49501d661d74707b6f2f4c - please let me know if you spot any issues with the code.

Thanks for the detailed report!

**Comment by leonorpalmeira** [comment]
The code looks good to me. Thanks for fixing this and for reverting back to what was probably intended!
