### ISSUE TITLE
Feature Request: Configure First Column of Tables

### ISSUE THREAD

**Issue by schorlton** [ewels/MultiQC#1560]
### Description of feature

Thanks for all of your hard work!

I'm wondering if it's possible to format the first column of a table, particularly a custom table, similar to the options available for the other columns? An example is if I want to color a sample name, without using highlighting (I want it by default, don't want it in the highlight menu and would like other formatting options that are available for data cells, eg. background color).

I didn't think this was possible based on these docs: https://multiqc.info/docs/#first-columns-in-tables-are-special

Thanks again!

**Comment by ewels** [comment]
Hi @schorlton,

This is not currently possible, no. It's not particular trivial either, because the first column is used so extensively throughout the javascript. I'd be worried that if we start adding any other markup in then it will likely break a lot of stuff.

If possible, I would advise adding any additional metadata (eg. sample grouping etc) as an additional column. I know this isn't ideal, but it's a lot less problematic 😅 

Closing for now as I don't see this being tackled any time soon, sorry.

Phil

**Comment by schorlton** [comment]
Thanks for the thoughtful response Phil. Yes, that is exactly what we'll do for metadata. Really appreciate the hard work you put into MultiQC and I think we'll live without formatted first column :smile:

**Comment by ewels** [comment]
Much appreciated 🙏🏻 😄
