### ISSUE TITLE
ERROR! MatPlotLib library could not be loaded

### ISSUE THREAD

**Issue by MeHelmy** [ewels/MultiQC#1601]
### Description of bug

Multiqc could not load matplotlib

### File that triggers the error

I used  `multiqc . ` as explained by log below. 

### MultiQC Error log

```console
multiqc . 

 /// MultiQC 🔍 | v1.11

|           multiqc | Search path : ~/home/result_2021-12-09
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 38/38
##### ERROR! MatPlotLib library could not be loaded!    #####
##### Flat plots will instead be plotted as interactive #####
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by ~/home/envs/mmy_env/lib/python3.8/site-packages/PIL/_imaging.cpython-38-x86_64-linux-gnu.so)
##### ERROR! MatPlotLib library could not be loaded!    #####
##### Flat plots will instead be plotted as interactive #####
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by ~/home/envs/my_env/lib/python3.8/site-packages/PIL/_imaging.cpython-38-x86_64-linux-gnu.so)
|          bargraph | Tried to make bar plot, but had no data
|          bargraph | Tried to make bar plot, but had no data
|            picard | Found 1 AlignmentSummaryMetrics reports
|          pangolin | Found 1 samples
|            fastqc | Found 2 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment]
Yup, your matplotlib installation seems to be broken. MultiQC is still running fine, it's just telling you that it can't make flat image plots.

If you reinstall / fix matplotlib then the warning will go away.

Let me know if there's anything I can do / if I need to reopen the issue.

Phil

**Comment by MeHelmy** [comment]
I installed MultiQC using Conda. I assume that it will install Matplotlib implicitly. Nevertheless, I also installed Matplotlib in the same environment after installing MultiQC, though I got the same error!! 

Best,
Medhat

**Comment by MatthiasZepper** [comment]
This error means your version of Python 3.8 was compiled against glibc version 2.14 and it requires that exact version to run, which is however not found on your system. 

Since Version 2.14 is fairly old, I would presume that the library version present in your Linux Distro natively is newer which can be checked with `readelf -a /lib64/libc.so.6`. If so, you could start troubleshooting how the shared libraries inside your virtual environment are resolved and run e.g. `export LD_DEBUG=libs && matplotlib`, but it is likely not worth the hassle to debug this. ([You can find some background information on shared libraries here](https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html)).

Therefore, I would suggest to start a fresh virtual environment and reinstall all dependencies there. (Also note that you seem to have conflicting `mmy_env` and `my_env` virtual environments).  

If updating the software versions inside your virtual environment is not an option, you could try [to install the old library version into your virtual environment](https://anaconda.org/pwwang/glibc214).

Thias
