### ISSUE TITLE
multiqc with trimmomatic and STAR log files

### ISSUE THREAD

**Issue by ARW-UBT** [ewels/MultiQC#1621]
### Description of bug

Hello, 
I ran trimmomatic and STAR on fastq data in the same folder. The log files were created (and are not empty). 

Trimmomatic: 
```
Sc-H-1_S5.trim_out.log
Sc-H-2_S6.trim_out.log
etc.
```

STAR:
```
trim_Sc-H-1_S5_starLog.final.out
trim_Sc-H-2_S2_starLog.final.out
etc. 
```

However, only the STAR logs were recognized by 'multiqc .'. Is there a specific requirement for trimmomatic log files?

GREAT tool, thanks for it!

### File that triggers the error

[multiqc.log](https://github.com/ewels/MultiQC/files/8003453/multiqc.log)

### MultiQC Error log

```console
$ multiqc .
```

**Comment by ewels** [comment]
It's a bit difficult to help without seeing one of the Trimmomatic logs sorry (eg. `Sc-H-1_S5.trim_out.log`). See the docs for how MultiQC finds these files: https://multiqc.info/docs/#trimmomatic (basically any file with the word `Trimmomatic` in the contents..).

Can you please check the [troubleshooting docs](https://multiqc.info/docs/#troubleshooting-1) and if that doesn't help, attach a file that you think should be found but that is missed..

Phil

**Comment by ARW-UBT** [comment]
Hi, 
I have created log files with the string 'trim_out.log' as specified in your documentetion (directing it to a file e.g. trimmomatic command 2> trim_out.log), but I tried it also with files containing 'Trimmomatic' in the filename. Was not recognized by multiqc. 
I have attached a log file created by trimmomatic's '-trimlog' option to this post (sorry, I assumed the multiqc log file would contain relevant info)
Thanks again for your support!

The log file is zipped as .log file types seem not to be allowed for uploading.
[Sc-H-1_S5_trim_out.zip](https://github.com/ewels/MultiQC/files/8013234/Sc-H-1_S5_trim_out.zip)

**Comment by ewels** [comment]
No the filename is irrelevant, it's looking for `Trimmomatic` in the file contents. You can call the filename whatever you want. See [the docs](https://multiqc.info/docs/#step-1-find-log-files) for more details for how this works (in combination with the [module docs](https://multiqc.info/docs/#trimmomatic)).

`trimmomatic command 2> trim_out.log` (where `command` is the rest of your normal Trimmomatic command) should be along the right lines though. You're looking for files that look something like the [example log files](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/trimmomatic) that the module is tested with / was built with.

**Comment by ARW-UBT** [comment]
Ok, I could solve it: Multiqc requires the output of 'step 2' (2>) as the input and not the output of '-trimlog'. 
Thanks,

**Comment by ewels** [comment]
Yeah, `2>` is for "standard error" (aka stderr) terminal output, not step 2.

Command line tools can typically output two types of text to the terminal: standard out (stdout) and standard error (stderr). By default these are both shown in your terminal prompt window, but you can "redirect" them to a file. Then instead of showing up in your terminal they are written to a file. `>` does this with stdout and `2>` does this with stderr. Other symbols do variations of this, for example `&>` does both stderr and stdout together.

Quite a lot of bioinformatics tools print summary information to the terminal and not to any files. MultiQC runs well after they are complete so needs this information in a file. So that's why for Trimmomatic, you need to redirect that stdout summary information to a file for MultiQC to parse.

I'm not sure what `-trimlog` is, but that's specific to Trimmomatic and doesn't seem to have any relevant information for the MultiQC report.

**Comment by ARW-UBT** [comment]
Thank you for correcting my misinterpretation of 2> (stderr). I'm more a user of tools than a developer... :-)
