### ISSUE TITLE
multiqc generates two rows for each sample when summarising qualimap reports

### ISSUE THREAD

**Issue by Rohit-Satyam** [ewels/MultiQC#1734]
### Description of bug

I don't understand why I am observing two rwos per samples in multiqc report of qualimap. Here is the preview

![image](https://user-images.githubusercontent.com/55479480/182020814-d16cedaf-a478-41cc-9f67-0ee8ad1952dd.png)
 Is there a way to avoid it?

I ran my qualimap as follows:

```bash
ls -1 ~/Documents/amits_swga_data/curtisi/markdup/*bam | head -n 3 | while read p; do n=$(echo $p | xargs -n 1 basename | cut -f 1 -d '.'); ~/qualimap_v2.2.1/qualimap bamqc -bam $p ; done
```

**Comment by ewels** [comment]
It's because your samples have different names:

- `C1.marked_duplicates`
- `C1.marked_duplicates_stats`

The `_stats` suffix means that they aren't identical and the rows aren't merged.

It's quite easy to remove this suffix via a MultiQC config file. See the docs here: https://multiqc.info/docs/#sample-name-cleaning
