### ISSUE TITLE
[probably not] Split modules out into separate Python packages

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1788]
# Discussion

This is a big one.

### Current state

At the moment, MutiQC is written and distributed as a single Python package. The code is structured with a core library then extensible plugins, report templates and modules. Each module parses the output from another bioinformatics tool.

Each plugin, template and module is installed and loaded using a separate named setuptools hook with a named group (eg. multiqc.modules.v1 - see [code](https://github.com/ewels/MultiQC/blob/master/setup.py)). This means that other separate python tools can install modules using the same named group and MultiQC will execute them as if they were part of the main tool. This architecture allows extensibility and customisation without having to fork and edit the main MultiQC codebase.

### Learning how to delegate

In order to help with code maintenance for MultiQC, I need to get others involved and delegate responsibilities. The most obvious way to do this is to split up maintenance on the module level (support for each bioinformatics tool) - this is already somewhat how the contribution model works.

There are a few ways in which this could be done, but the simplest would be to make use of the extensible module structure that MultiQC uses and split up the codebase. If each MultiQC module is in its own GitHub repository and has its own PyPI / Conda package, each can have its own set of maintainers who are responsible for that chunk of code. If the GitHub repositories are hosted under the [MultiQC GitHub organisation](https://github.com/MultiQC) I will maintain overall ownership to avoid any being abandoned, but each can have its own set of collaborators. Unfortunately, PyPI and bioconda don’t have an inherit organisation structure in the same way, but an ad-hoc convention of using the `multiqc-` prefix to each package name could help with standardisation.

Having each MultiQC module maintained as its own code base allows each module to do its own releases. This means that there would be no period of waiting for a core MultiQC release: module bug fixes and features could be written, merged and released in a day.

### Solving installation

The problem with the above model is that installing the MultiQC package is no longer enough. We now need to install MultiQC and every MultiQC module that we want to use.

One way to get around this for PyPI and Conda is to list every MultiQC module package as a package requirement (eg. in [setup.py](https://github.com/ewels/MultiQC/blob/9760f7561a56c1295a661471d7447abd085b8020/setup.py#L80) and the [conda recipe](https://github.com/bioconda/bioconda-recipes/blob/d41a392df684dbcd47a820b1cee1a62057c960ee/recipes/multiqc/meta.yaml#L22-L37)). Then the package managers should go off and install each module when installing MultiQC. If each new core MultiQC release specifies the latest module version number using `>=` then upgrading MultiQC will also upgrade all modules, but if there is a newer version at the time of the installation then that will be used instead.

A problem with not pinning exact module version numbers is that this could cause issues if people try to install older versions of MultiQC which are missing features used by the newest release of some MultiQC modules. I’m not sure how to get around this, suggestions welcome. The complex versioning could also impact reproducibility a little - running the same version of MultiQC will not be sufficient to ensure that the same report is generated. The version of every module package would need to be pinned as well.

For people using containers (eg. Docker), the above solution should work well for releases. We can also add automation for the MultiQC GitHub organisation that triggers new package builds for core MultiQC whenever any MultiQC module is released. This would mean that the multiqc:latest image always contains the most up to date version of each module.

### Tests and versions

To scale whilst maintaining code quality, we need better tests. With separate repos for each module, it gets easier to keep tests and test data within the same repo as the code. We also need more automated tests to check code quality. Some will need to be custom written, but hopefully many can be taken care of refactoring using Pydantic models - see https://github.com/ewels/MultiQC/issues/1790

It may be worthwhile to write some kind of automated sync mechanism / code linting (eg. files exist / are not changed etc) as we have for @nf-core.

All modules will be able to maintain their own versioning system after being split up. This is helpful as they can follow semver following their data models. So if columns are renamed or removed, breaking backwards compatability with any APIs expecting a certain data model, they can push up the major version.

# Plan for implementation

Modules can be moved in a slow and steady way, in combination with refactoring associated with https://github.com/ewels/MultiQC/issues/1790. I can create a repository template / cookiecutter repo to scaffold the code.

Once we have a solid implementation plan and pattern with some modules ported over and working well, it may be worth running a hackathon to get help from the community with porting modules over.

**Comment by multimeric** [comment]
> One way to get around this for PyPI and Conda is to list every MultiQC module package as a package requirement

I would like to offer some dissent here. I would like to see the modules and core decoupled as much as possible. If we make multiqc depend on each module, then it won't be possible to only install a subset of modules, and you will always have the maximal installation. On the other hand, the modules themselves will need to depend on `multiqc` just so that they can specify the range of versions they are compatible with.

Since we're making a new major version, I think we can adjust the workflow a little. I don't personally have an issue with asking the users to install each module individually, especially because I think the average user will just start with a handful of modules (`fastqc` is probably very common), but they certainly won't need everything. Maybe we could edit the installation instructions to include some example "preset groups" e.g. for genomics we might suggest the following command:
```bash
pip install multiqc multiqc-fastqc multiqc-samtools multiqc-mosdepth
```
Then we can have a number of other example presets for other subdomains of bioinformatics. However at their core, the modules can then stay decoupled from multiqc.

**Comment by ewels** [comment]
Yes this is a good point, but it needs to be fairly painless. One of the big draws to MultiQC for a lot of people is that it "just works".

What about using [optional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies)? Then we can have single preset commands:

```bash
pip install multiqc                                  # installs just the core library
pip install multiqc[all]                             # installs everything, as proposed in the issue above
pip install multiqc[common]                          # could have other named groups for common presets
pip install multiqc multiqc-fastqc multiqc-samtools  # Installed as you propose above
```

Are you still ok with the docker container having the maximal installation? A lot of people use this (eg. in pipelines) from either the MultiQC repo or from biocontainerrs. I don't see any way around that having everything installed always.

**Comment by multimeric** [comment]
> What about using [optional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies)?

I think this is okay? But I'm not sure. Most plugin systems *don't* do this, possibly because it inverts the dependency relationship. So we end up with plugins depending on `multiqc`, which in turn depends on the plugins. It might confuse the dependency resolver, but maybe not. If we do this, I think at least we could never depend on specific plugin versions, or it would be very confusing and probably break `pip`. The "true" dependency relationship is that plugins depend on `multiqc`, so that's where the version specification should lie.

> Are you still ok with the docker container having the maximal installation?

Yeah, this is fine. It's only the python package that I'm worried about, for dependency resolution reasons.

**Comment by Redmar-van-den-Berg** [comment]
I'm worried it will add a lot of overhead to split the modules off into truly independent packages. For example, you could get a case where module A only supports an old version of MultiQC, while module B only works on the latest version. That would mean that as a user, I cannot build a pipeline that includes a MultiQC report for both A and B.

> To scale whilst maintaining code quality, we need better tests. With separate repos for each module, it gets easier to keep tests and test data within the same repo as the code. We also need more automated tests to check code quality. Some will need to be custom written, but hopefully many can be taken care of refactoring using Pydantic models - see https://github.com/ewels/MultiQC/issues/1790

I agree that it would be nice to have better tests, in fact I recently spent some time looking at all the test data in the MultiQC_TestData repository. While it is quite large, both in terms of number of files and size, this is mainly due to a few "misbehaving" modules that add hundreds of files, or giant files with thousands of lines.

I would be interested in helping out with cleaning up the data files from MultiQC_TestData and add them to the main repository, which should not massively increase the size. With something like [pytest-workflow](https://pytest-workflow.readthedocs.io/en/stable/#writing-tests-with-pytest-workflow) it is very easy to add tests, even for pretty high-level checks such as modules not cleaning/renaming/ignoring sample names.

With better tests, it should be possible to release MultIQC way more often, without the added complexity of splitting each module off into it's own project, which have to be packaged for pypi, conda, etc.

**Comment by apeltzer** [comment]
> I'm worried it will add a lot of overhead to split the modules off into truly independent packages. For example, you could get a case where module A only supports an old version of MultiQC, while module B only works on the latest version. That would mean that as a user, I cannot build a pipeline that includes a MultiQC report for both A and B.

We can certainly get around that by imposing minimum / maximum required versions for a package no & should not run into this too frequently given that tests with real test data are created and thus the dependency packages are receiving rather more frequent fixes than currently, at least I would assume so. 


> > To scale whilst maintaining code quality, we need better tests. With separate repos for each module, it gets easier to keep tests and test data within the same repo as the code. We also need more automated tests to check code quality. Some will need to be custom written, but hopefully many can be taken care of refactoring using Pydantic models - see #1790
> 
> I agree that it would be nice to have better tests, in fact I recently spent some time looking at all the test data in the MultiQC_TestData repository. While it is quite large, both in terms of number of files and size, this is mainly due to a few "misbehaving" modules that add hundreds of files, or giant files with thousands of lines.

Agree here very much - would also be easier to spot these sort of things when the tests are e.g. kept in each repository instead of one central location for all "modules".

 
> I would be interested in helping out with cleaning up the data files from MultiQC_TestData and add them to the main repository, which should not massively increase the size. With something like [pytest-workflow](https://pytest-workflow.readthedocs.io/en/stable/#writing-tests-with-pytest-workflow) it is very easy to add tests, even for pretty high-level checks such as modules not cleaning/renaming/ignoring sample names.

🙇🏻 

> With better tests, it should be possible to release MultIQC way more often, without the added complexity of splitting each module off into it's own project, which have to be packaged for pypi, conda, etc.

Packaging these however is also something we can automate - so I would only worry about the _one time_ effort here to split out modules.

**Comment by apeltzer** [comment]
The fact _that_ it was mostly @ewels _so far_ that kept the PRs merged / worked on most of it is also likely the reason why there were so infrequent updates ;-) Another benefit would also be that users can define which modules to use (= multiqc-light) and broken ones (happened sometimes in the past, though honestly not very often) would not affect everyone apart from people who are in fact using that exact module. 

I totally get what you mean in terms of maintenance and agree on a large part of what you're lining up here in your chain of arguments (especially the single person aspect ;-))! Not sure that we can achieve the very same thing by having everything in one repository and only making the tests better and more complete as it still means we have to have a MultiQC release that contains all changes more frequently - while the split out approach would not necessarily need this apart from potentially breaking changes in core vs modules.

**Comment by ewels** [comment]
Some interesting points, thank you for your input @Redmar-van-den-Berg !

1. Generally speaking, the lack of other developers and reliance on me is the thing I'm hoping to improve upon. The intention behind many of these "big picture" issues is to attract more developers and build a community around MultiQC.
2. Your point about the test data not being that big is interesting. I just downloaded a flat zip file out of curiosity. Some numbers: _Total size:_ `232.6 MB`. _Size with with 7 biggest modules removed:_ `69.1 MB`. You're right that it could be cleaned up, but I think it would be tough to get it down to a point that I'd be happy with. I think if we're not splitting into separate repos, it would be easier to use copy + paste fragments for unit tests and keep the test files in their own repo as is done currently.
3. I like pytest-workflow a lot, we have used that for @nf-core and it's a powerful tool. For example, I could imagine using `contains` / `must_not_contain` for checking that a sample has been renamed as expected. The downside is that it would probably still need quite a lot of manual setup for every module. I _hope_ that by refactoring the core MultiQC module code we can write some nice bespoke tests that can automate much of this for us without having to do anything at module level. There's nothing to say that we can't have both though.
    * Side note: it's a pet peeve of mine to have a [root level](https://pytest-workflow.readthedocs.io/en/stable/#getting-started) `tests` directory for something like MultiQC where there are hundreds of modules (directory names) to dig through when you want to make a change. Would be nicer if we could keep a `tests` subdirectory next to the pipeline code imho.
5. I agree with @apeltzer that packaging for PyPI + Conda etc should be fairly trivial. Simply a case of having a GitHub Action for PyPI with org-level secrets, then me creating a new package there for each module. Creating new conda recipes is a bit of a time sync, but would be 99% copy and paste, then they automatically have PRs based on new PyPI releases. Still a time sync, especially at the start, but not terrible. 
6. Lots of focus in this issue on breaking dependencies, but I'm really not worried about that at all. My suggestion above is that all "core" packages would still be centrally maintained in this org. So it would be trivial to test all of them when breaking changes are made to core MultiQC, and update any that need it. In practice I can't see this situation of having packages with different MultiQC requirements ever happening - modules might get ahead of MultiQC, but never behind.

Everyone agrees that more frequent releases = a good thing. If we can solve this in another way (more testing, me not being on paternity leave so often, team of maintainers, many options) then it may be that splitting out into packages is not needed.

I've been going back and forth on it for 2 years now and have always been very split on it. I think that there are many other lower-hanging fruits to be had, so this really comes at the end of the queue for the v2.0 releases. Maybe by the time we get to it, we'll be satisfied with the current situation and can drop the idea.

**Comment by jchorl** [comment]
Are there other extension-heavy python packages we could learn from?

It would be good to spell out what the real problems are. If the problem is around centralized maintenance burden, but we plan to continue to put all the packages under a centralized org, we may end up incurring a lot of packaging/installation complexity only to end up with similar issues.

This discussion has veered a bit into problematic tests and what tech we might use for testing. I'd suggest constraining conversation here to just packaging (and the packing-specific parts of testing).

I'll throw out two wild ideas:
- You can submodule in other repos so that other folks can own their repos, but they need to cut a PR to "bump" the submoduled version into this repo
- You can codeowner the respective package dirs

I think we take for granted that when you install multiqc, by and large all the modules _just work_. It's all versioned together.

Each come with pros and cons. Problems I'm worried about with conda/pip approaches:
- While you can impose versioning with version constraints, nobody wants to deal with a compatibility matrix. If some package owner ships a breaking change, who would be responsible for updating the compatibility restrictions? What if multiqc wants to ship a breaking change?
- `multiqc` is clearly the multiqc org. If you adopt `multiqc-*`-style packaging, do you have to worry about folks namesquatting/seeming official just because they grab `multiqc-fastqc-official` on bioconda?
- Would we need to test version-matrices in CI? E.g. testing the last 5 versions of multiqc against the last 5 versions of every module. Could get expensive, fast.

Anyway, packaging is an interesting idea. I agree it would be helpful. There is clearly a problem today with package maintenance. This just seems like a huge effort time-wise and we should make sure we get sufficient benefit to justify.

**Comment by ewels** [comment]
The original motivation for this idea goes back to around 2020 when I started drafting a blog post with ideas to make MultiQC more sustainable. The motivation was two things:

1. Share maintenance burden by sharing out responsibilities (code ownership)
2. Make it easier to ship small and often to get bug fixes / features out fast. I have been working on MultiQC with infrequent spikes of activity (often a series of late nights!) and so doing little and often releases has been very tough.

However. It's now 2023 and there's a job ad out for someone to work on MultiQC full time (#1894) and with it, the chance that I may also get more time to work on the project. The prospects of being able to handle reviewing and releases is now looking much better and so my motivation for any of this issue is suddenly dwindling.

I really like the idea of scoped `CODEOWNERS` files 🤔 I think that could solve a lot of the issues that I was aiming at with this, without the logistical software problems. Could even be clever and have teams for each module and link a CI workflow up to the New Issue template, where if someone selects a module in a dropdown the relevant team gets assigned..?? I'll split this out into a new issue.

Considering closing this now as a `will-not-implement` but will leave it open a little more to see if anyone has any further thoughts.

**Comment by vladsavelyev** [comment]
Agree that having more resources to work on the project would help with more frequent releases, and would largely solve the problem.
* As noted, maintenance can be shared by `CODEOWNERS` for PR default reviewers. Modules are largely independent in the code base, so there are not many clashes between code parts.
* Users who want to be independent can already work on extensions/plugins in separate repos, or with forks/branches.
* Separate repos for each module would soon lead to most of them looking empty and abandoned, apart from bulk updates following refactorings and breaking changes in the core MultiQC. The monorepo, however, is guaranteed to have lots of activity.
* But if we went that route, designing it the way of `multiqc[all]` that depend on `multiqc-module`, and  `multiqc-module` depending on `multiqc`, works nicely with pip. So can keep it as an alternative.

**Comment by ewels** [comment]
Thanks everyone for the thoughts and discussion 🙏🏻 

Consensus seems to be that monorepo is better, let's stick with that 👍🏻
