### ISSUE TITLE
Docummentation in the official page still states `--cl_config`

### ISSUE THREAD

**Issue by sunta3iouxos** [ewels/MultiQC#1825]
This is just a notification that in the official [documentation](https://multiqc.info/docs/#configuring-multiqc) of multiqc there needs to be a simple adjustment from: `--cl_config` (underscore) to `--cl-config` (hyphen).

The following will not work anymore:

```bash
multiqc . -f \
-c /home/hthiele0/rnadepipe/data/multiqc_config.yaml \
--cl_config "report_header_info: [ Project: 'ZEC001', Project ID:    'ZecchiniV', Analysis ID: 'rescuedpFH1_Vs_UOK262', Species: 'Homo_sapiens',     Reference: 'h38.105' ]"
```

```console
Usage: multiqc [OPTIONS] [ANALYSIS DIRECTORY]                                  
                                                                                
 This is MultiQC v1.13                                                          
 For more help, run 'multiqc --help' or visit http://multiqc.info               
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ No such option: --cl_config (Possible options: --cl-config, --config)        │
╰──────────────────────────────────────────────────────────────────────────────╯
```

**Comment by ewels** [comment]
Thanks for pointing that out @sunta3iouxos ! I've just gone through and updated hopefully all instances of that.

I also went back to figure out when this was removed and have retrospectively added notice of it to the Changelog for the v1.13 release.

Apologies for any trouble caused, I'm not actually sure if this was an intentional removal or not! Either way, I should have been a bit more careful when I did it.
