### ISSUE TITLE
MULTIQC Error - No analysis results found. Cleaning up (when using json files)

### ISSUE THREAD

**Issue by gauri080191** [ewels/MultiQC#1839]
Hi, I am using multiqc to read my output .json files that I got after running the Encode-atac-seq-analysis pipeline (https://github.com/ENCODE-DCC/atac-seq-pipeline). However, I get the error saying -  No data found in qc1_mqc.json
                                                         No data found in qc_mqc.json
                                                         No analysis results found. Cleaning up..

What can I do so that it can recognize my output files. I am not sure whether these output filles and the tools that generated it are supported by MULTIQC and where can I make the change to make it work. I have attached the screenshot of the json file for your review. Let me know additional files you need from me.
<img width="1786" alt="Screen Shot 2023-01-04 at 11 41 11 AM" src="https://user-images.githubusercontent.com/115571976/210605368-ee99a105-f8a5-4d0a-840a-78b3e2f447bc.png">

**Comment by ewels** [comment]
Hi @gauri080191,

It's a bit difficult to tell from a screenshot, but I don't think that this file has anything to do with MultiQC. Looking at https://github.com/ENCODE-DCC/atac-seq-pipeline it seems that the pipeline does its own reporting. As such, there's no reason that MultiQC should recognise your output file in this case.

This pipeline may or may not produce results that are recognised by MultiQC. If you would like to generate a report with these, please run MultiQC on the results and log files instead of this JSON file. See the [MultiQC docs](https://multiqc.info/docs/#running-multiqc) if in doubt.

Next time please drag + drop files to attach, zip them if needed :)

Phil
