### ISSUE TITLE
New plot type: scatter plot (for general stats)

### ISSUE THREAD

**Issue by dcdanko** [ewels/MultiQC#184]
Seems like a general, useful, feature.

I am currently working on this.

**Comment by ewels** [comment]
Hi @dcdanko,

I've thought about adding scatter plot functionality a few times, but have specifically decided against it. This is because MultiQC can be (and often is) run on large numbers of samples. We commonly run hundreds of samples at our sequencing centre and people doing single cell experiments can push this into the thousands. It's possible to understand data from a line graph or bar plot with such numbers, but a scatter plot becomes pretty incomprehensible as soon as you get more than ten or so different colours.

Every time I've wanted to use a scatter plot in the past, I've been able to reduce the complexity of the data to something that can work in a different plot type. In some cases I've added functionality to 'click through' to more complex data (eg. the FastQC sequence content plot or RSeQC junction saturation plots).

Phil

**Comment by dcdanko** [comment]
Makes sense. I still plan to add this to me fork.

**Comment by ewels** [comment]
Yeah absolutely. And of course any module can have it's own custom plots. I'm purely thinking about the core functionalities here. which will be used by many modules.

One exception to my logic is if each sample has a single point. This is something I'm planning to do for a custom module we're going to use in-house, plotting samples on a 2-axis PCA plot.

If we find that lots of modules want / need scatter plots and that my fears about data overload with high sample numbers are unfounded we can always move this code back into the core at a later date.

Phil

**Comment by ewels** [comment]
Sorry, some explanation - I reopened as I think I was probably a little hasty in turning this down. I've been mulling it over and can think of quite a few instances where scatter plots are the best approach. I'll look into adding proper support for this soon.
