### ISSUE TITLE
Fastqc failed sample name discrimination

### ISSUE THREAD

**Issue by bricoletc** [ewels/MultiQC#1849]
### Description of bug

Hi -thanks for the great tool.

This is a small and specific bug report. I ran fastqc separately on read files called `sname.fastq.gz` and `sname_trimmed.fastq.gz`, then `multiQC`, and the latter only recognised a single sample/report - for `sname`. 

The `Filename` attribute in `fastqc_data.txt` directories is indeed different - `sname` vs `sname_trimmed` - which is what I understand the tool [bases recognition on](https://multiqc.info/docs/#fastqc).
Replacing `_trimmed` with `_cutadapt` restored correct functionality.

**Comment by ewels** [comment]
Yup, this is not a bug - it's actually working as intended.

It happens because MultiQC is "cleaning" the sample names, automatically removing the `_trimmed` part which means that they end up with identical names and overwrite one another. It's in the code here:

https://github.com/ewels/MultiQC/blob/cfbce33f401b7ddb2a5d3c2b351fa997b8c08afb/multiqc/utils/config_defaults.yaml#L270

Docs:

- [Not enough samples found](https://multiqc.info/docs/#not-enough-samples-found)
- [Clashing sample names](https://multiqc.info/docs/#clashing-sample-names)
- [Sample name cleaning](https://multiqc.info/docs/#sample-name-cleaning)

Possible solutions:

- Use `--fullnames` to turn off all sample name cleaning
- Don't use `_trimmed`, as you found out
- Prepend directory names with `--dirs`
- Set `fn_clean_trim` in your MultiQC config, overwriting the default list and so no longer cleaning off that extension

**Comment by bricoletc** [comment]
Oh wow - thanks!

**Comment by ewels** [comment]
No problem 😊
