### ISSUE TITLE
"Export Plots" functionality only downloads the first 10 plots.

### ISSUE THREAD

**Issue by robsyme** [ewels/MultiQC#1873]
When using the "Export" tab in the right-hand sidebar and more than ten plots are selected for export, only the first 10 plots are downloaded.

I have tried this on both Chrome and Safari, so I don't think that this is a browser limitation.

Example report: [5_multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/10886096/5_multiqc_report.html.zip)

**Comment by ewels** [comment]
How has no-one ever reported this before? 🤯

**Comment by vladsavelyev** [comment]
After playing with this a bit, it looks like it's a browser limitation after all. It seems to behave differently across browsers though. 

Here is a toy HTML page with one button that generates and downloads 20 files. In Chrome, for me, it would download only the first 10 files (`sample_1.txt through `sample_10.txt`). Safari though downloads only one last file (`sample_20.txt`).

```
<!DOCTYPE html>
<html>
<head>
  <title>Test downloads</title>
</head>
<body>
  <button id="downloadButton">Download Files</button>

  <script>
    document.getElementById("downloadButton").addEventListener("click", function() {
      for (let i = 1; i <= 20; i++) {
        const content = `sample_${i}`;
        const fileName = `sample_${i}.txt`;

        const blob = new Blob([content], { type: "text/plain" });
        const link = document.createElement("a");
        link.href = URL.createObjectURL(blob);
        link.download = fileName;
        link.click();
      }
    });
  </script>
</body>
</html>
```

Though after multiple attempts, Chrome suddenly learned to download all 20 at the same time, so it's not very reproducible.

One obvious solution would be to put all images into a zip archive and just download that archive instead. I tried to dig through the HighCharts codebase to find a more or less elegant solution for that with no success. I think since we will be looking for a HighCharts replacement, probably it's not worth it to hack it too much.

Another idea is to add a small timeout between each batch of 10 downloads. The problem is that it would require the user to confirm each batch in the browser, which is not super user-friendly, and also, quiet hacky.

So no solution for now, let's discuss options!

**Comment by ewels** [comment]
I think zipping if there are > 8 plots or something could be good. Pretty sure I've written in-browser JS creation of zip files in the distant past at some point, feel like it should be possible..? 🤔 

I'm not sure that a new plotting library will solve this issue, as we will still want the ability for people to export multiple plots in one go.
