### ISSUE TITLE
[Question]: likely date for new MultiQC release

### ISSUE THREAD

**Issue by tamuanand** [ewels/MultiQC#1900]
Hi

I was curious to know when the next release is slated for - interested in some new tools that are in PRs

Also happened to see this: https://github.com/ewels/MultiQC/issues/1784 

Thanks in advance

**Comment by ewels** [comment]
Next release will hopefully be very soon, though it won't include all PRs as it's a lot of work going through the review process (should hopefully get better soon! See #1894 !)

I'll put together a milestone for v1.15 so that the roadmap is clear. If all goes well should hopefully be in a week or so (famous last words).

**Comment by ewels** [comment]
https://github.com/ewels/MultiQC/milestone/19
