### ISSUE TITLE
Beehive plot suggestions

### ISSUE THREAD

**Issue by jfreimer** [ewels/MultiQC#191]
After updating to the latest dev version, my general statistics table isn't displaying correctly.

![screen shot 2016-04-26 at 2 48 28 pm](https://cloud.githubusercontent.com/assets/7303848/14835325/0e237f84-0bbe-11e6-9cd6-f2b406445aea.png)

**Comment by ewels** [comment]
Yes it is ;)
> **v0.6dev**
> * New beeswarm plot type. General Stats table replaced with this when many samples in report.

This is a new feature to stop reports from having super-huge General Statistics tables which are impractical. The beeswarm plot is an alternative which takes up less space.

You're right that I need to smooth the transition of this new feature a bit though. For starters, [the threshold](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/config.py#L39) is currently set a bit low. I should probably add an explanation message or something too.

Short term, you can set the config option `genstats_beeswarm_numseries` to a very high number to disable this. I am currently working on a branch where I'm refactoring all of this code though, so that config option name will change in a day or two, plus the default will be quite a bit higher.

Generally speaking, as one of the first people to see this new feature, any feedback?

Phil

**Comment by jfreimer** [comment]
I generally work with 10-20 samples so find the general stats table much more useful. For lower number of samples it is much quicker to glance through everything in a table rather scroll over each sample. A few suggestions:
1) I realize that the dots are colored by what program the numbers come from, but that is not immediately obvious. I also don't think it is the most useful to color code this way. 
2) In my screenshot I have % aligned and M aligned from both featureCounts and tophat. However, I have to scroll over the dots to see which is which. It would be nice if the y-axis was labeled by what program the stat comes from rather than just color coded.
3) Maybe there is a way to do this already, but I would add something to the beehive plot where you can quickly select samples into groups and color code all metrics by that. Usually will want to check that groups of samples are behaving as expected (check that GC % or aligned % etc are not segregating by knockout vs wildtype). I think if you have 50+ samples it would be nice to see that low quality outliers are a mix of your conditions rather than having to hover over each dot and see if they are all in one specific group or batch.

**Comment by ewels** [comment]
ok great, thanks for the feedback! I will bump up the default to around 200 rows I think, maybe a little more.

1. Ok, yes I think you're probably right. I'll leave them all the same colour, it's also better for sample highlighting.
2. Good suggestion, I think I know how to approach this. I'll see if I can have both.
3. I intend to tie this plot into the Toolbox highlighting panel. So you'll be able to enter a search string there and all matching samples will be highlighted. This hasn't been written yet.

Might be nice to have click events automatically add that sample to the highlighting toolbox actually. Could work for the table as well. I'll have a play.

**Comment by ewels** [comment]
Hi @jfreimer,

I've made a few changes above - the default threshold is now 500 rows instead of 50. There's also a warning text above the plot explaining why there is not table in the report.

Points have a uniform colour and module names are shown alongside the row title. The highlighting thing is more complex, so I've created a separate issue (#193) to track this for future work.

Thanks again for the suggestions! Let me know if you have any more. You can test out what I've changed by adding `max_table_rows: 5` to your `~/.multiqc_config.yaml` file.

Phil
