### ISSUE TITLE
support bamdst

### ISSUE THREAD

**Issue by gudeqing** [ewels/MultiQC#1984]
### Description of feature

Hi, is it possible to support the following tool ?
https://github.com/shiquan/bamdst

Best regards!

**Comment by serge2016** [comment]
@gudeqing why do you use this tool? What is the advantage?

**Comment by gudeqing** [comment]
> @gudeqing why do you use this tool? What is the advantage?

well，I used several other tools like  mosdepth, qulimap and gatk, but only find this one satisfy all my requirements for a targeted panel. Simply, it is fast and good and easy to use.  Here is a part of metrics can be derived from bamdst result.  If you have any other good suggestion, please let me known.
![image](https://github.com/ewels/MultiQC/assets/30919159/62919b25-77b3-499d-8f73-561fddceb900)

**Comment by ewels** [comment]
Please use the issue template when requesting new modules: https://github.com/ewels/MultiQC/issues/new?template=module-request.yml

It ensures that we have all of the information that we need. Most important is to have some example data to use for building the module and running tests.

I'll leave this issue open for now so that you can add this info manually. But if you prefer you can create a new issue using the template and we can close this one. Up to you.

**Comment by tamuanand** [comment]
@ewels -  I believe example data is provided here - https://github.com/ewels/MultiQC/issues/2158

**Comment by ewels** [comment]
Thanks 🙏🏻
