### ISSUE TITLE
RSeQC: division by zero on all-zeroes output (via nfcore rna-seq)

### ISSUE THREAD

**Issue by berk1835** [ewels/MultiQC#2033]
### Description of bug

File triggering error appears consistent with inner_distance_freq text files of other samples, which have had no issues. Any suggestions would be much appreciated.

### File that triggers the error

[10975_b2_H4_S20.inner_distance_freq.txt](https://github.com/ewels/MultiQC/files/12567854/10975_b2_H4_S20.inner_distance_freq.txt)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.13
  
  |           multiqc | MultiQC Version v1.15 now available!
  |           multiqc | Only using modules: custom_content, fastqc, cutadapt, sortmerna, star, hisat2, rsem, salmon, samtools, picard, preseq, rseqc, qualimap
  |           multiqc | Search path : /directory/work/9d/44892c41544cf22dc6d43ee8341002
  |            report | Skipping 17 file search patterns
  |         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 331/331  
  |    custom_content | software_versions: Found 1 sample (html)
  |    custom_content | nf-core-rnaseq-summary: Found 1 sample (html)
  |    custom_content | fail_strand_check: Found 21 samples (table)
  |            hisat2 | Found 23 reports
  |    MarkDuplicates | Skipping MarkDuplicates sample '10975_Negative_S23' as log contained no reads
  |    MarkDuplicates | Skipping MarkDuplicates sample '10975_Negative_S23' as log contained no reads
  |    MarkDuplicates | Skipping MarkDuplicates sample '10975_Negative_S23' as log contained no reads
  |            picard | Found 22 MarkDuplicates reports
  |            preseq | Found 21 reports
  |             rseqc | Found 23 read_distribution reports
  ╭───────────────── Oops! The 'rseqc' MultiQC module broke... ──────────────────╮
  │ Please copy this log and report it at                                        │
  │ https://github.com/ewels/MultiQC/issues                                      │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ ./rseqc/inner_distance/10975_b2_H4_S20.inner_distance_freq.txt
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [ ] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by skchronicles** [comment]
I just wanted to add a comment here. @vladsavelyev is correct. If you run into this issue, there is a bigger problem with how the data was processed that needs to be addressed. This is a red herring/signal of a bigger lingering issue.

I just ran into this same problem, and it was due to a bug I had in a script that merged fastq files which were split across flowcell lanes. In the script, I accidentally forgot to update a variable name after copy/pasting some code which caused the contents of the R1 and R2 fastq files to be the same. Meaning, that the contents of the merged files were the same for **${sample}.merged.R1.fastq.gz** and **${sample}.merged.R2.fastq.gz** (just the file names were different). This would explain why my inner distances were all zero. 

I just wanted to throw this out there, just in case someone else runs into the same problem.

**Comment by berk1835** [comment]
Thanks @skchronicles, my 'bigger problem' was similar. The issue was within the trimming script - in short, it duplicated the forward read for each sample in the file for the reverse reads, explaining why my inner distances were all zero.
