### ISSUE TITLE
Software Versions: Add support to all modules

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#2042]
Now that https://github.com/ewels/MultiQC/pull/1927 is merged and stable, we should go through all modules adding support for reporting version numbers wherever we can!

**Comment by pontushojer** [comment]
I started to work a bit on this in PR #2051

I am using a Google Sheet to make it easier to keep track of which modules has version info, if its been added and any other relevant information. That way it should be easier to collaborate since its soooo many modules to go through. Here is a link: https://docs.google.com/spreadsheets/d/1amPRcK_Lewudyli5ql9We73tC1Txm8eNvjKfQVXW0u0/edit?usp=sharing

Two suggestions
1. Should we add version information if is in a file that is not currently parsed but part of the software output? For example, for  `fastp` we only parse the JSON ATM while version info is only found in the HTML report. I think that we should.
2. As an extension of (1) should we parse the output of something like `tool --version &> sample_name.module_version.log`. This is primarily for tools that have no version info in their normal output. For example `mosdepth` does not output version info but calling `mosdepth --version` produces output from which the version could be parsed. We could allow users to direct this output to a file like this `my_sample.mosdepth_version.log` from which we could get the sample (`my_sample`) and the module (`mosdepth`) require to include sample version info in the report. This would probably be quite a big addition, maybe for its better a separate issue.

**Comment by ewels** [comment]
Just chatting to @vladsavelyev - it's too much work to tick them all off manually here. We should add a lint test to automatically highlight any that are missing.

We could adapt the software versions function to be able to explicitly report `False` or `None` when it's impossible to scrape the version. Then we can hopefully check if the function was called, and fail `--lint` runs if it's not. Then any new modules added will fail CI if the author hasn't added this. Also it provides a way for us to keep track of what's done as we move towards checking them off.

**Comment by ewels** [comment]
Completed, even with the linting to check that every module attempts this ✅ 

Thanks @pontushojer! 🎉
