### ISSUE TITLE
Trimmomatic looks problematic

### ISSUE THREAD

**Issue by pgonzale60** [ewels/MultiQC#217]
Hi Phil,

It seems that the trimmomatic module can't load this trimmomatic output. Could you please find out what the problem might be?

This is the log file:
[arizonaTrimm.txt](https://github.com/ewels/MultiQC/files/276120/arizonaTrimm.txt)

I'm running multiqc with `multiqc arizonaTrimm.txt`.

The result is:
```
[INFO   ]         multiqc : This is MultiQC v0.7.dev0
[INFO   ]         multiqc : Searching 'arizonaTrimm.txt'
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Hi @pgonzale60,

This looks like a localisation error - your trimmomatic logs use the european style `,` instead of `.` for decimal points. I've come across this problem [previously](https://github.com/ewels/MultiQC/issues/123#issuecomment-196934417) and it's almost impossible to fix.

However, given that in this case the commas are in percentage values, I think it's fair to assume that they are never going to be thousand separators. So I'll update the code to handle both cases.

Phil

**Comment by ewels** [comment]
Code pushed - let me know if that works for you!

Cheers,

Phil

**Comment by pgonzale60** [comment]
Yes, it works great. Thanks!
