### ISSUE TITLE
Version 1.18 ignores ordering of an OrderedDict

### ISSUE THREAD

**Issue by rich7409** [ewels/MultiQC#2204]
### Description of bug

We have an internal plugin that creates a horizontal bar plot. The order of the rows is defined by how they are read from a file and we need that order preserved. Thus we've used OrderedDict for the plot data.

This has been working correctly for all versions up to and including 1.17 but the latest 1.18 disregards the order of the object and we end up with a plot ordered by the alphabetic keys.

I suspect a copy into another dictionary has been introduced between the two versions with natural ordering of the keys. I've not poked around in the source code but it appears the object we create is not the one that is used to render the chart's data.

If this is intended behaviour we will need to change our code (or stay on 1.17) but I'm raising this as it might be an unintended change.

### MultiQC Error log

```console
python3.9 -m multiqc -n zz_SINAA9.html --clarity https://limsdev.cruk.cam.ac.uk --force --no-data-dir --barcode-file testdata/clarityBarcodes.json -e bcl2fastq -e bclconvert --title 'SINA testing' --config /home/bowers01/work/pipelines/nf-sequencing/resources/multiqc_config.yaml testdata/231120_A00489_2045_BHNV7LDRX3

  /// MultiQC 🔍 | v1.18

|           multiqc | Report title: SINA testing
|           multiqc | Excluding modules 'bcl2fastq', 'bclconvert'
|           multiqc | Search path : /home/bowers01/work/multiqcplugins/multiqc_barcodebalance_plugin/testdata/231120_A00489_2045_BHNV7LDRX3
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/3  
|    barcodebalance | Using https://genomicsequencing.cruk.cam.ac.uk as the Clarity server.
|    barcodebalance | Found 2 demultiplexing stats files
|           multiqc | Report      : zz_SINAA9.html   (overwritten)
|           multiqc | Data        : None
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thank you @rich7409 for creating an issue. It sounds like an unintended behaviour, so sorry about it - I'll take a look into this asap.

I wonder if it's possible for you to attach the data you are using here (`testdata/clarityBarcodes.json`,
`/home/bowers01/work/pipelines/nf-sequencing/resources/multiqc_config.yaml`, and `testdata/231120_A00489_2045_BHNV7LDRX3`)?

**Comment by vladsavelyev** [comment]
Looked into this again, it looks like MultiQC normally sorts samples alphanumerically in tables and bar plots, both in modules and custom content, so it's an intended behaviour after all. I'm curious about the specific code you were using with `OrederedDict`s. Note that since Python 3.6, the standard `dict`s are guaranteed to be ordered, so it must be something else. Perhaps keeping the order was a side effect of something that we refactored recently. So I'm curious to look at your code, it would be really helpful to reproduce!

**Comment by vladsavelyev** [comment]
Oh, I see! So passing an `OrderedDict` was effectively the way to tell MultiQC to keep the order of input data. But actually it looks like it's an old artefact of the pre-python-3.6 code that didn't keep the order in regular dicts, so some sorting was nice to do, otherwise it would be randomly shuffled. But since the order is now always preserved for regular dicts, that sorting is not necessary anymore, so I'm going to remove it.

Thank you so much for the details, that's really helpful!

**Comment by vladsavelyev** [comment]
I created a pull request that fixes this issue: https://github.com/ewels/MultiQC/pull/2210

**Comment by ewels** [comment]
Hi @rich7409 - the previous behaviour should now be restored.

Note that the recommended method is now to not use `OrderedDict` in your custom module, but instead set the new bar plot config option `sort_samples` to `false`.

Thanks for reporting this!

**Comment by rich7409** [comment]
Right you are. I'll remove references to it when I'm next in the code.
