### ISSUE TITLE
Enable exclusion of General Stats from report with --exclude

### ISSUE THREAD

**Issue by stephenturner** [ewels/MultiQC#227]
Not a bug, probably user error/misunderstanding. I'm running fastqc, STAR, and featureCounts on a handful of RNA-seq samples (DKOs, KOs, and WTs). In the general stats section at the top of the report, it's pretty clear that each set of four rows corresponds to sample DKO1, second four are DKO2. It would be great if these were consolidated, or at least if the star and featurecounts lines were. I'm guessing it's something to do with the naming conventions? 

If these can't be consolidated, I would alternatively like to turn off the general statistics section, since this could be confusing as the first thing a collaborator would see. Tried looking into using `--exclude` for this, but there doesn't seem to be a way to turn that top section off. 

Here's what my top section looks like:

![image](https://cloud.githubusercontent.com/assets/460076/15703585/1540001e-27b4-11e6-8acf-1d936fb2e94a.png)

```

Sample Name	% Assigned	M Assigned	% Aligned	M Aligned	% Dups	% GC	Length	M Seqs
DKO-1.star.			87.2%	34.3				
DKO-1.star.Aligned.sortedByCoord.headfix	71.7%	32.2						
DKO-1_R1					70.6%	50%	76	39.4
DKO-1_R2					47.1%	50%	75	39.4
DKO-2.star.			86.6%	36.1				
DKO-2.star.Aligned.sortedByCoord.headfix	70.4%	33.8						
DKO-2_R1					72.4%	50%	75	41.7
DKO-2_R2					47.8%	50%	75	41.7
DKO-3.star.			87.3%	33.9				
DKO-3.star.Aligned.sortedByCoord.headfix	72.6%	31.8						
DKO-3_R1					70.7%	50%	76	38.8
DKO-3_R2					47.5%	50%	75	38.8
DKO-4.star.			87.8%	29.0				
DKO-4.star.Aligned.sortedByCoord.headfix	72.9%	27.3						
DKO-4_R1					68.3%	50%	76	33.1
DKO-4_R2					46.9%	50%	75	33.1
KO-1.star.			85.8%	37.6				
KO-1.star.Aligned.sortedByCoord.headfix	70.3%	35.4						
KO-1_R1					73.9%	50%	75	43.9
KO-1_R2					49.5%	50%	75	43.9
KO-2.star.			83.4%	27.3				
KO-2.star.Aligned.sortedByCoord.headfix	71.4%	25.6						
KO-2_R1					68.6%	50%	75	32.8
KO-2_R2					45.1%	51%	75	32.8
KO-3.star.			86.7%	40.0				
KO-3.star.Aligned.sortedByCoord.headfix	71.9%	37.5						
KO-3_R1					71.5%	50%	75	46.1
KO-3_R2					46.6%	50%	75	46.1
KO-4.star.			87.5%	43.4				
KO-4.star.Aligned.sortedByCoord.headfix	72.9%	40.8						
KO-4_R1					70.9%	50%	75	49.7
KO-4_R2					47.0%	50%	75	49.7
WT-1.star.			86.2%	38.3				
WT-1.star.Aligned.sortedByCoord.headfix	70.2%	35.9						
WT-1_R1					71.9%	50%	75	44.4
WT-1_R2					48.9%	50%	75	44.4
WT-2.star.			85.6%	34.8				
WT-2.star.Aligned.sortedByCoord.headfix	69.8%	32.4						
WT-2_R1					70.7%	50%	75	40.6
WT-2_R2					46.8%	50%	75	40.6
WT-3.star.			86.5%	22.4				
WT-3.star.Aligned.sortedByCoord.headfix	71.6%	20.9						
WT-3_R1					66.0%	50%	75	25.9
WT-3_R2					46.6%	50%	75	25.9
WT-4.star.			86.9%	34.6				
WT-4.star.Aligned.sortedByCoord.headfix	71.9%	32.5						
WT-4_R1					70.6%	50%	75	39.8
WT-4_R2					48.2%	50%	75	39.8
```

**Comment by ewels** [comment]
Hi @stephenturner,

Yup, this is a known phenomenon and is probably the toughest part of MultiQC. What the program tries to do is take the input filename for each log, and then "clean" it by trimming back suffixes. The hope is that this will result in a basename which is consistent across steps, resulting in continuous rows across the General Statistics table.

You can customise how this trimming works (see the [docs](http://multiqc.info/docs/#sample-name-cleaning)) - in your case you'd need to add `.Aligned.sortedByCoord.headfix` and `.star.`. I might add `.Aligned` as a default for v0.7 as I've seen this one myself a few times now.

Note that even with these additions, you'll still end up with three rows per sample. This is because the FastQC results are on a per-read basis, whilst the other results are per-sample. You can add `_R1` and `_R2` to the sample name cleaning if you want, but then the FastQC results from read 2 will overwrite read 1. You could exclude `_R2` reports using `--ignore *_R2.fastq.gz.fastqc.*` (or similar) on the command line but this is getting a bit convoluted.

Making it possible to exclude `General Statistics` in the same way as excluding other modules is a good idea though, I'll do that for the next version.

Phil

**Comment by ewels** [comment]
ps. Worth noting - when you run MultiQC with a lot of samples, the table is replaced with a beeswarm plot which looks something like this:

![beeswarm](https://cloud.githubusercontent.com/assets/7303848/14835325/0e237f84-0bbe-11e6-9cd6-f2b406445aea.png)

This representation doesn't require identical names (though it helps for mouse overlay highlighting). You can tweak the config option [`genstats_beeswarm_numseries`](https://github.com/ewels/MultiQC/blob/master/multiqc_config_example.yaml#L77) to always have this representation if you prefer it.

Any other suggestions for how to approach this problem welcome!

**Comment by ewels** [comment]
(apologies, originally quoted outdated config option name - amended above comment).

**Comment by ewels** [comment]
Ok, `--exclude general_stats` should now work in the development version! Let me know if you run into any problems with it..
