### ISSUE TITLE
Write documentation about flat / interactive plots

### ISSUE THREAD

**Issue by bmreilly** [ewels/MultiQC#231]
When I run MultiQC on larger numbers of fastQC files the report generated produces flat images, as opposed to interactive images.   

I saw that you may have added this feature (issue 101/102) to help reduce report size for single cell experiments.  

Is there a way to make the reports interactive again for larger sample numbers?   This would be quite helpful because if I see that 1 or 2 out of 200 files has bad quality, it would be nice to know which file that was without digging through the 198 high quality files (which is kind of the point of why I'm using MultiQC).

**Comment by ewels** [comment]
Hi @bmreilly,

Apologies - I just went to the documentation to find the correct link to send to you and it looks like I never got to writing anything about this.

There are two ways to change this behaviour - firstly you can force plots to be either flat or interactive for a single run by using the `--flat` and `--interactive` command line options.

Secondly, you can change the threshold at which this swap happens with the `plots_flat_numseries` config option. The default is 100 as you say, so you could change this to be 200 by adding the following line to `~/.multiqc_config.yaml`:
```yaml
plots_flat_numseries: 200
```
(see the [example config file](https://github.com/ewels/MultiQC/blob/master/multiqc_config_example.yaml#L75) for more of these).

I'm a bit conflicted about where to set the default for this - I'd like to set it higher, as you say, the interactive plots are quite a bit more useful. However, getting reports which are tens or hundreds of Mb in size because of the embedded plot data is not helpful, not to mention the problem of crashing people's browsers. It's tough to know exactly where to draw the line for this.

What I will definitely do is improve the docs on this topic though.

Phil

**Comment by bmreilly** [comment]
Hi @ewels,

Thank you for the explanation, and for updating the documentation!  

Personally I don't mind where you set the default file limit, as long as there are options like `--flat`, `--interactive`, and `plots_flat_numseries`.   I agree that it is not helpful to generate huge files that will crash people's browsers, so perhaps setting a relatively low default limit like you have (100) is best.  Users will still be able to produce the interactive plots for larger file numbers if they have the capacity to use those reports.

Thanks again,
Brian

**Comment by ewels** [comment]
Hi @bmreilly,

Thanks for the feedback! Glad you agree. I updated the docs, this behaviour (and other similar behaviours) are now described here:

http://multiqc.info/docs/#plots
http://multiqc.info/docs/#large-sample-numbers

Let me know if you think I've missed anything!

Phil
