### ISSUE TITLE
Samtools stats wrongly visualising read fractions

### ISSUE THREAD

**Issue by jrderuiter** [ewels/MultiQC#242]
The current samtools stats plot is misleading, as reads/mate-pairs are represented multiple times in the stacked bargraph. For example, in the plot below if have a bam file with approx. 48 million reads, of which the majority is mapped (47,8 million). However, because reads can be in multiple categories, the percentage (and thus the plotted bars) are estimated wrongly at 24.5% instead of ~99%. This is also why the graph counts up to nearly 200 million reads instead of 47.8 million.

Is this intentional behaviour? Isn't there a more appropriate way to plot this data so that it reflects what we expect? Or should I simply adjust the plot by removing overlapping categories if this is what I'm interested in?

![screen shot 2016-06-24 at 22 56 37](https://cloud.githubusercontent.com/assets/307739/16350761/07607c5c-3a61-11e6-8a7a-f70e3d1a232a.png)

**Comment by ewels** [comment]
Hi @jrderuiter,

That definitely sounds like a bug. I'll look into it asap, thanks for reporting..

Phil

**Comment by ewels** [comment]
Hi @jrderuiter,

I just took a look at the code for samtools and I realised that I've rewritten that plot (and most of the module) since the v0.6 release. It now uses a beeswarm plot instead:

![image](https://cloud.githubusercontent.com/assets/465550/16408739/67f84b7e-3d1a-11e6-9778-0e9761eb020b.png)

Hopefully this is less misleading. I'll close this issue for now, but feel free to reopen if you think that the above could be improved.

Phil

**Comment by ewels** [comment]
ps. This code is available now in v0.7dev, version 0.7 release will hopefully be going out pretty soon.
