### ISSUE TITLE
Error with empty FastQC reports

### ISSUE THREAD

**Issue by raivokolde** [ewels/MultiQC#254]
When directory contained FastQC files that were based on non-existing fastq files, then I got an error (shown below) and final report did not contain any Fastqc information. 

```python
 Module fastqc raised an exception: Traceback (most recent call last): 
  File "~/MultiQC/multiqc/lib/python2.7/site-packages/multiqc-0.7.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 296, in multiqc 
  report.modules_output.append(mod()) 
  File "~/MultiQC/multiqc/lib/python2.7/site-packages/multiqc-0.7.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 54, in __init__ 
  except (zipfile.BadZipfile, BadZipfile) as e: 
  NameError: global name 'BadZipfile' is not defined
```

**Comment by ewels** [comment]
Thanks for reporting this bug - it's actually due to a change that I made to fix an almost identical bug reported by someone else. It fixed it for them but broke it for everyone else it would seem 😄 

This is actually already fixed in 17a2bab5a9695efd39f3883e7136ba552f7cf1cc - sadly just after the v0.7 release. I also added a new test file into ewels/MultiQC_TestData@fc7da5b57c766929a7ccaefd7450057b439fa702 to keep on top of this in the future.

Finally, I'll put a ticket in with the FastQC author to ask for FastQC to not create empty zip files in the first place..

Phil
