### ISSUE TITLE
MultiQC does not see the TrimGalore report - requesting new module

### ISSUE THREAD

**Issue by mgavery** [ewels/MultiQC#260]
## If you're requesting a new module
Checklist of requirements:
- [ ] Description of tool, link to homepage
  TrimGalore (http://www.bioinformatics.babraham.ac.uk/projects/trim_galore/)
- [ ] Log files - please submit as a PR to https://github.com/ewels/MultiQC_TestData
[89_S1_L001_R1_001.fastq_trimming_report.txt](https://github.com/ewels/MultiQC/files/352726/89_S1_L001_R1_001.fastq_trimming_report.txt)

- [ ] Any standard log file naming patterns to get sample name (eg. `sample_name.processed.log`)
- [ ] Say which value is most important, to go into the General Stats table
The last 5 lines of the report contain the most important information
- [ ] Specify what should be plotted, if anything

Thanks!

**Comment by mgavery** [comment]
Just want to follow up that I ran multiqc on files created from a very similar pipeline on a different computer and it recognized the TrimGalore reports as Cutadapt just fine.  Maybe it's a version thing with what's on my computer. Anywho, my issue has been solved.  Thanks.

**Comment by ewels** [comment]
Hi @mgavery,

You beat me to it - MultiQC already supports TrimGalore because it supports cutadapt. In fact, the [test data](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/trim_galore) for the module uses output from TrimGalore.

I'll close this issue now, but if you have a log file that you think should be understood by MultiQC which isn't recognised, I'd be interested!

Cheers,

Phil
