### ISSUE TITLE
FastQC KeyError for zip file

### ISSUE THREAD

**Issue by woook** [ewels/MultiQC#279]
## If you're reporting a bug..
Please paste the full log message that you get in a code block. If possible, please attach an example file which triggers the problem.
```python
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/home/w/anaconda2/envs/conda_multiqc/lib/python2.7/site-packages/multiqc-0.8.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 304, in multiqc
    report.modules_output.append(mod())
  File "/home/w/anaconda2/envs/conda_multiqc/lib/python2.7/site-packages/multiqc-0.8.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 44, in __init__
    for f in self.find_log_files(config.sp['fastqc']['zip'], filecontents=False):
KeyError: 'zip'
============================================================

```

**Comment by ewels** [comment]
Hi @woook,

Thanks for reporting this - it sounds like a strange error, caused because MultiQC can't find the search parameter stored by default [here](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L35).

Are you customising file search parameters in any way? How do you have MultiQC installed?

Phil

**Comment by woook** [comment]
Hi @ewels  - thanks for the reply. I think this is due to that way I'm using fastqc (the implementation on DNAnexus), as there is no fastqc.zip file generated, only the fastqc_data.txt. I had assumed that the zip file was optional not required?

**Comment by ewels** [comment]
Hi @woook,

I just checked and MultiQC should work with just a single `fastqc_data.txt` file. I updated the [test data repo](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/fastqc/fastqc_data.txt) with one such file to be sure. MultiQC can use `.zip` files as well, but that's an alternative and not required.

The bug is from MultiQC not being able to find the search pattern anyway, before it does any searching. That is strange and suggests that there is something wrong with how the config is being loaded.

Phil

**Comment by ewels** [comment]
Hi @woook,

I'm going to close this issue for now as I can't replicate the problem. Feel free to reopen it if you'd like.

Phil

**Comment by woook** [comment]
For reference, I figured out the issue:

In my multiqc_config.yaml, I am specifying the search pattern for fastqc. However, I only specified the fastqc data search pattern and didn't specify as search pattern for fastqc zip. Once I included that the error went away.

So, this errors:
```
fastqc:
    data:
        fn: '*.stats-fastqc.txt'
```
and this runs without errors:
```
fastqc:
    data:
        fn: '*.stats-fastqc.txt'
    zip:
        fn: '*_fastqc.zip'
```
