### ISSUE TITLE
New --export option

### ISSUE THREAD

**Issue by VGalata** [ewels/MultiQC#280]
It would be great if the user could specify the output format for the plots (`.png`, `.svg` etc.). Otherwise, one is forced to use the interactive `html` view to export the plots which is quite slow when having many samples.

Furthermore, that would be a more intuitive way to plot the results for large datasets without the need for changing the settings in the `config` file (forcing `multiqc` to create interactive plots to be able to use the "Export" function in `html` view).

**Comment by ewels** [comment]
Hi @VGalata,

MultiQC already half-does some of what you suggest - if you use the `--flat` command line option, it forces MultiQC to use static images in the report. This was written to try to prevent reports from opening slowly when you have lots of samples. This also happens if you run MultiQC with > `config.plots_flat_numseries` samples (I guess you've found this already based on the issue title).

When these "flat" plots are created, they are additionally saved to `multiqc_data/multiqc_plots` as `.png` files. This is not advertised / documented very much though, so you sort of have to know it exists.

I have previously considered adding in functionality to always generate the static image plots, even for normal reports with dynamic plots. The main down-side for this is that it will slow the execution time of MultiQC. However, I could add an `--export` option to enable the feature (+ a config default) to solve this problem. I could also use these to specify output formats (probably `.png`, `.svg` and `.pdf`).

Note that not all plot types have the necessary code to generate static images on the command line yet (see #204, but some other plot types too). But this is something that I intend to add at some point anyway.

Is this be the kind of functionality that you would like?

Phil

**Comment by VGalata** [comment]
Dear @ewels,

> However, I could add an `--export` option to enable the feature (+ a config default) to solve this problem. I could also use these to specify output formats (probably `.png`, `.svg` and `.pdf`). [...]
> Is this be the kind of functionality that you would like?

Yes, this is exactly what I meant. :) Otherwise, I have to create the interactive plots though I only need the "flat" ones. And opening the `.html` and using the export function works slowly for large datasets.

Thank you!

Regards,
Valentina

**Comment by ewels** [comment]
Ok great, I'll put this together. Thanks for requesting it - it has been an idea in the back of my mind for a while now but low enough priority that I'd never got around to doing it ;)

Phil

**Comment by ewels** [comment]
Hi @VGalata,

I've just written in support for this new feature. Only barcharts and line plots currently have the MatPlotLib code required to generate the static plots so only these will be generated for now. I'll get onto writing the code for [heatmaps](https://github.com/ewels/MultiQC/issues/204), [scatter plots](https://github.com/ewels/MultiQC/issues/281) and [beeswarm dot plots](https://github.com/ewels/MultiQC/issues/282) soon though hopefully.

I've written a little documentation about the new features here: http://multiqc.info/docs/#exporting-plots

Let me know how you get on with this and if you find any bugs!

Phil

**Comment by VGalata** [comment]
Hi @ewels,

I just tried the export feature and it works great! Thank you very much!

Valentina
