### ISSUE TITLE
Module request for samstat

### ISSUE THREAD

**Issue by astewart-twist** [ewels/MultiQC#309]
More a suggestion than a request:  samstat (http://samstat.sourceforge.net/) might make a nice module.  It generates an html file which could probably be directly incorporated into the MultiQC report.

**Comment by ewels** [comment]
Interesting - thanks for the suggestion, it looks nice! I've not heard of it before.

I'm not keen on using HTML generated by another tool directly in MultiQC (has potential to break a lot of stuff), but if samstat outputs its data in another format I could certainly write a module to parse and display the same data.

Do you have any example output that you could send? Preferably the full output - HTML and any other files that are generated.

Cheers,

Phil

**Comment by astewart-twist** [comment]
I believe it only outputs the HTML.

Here's an example using https://github.com/samtools/samtools/blob/develop/examples/toy.sam as the input. 

[toy.sam.samstat.html.zip](https://github.com/ewels/MultiQC/files/501328/toy.sam.samstat.html.zip)

**Comment by ewels** [comment]
Thanks for the example @astewart-twist, it looks like a nice report!

However, if I'm honest, I have doubts about this one. The reports from SAMStat are nice, but they effectively split each sample into six for each plot. This makes it difficult to visualise for multiple samples. If I collapse the six categories into one, two of the three plots end up being the same as those generated from FastQC. Add onto this that there is no textual output from the tool so I have to parse HTML (a famously nasty task) and I'm not sure that it's worth the trouble.

You're welcome to convince me otherwise! Is there anything I'm missing here?

Phil

**Comment by ewels** [comment]
NB: The top plot is showing the data requested in #314. If this is of general interest I could look into parsing this from FastQC logs as part of that module.
