### ISSUE TITLE
Table with percentage of reads with mean quality scores equal or above 10, 20, 30 and 40

### ISSUE THREAD

**Issue by marisa-cunha** [ewels/MultiQC#314]
Hi,

I would like to make a suggestion. It would be great to have a table that uses the data from the file “Per_sequence_quality_scores.tsv” to answer the following question:
what is the percentage of Sample A reads with mean quality scores equal or above 10, 20, 30 and 40?

Example:
![samplea_q10_q20_q30_q40](https://cloud.githubusercontent.com/assets/18395573/19317355/abbb2658-909c-11e6-8cb0-af82b9e937e5.PNG)

Thanks,
Marisa

**Comment by ewels** [comment]
Hi @marisa-cunha,

Thanks for your suggestion - any reason why you need this in tabular format rather than using the plot that shows this data? 

Based on the name _Per sequence quality scores_ I'm guessing that this is to do with FastQC, but I can't find any file called `Per_sequence_quality_scores.tsv` with this data. Can you confirm what tool / command produces this file?

Phil

**Comment by ewels** [comment]
Closing this due to lack of feedback. Feel free to comment and I'll reopen!

Phil
