### ISSUE TITLE
minor updates to Samtools idxstats plots

### ISSUE THREAD

**Issue by cstubben** [ewels/MultiQC#323]
I have a few suggestions for samtools idxstats.  For the mapped reads per contig plot, can you
1.  order the chromosome names   1,2,3,4, .. MT, X,Y  instead of 1, 10,11, 12, 13, ...
2.  round the number of digits in the mouse over - I see 20 digits when you need 2 or 3 at most.
3. In the counts tab, maybe add commas instead of spaces as thousand separators.

Thanks for the great tool!

**Comment by ewels** [comment]
Thanks @cstubben, some good suggestions!

1. The module takes the order of the input file, I'm not sure if I want to change this behaviour, some species have weird chromosome names and specific orders. Sorting your log file should fix it.
2. Easy change and standard config option, sorry I missed it here
3. You mean on the Y axis? This is a HighCharts default, though it can be changed through internationalisation I think. I'm not keen to change it to be honest, I prefer to leave commas / dots out where I can because of confusion in Europe about how decimal places should be represented. Hopefully a space is universally understandable, if not the first choice for everyone.
4. _Picking up old MultiQC data as reported in #308_
  * This is due to the fact that the output file has basically no way to be recognises, so relies on a ridiculously flexible filename pattern ([`*idxstats*`](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L122)).
  * I think the best way to tackle this is to add `multiqc_data` to the default [`fn_ignore_dirs` config variable](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/config_defaults.yaml#L45). 
  * Maybe also I can change the parsed output filename by adding a hyphen or something.

**Comment by cstubben** [comment]
Thanks, I will look into sorting the idxstats log file.  And for #3  the idxstats - ChrXY mapped reads plot has commas as the separator and idxstats - Mapped reads per contig [counts] has spaces.

**Comment by ewels** [comment]
Hi @cstubben,

Minor update - I just refactored the tooltip code for bar plots, so the ChrXY tooltip now has the same number formatting as everything else (spaces). I've also added two new config options - `decimalPoint_format` and `thousandsSep_format`, so you can customise how these numbers look to your liking. For instance, `thousandsSep_format: ','` to get commas for thousands separators.

Note that these config options don't affect all numbers in the report (yet). Feel free to submit issues if you find numbers elsewhere that you think should use the same formatting and I'll add it in.

Phil
