### ISSUE TITLE
Give warning when trying to export beeswarm plots from report

### ISSUE THREAD

**Issue by mahermassoud** [ewels/MultiQC#339]
When I attempt to export a plot, clicking the "download plots" button does nothing. It does however export data just fine.

I have a plot of samtools flagstat data

**Comment by ewels** [comment]
Hi @mahermassoud,

You're completely correct - it does do nothing, sorry! The beeswarm plot type is relatively new, and I had to write it myself because there is no default HighCharts plot type for it. As a result, it's actually not a single plot, but rather several scatter plots stuck together. As such, it's not possible to export it as an image (easily at least, would require quite a lot of code).

I intend to write the required code to generate flat image plots of this plot type at run time (see #282), but I haven't done that yet. When it is written, it should be possible to get plots by running MultiQC with `--flat` or `--export`.

In the mean time, I will add an error message when the export button is clicked so that it doesn't fail silently. Thanks for the report!

Phil
