### ISSUE TITLE
Median quality score - FASTQC report

### ISSUE THREAD

**Issue by annaquaglieri16** [ewels/MultiQC#349]
Hi, 

I love your work! I am wondering if in the Sequence Quality Histograms from the FASTQC reports it would be possible to include also the median quality score per base. I tend to prefer looking at the median as well as it is suggested in the manuals. It would be good to have the option for it. 

Thanks for this, 
Anna

**Comment by ewels** [comment]
Hi @annaquaglieri16,

Great that you like MultiQC! I actually started off using the median values for the sequence quality plot when I first wrote the module. However, I found that because the median values are typically integers, with lots of samples the different lines become indistinguishable which effectively breaks sample highlighting and general fast visualisation. For this reason I switched to the mean value - in my experience this usually has a pretty similar value but is a float number and gives shows differences better than the median.

I could add this in as an optional second plot, but if I'm honest I'm not sure how much value it would add - can you give me an example where mean values would miss something that you'd be able to see from the median?

Phil

**Comment by annaquaglieri16** [comment]
Hi Phil, I see your point. As a summary statistics I just normally tend to prefer looking at the median especially if I am expecting to see skewness, which is often the case in these plots. It is also true that most times, at the end of the reads, the boxplots tend to show skewness towards lower values and the worsts that can happen is that you think your data are worse that they actually are. But also I assume that you colour the lines 'red' when the median value is below 20, which will give an idea about the distribution anyway.  Therefore, as you said, the median won't add too much. 

I have one more suggestion that you may or may not consider. I have few samples to process together and in some cases I would like to only show the lines for some of them. For example, when I look at the distribution of the fragment sizes, lines are often overlapping. It would be good if we could decide to remove some samples from some plots.

Thanks for your answer anyway!

Best wishes,
Anna

**Comment by ewels** [comment]
Absolutely - reports have a toolbox where you can hide samples, see [the docs](http://multiqc.info/docs/#hiding-samples). You can also highlight different samples in different colours. Note that if your report has very many samples and flat-image plots, these tools won't work.

Is this the functionality that you're looking for?

Phil

**Comment by annaquaglieri16** [comment]
Hi Phil! 
Sorry for the delay in my reply, that was exactly what I was I was looking for!

Thanks again ,
Anna

**Comment by ewels** [comment]
Great, glad to hear it :)
