### ISSUE TITLE
Glitch in the interplay of renaming / highlight samples

### ISSUE THREAD

**Issue by kevinrue** [ewels/MultiQC#354]
Hi,

I can rename samples: check.
I can save and reload setting profiles: check
However, when I first rename samples, then reload a setting profile to highlight them (based on their new name), I am fairly sure it highlights the right one, but all sample names are reverted to the initial value (before renaming).

The expected behaviour would be to keep the new names after highlighting.

All the best!
Kevin

**Comment by ewels** [comment]
Hi @kevinrue,

Thanks for reporting this - I just had a look at the code and changed a few things. I think it was mostly down to the order in which the loaded config settings were applied (highlight then rename, instead of the other way around) and also a bug in the load config for renaming.

Anyway, _should_ be fixed now in v0.9dev. Let me know if you spot any other strange behaviour.

Phil
