### ISSUE TITLE
Module: Peddy

### ISSUE THREAD

**Issue by leipzig** [ewels/MultiQC#355]
New module request: Peddy - Pedigree/Sex QC for VCF files
https://github.com/brentp/peddy

Standard log file naming patterns:
* `.het_check.csv`
* `.ped_check.csv `
* `.sex_check.csv`

**General Stats Table**
From this table, the last 7 columns are from Peddy, and last 3 columns are very important:
![screenshot 2016-12-05 14 42 02](https://cloud.githubusercontent.com/assets/147991/20899596/0bc48946-baf9-11e6-82a6-c9dc72cd204f.png)

**Plotting**
![screenshot 2016-12-05 14 39 40](https://cloud.githubusercontent.com/assets/147991/20899506/b5336af2-baf8-11e6-8a06-16732d14f3fe.png)

Peddy plots the PCAs against a background of g1k - not sure how you would implement this in MultiQC
![screenshot 2016-12-05 12 26 39](https://cloud.githubusercontent.com/assets/147991/20895245/9ecaf90e-bae6-11e6-885d-58e4d84e9004.png)

**Comment by ewels** [comment]
Thanks @leipzig - I've edited your issue a little so that it's easier for me to read, hope that's ok..

Extra links for myself:
* Documentation site: http://peddy.readthedocs.io/en/latest/
* CSV output description: http://peddy.readthedocs.io/en/latest/output.html#output
* Example HTML report: http://peddy.readthedocs.io/en/latest/_static/ceph.html

The General Stats information should be fine.

The plots completely depend on what data is available from Peddy. If we can get the XY co-ordinates from somewhere then I think that the scatter plots that have one point per sample should be no problem (rate of HET calls / depth & heterozygosity).

I can look into the PCA with background of the 1k genomes. It's more points than I like, but the background cloud is a fixed number so should scale ok. I quite like it, so I'll see what I can do. Again, this is conditional on getting the XY co-ordinates from peddy.

I can't find any example data on the docs or GitHub repo. @leipzig - do you have any data that I can use to write the module with?

Many thanks,

Phil

**Comment by leipzig** [comment]
Yes will get those PR'ed tomorrow morning. Peddy should be an easy one
since you can just reproduce the visualizations.

**Comment by ewels** [comment]
Hi @leipzig,

I've just started this module for you. I need some feedback though if that's ok...

* The general stats columns are fine, but I can't find `sex_error` in the example data you provided.
  * I'm taking the other data from the `.ped` file. I'm not sure that this is actually from Peddy? Maybe plink?
  * I've also added the Family ID, but this is hidden by default if all samples share the same id.
* The PCA plot is done, using `PC1` and `PC2` as specified in the `.ped` file
  * No 1000genomes background data, as this isn't available in the data

For the other plots, I'm not sure where the numbers come from. If you could point me to exactly what columns you would like to be plotted (and how, if any transformation is needed).

Apologies, I'm not at all familiar with this type of analysis, so you're going to have to lead me by the hand here :)

Example output here: [multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/657638/multiqc_report.html.zip)

Changes are committed so you should be able to pull the development version and have a go yourself.

Phil

**Comment by leipzig** [comment]
- `sex_error` is just called `error` in the `sex_check.csv` table
- the `.ped` file is indeed peddy output, no worries there
- yeah not sure what do with about 1kg - the coordinates are just not exported by peddy

**Comment by ewels** [comment]
Ok great, I'll add the `sex_error` column then. Did you want any other plots?

Phil

**Comment by ewels** [comment]
Hi @leipzig,

I can't resist a bit of a challenge, so I had a go at getting the thousand genomes data into the MultiQC report. I managed to reverse engineer the data from the example Peddy report and have included with MultiQC, so the PCA plot now has the background for context.

I hope this is ok - I'm making the somewhat crude assumption here that this background PCA data will be the same for every run - is this ok?

I've also added the `error` column from the `sex_check.csv` file.

Phil

**Comment by leipzig** [comment]
Yeah I'm not sure that is really static info but it's worth a shot. Another option is to ask brentp (or PR it) to just dump the actual 1KG coordinates from the peddy run into a file

**Comment by ewels** [comment]
Ok - thousand genomes data added and then removed again (hopefully coming with an update to Peddy - see above thread). I also added a copy of the relatedness plot.

I need to push a release of MultiQC so I'll close this issue for now. If there are any changes or improvements that you'd like to see, please open a new issue.

Thanks!

Phil
