### ISSUE TITLE
Automate deployment?

### ISSUE THREAD

**Issue by epruesse** [ewels/MultiQC#372]
https://docs.travis-ci.com/user/deployment/pypi/
https://docs.travis-ci.com/user/deployment

Travis supports mechanized release deployment. May be worth investigating (for easy fast releases). PyPi is supported "out of the box". Bioconda needs a script to create a PR. 

Another useful tool is `bumpversion`. Combined, pushing out a version can become as easy as:

```
bumpversion minor
git push --tags
```

The rest happens on its own.

**Comment by ewels** [comment]
Thanks for this - yes I'm aware of these tools (and use them on other projects). I haven't implemented them as I do a bunch of other stuff when I push MultiQC releases which can't be automated. The PyPI / bionconda deployments only add a small amount of time onto what it otherwise a fairly long process so I don't think it would help all that much.

One day I'll write up automation for the other parts of the release process (eg. generating new example reports for the website) and some of the other more boring stuff. If the automated testing is also more thorough by then, I might come back and do this. We'll see :)

**Comment by ewels** [comment]
ps. See my [release checklist](https://github.com/ewels/MultiQC/blob/master/.github/RELEASE_CHECKLIST.md) if you're curious. It includes stuff like posting on SeqAnswers and visually checking the PyPI release page. The `python setup.py sdist upload` command is one of the fastest bits.

**Comment by epruesse** [comment]
Sure, I just wanted to mention them since you said it'd taken you too long between 0.8 and 0.9 on bioconda-recipes. I've used the process mostly for patch-level releases. A lot of what's on your checklist could be mechanized, but it's worth it only if you want to do frequent micro releases. And, of course, it would really need more rigorous automated tests. Theoretically ones that actually run the tools the modules need so that you can see whether their output formats have changed (lot's of moving targets for aggregators like MultiQC unfortunately).
