### ISSUE TITLE
feature request - A barplot showing the proportion of bp/reads passing each step of a Methyl NGS pipeline from:

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#38]
A barplot showing the proportion of bp/reads passing each step of a Methyl NGS pipeline from:

1. Initial fastq.gz PF reads/bases
2. Qscore and adaptor filtering
3. Mapping
4. Deduplication
5. Clip Overlap
6. 5' or 3' trimming before methylation calling
7. Bases in CpG positions covered below 1x, above 1x, above 5x, above 30x

**Comment by ewels** [comment]
Hi @avilella!

Thanks for this - what programs generate the output for each of these steps? Do you have example log files for all of them?

Typically, the design of MultiQC is to have a single section / plot for each chunk of log file output (_eg._ from a single program). Then the "General Stats" table at the top is the centralised place for numbers across different modules.

Having said this, I can see the value of having a "meta-module" that plots numbers generated from a variety of programs. So maybe this can be a trial of that idea - a module that runs after everything else and creates a plot if certain data are found from previous modules. I can see that this could be useful in a number of cases, though I think that the core MultiQC code may need modifying a little so that a submodule can get at numbers generated elsewhere.

Are you planning to work on this at all, or is it a feature request? Either is fine! :smile: 

Phil

**Comment by avilella** [comment]
Feature request at the moment :-)

Many of these numbers come from bismark, then there is bam clipOverlap for
clipping stats.

Point number 7 comes from methylQA (https://github.com/lidaof/methylQA) in
bismark mode.

**Comment by ewels** [comment]
Ok great - well there is already a module for FastQC, cutadapt (Trim Galore!) and Bismark - so hopefully most of the numbers you'd like will already be there. I'm in the process of generating a BS-seq analysis example report with some public data now, will post the link when it's done so that you can see what a typical report looks like in my hands.

MethylQA is new to me, looks nice! If you can post an example output which has the information you'd like to display in it I can take a look at writing a module for it. Please list which values (lines) you'd like parsed, and also how to recognise the file (typical file naming, or included text).

Phil

**Comment by ewels** [comment]
Hi @avilella,

I'm going to close this issue for now as it doesn't describe a single module request or any individual features. If you'd like a new module for MethylQA and/or any others, please feel free to create a new issue for them.

Cheers,

Phil
