### ISSUE TITLE
Ignore hidden samples when exporting raw data from report

### ISSUE THREAD

**Issue by annaquaglieri16** [ewels/MultiQC#387]
Hi there, 

I am trying to export the .csv file relative to the GC content plot only for a subset of sample. The export function works fine if I want to export the actual plot but it downloads all the data instead. Is there a way to only download the samples I am interested in, say the ones with warnings?

Thanks for your assistance, 
Anna

**Comment by ewels** [comment]
Hi Anna,

I'm away at the moment so can't look into this for you right away (I'm back mid-Feb). But if it doesn't already honour renaming and hiding of samples then it probably should, this would be a good addition for the next release.

Thanks!

Phil

**Comment by ewels** [comment]
ps. In case you haven't already found it - FastQC plots have a little Pass / Warn / Fail bar next to the title. Clicking this allows you to easily show only failing samples (hiding all other samples across the whole report). If the export data function does already honour these settings, then this will be how to get it.

**Comment by annaquaglieri16** [comment]
Thanks for your answer Phil, 

I am using the Pass/Warn/Fail selection tool to plot only the samples with issues and I can easily export the subsetted plot. However, when I switch to download data instead of plot it downloads all the samples. Maybe it would be enough to add a factor column (pass-warning-fail) to the downloaded dataset to be able to quickly subset the dataset. 

Anna

**Comment by ewels** [comment]
Hi @annaquaglieri16,

I'm back from holiday now so will hopefully look into this soon. I think that the expected behaviour is (and should be) that exporting raw data from a report will only export visible samples. So anything hidden through the pass/warn/fail buttons or the more general Toolbox functions should be honoured. I'll update the code so that this is done in the next version.

Cheers,

Phil

**Comment by ewels** [comment]
Hi @annaquaglieri16,

Apologies that this took so long to do - it turned out to be quite a lot more difficult than I expected! I ended up basically rewriting all of the plot data exporting functionality. I think it's quite a bit better now and should work as expected :)

Let me know if it works for you or if you run into any problems..

Phil
