### ISSUE TITLE
htseq and slamdunk module issues when running MultiQC

### ISSUE THREAD

**Issue by Mlotshwa** [ewels/MultiQC#391]
```
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '/home/mlotshwa/RNA_Seq_TB_project/Run2'
[ERROR  ]         multiqc : Oops! The 'htseq' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module htseq raised an exception: Traceback (most recent call last):
  File "/home/mlotshwa/miniconda2/envs/snowflakes/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/home/mlotshwa/miniconda2/envs/snowflakes/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/htseq/htseq.py", line 31, in __init__
    parsed_data = self.parse_htseq_report(f)
  File "/home/mlotshwa/miniconda2/envs/snowflakes/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/htseq/htseq.py", line 62, in parse_htseq_report
    assigned_counts += int(s[1])
IndexError: list index out of range
============================================================
[INFO   ]        samtools : Found 1 rmdup reports
[ERROR  ]         multiqc : Oops! The 'slamdunk' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module slamdunk raised an exception: Traceback (most recent call last):
  File "/home/mlotshwa/miniconda2/envs/snowflakes/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/home/mlotshwa/miniconda2/envs/snowflakes/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/slamdunk/slamdunk.py", line 42, in __init__
    self.parseSummary(f)
  File "/home/mlotshwa/miniconda2/envs/snowflakes/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/slamdunk/slamdunk.py", line 295, in parseSummary
    self.slamdunk_data[s_name]['sequenced'] = int(fields[4])
IndexError: list index out of range
============================================================
[INFO   ]          fastqc : Found 112 reports
[WARNING]          fastqc : Multiple FastQC Theoretical GC Content files found, now using fastqc_theoretical_gc_hg38_genome.txt
[WARNING]          fastqc : Multiple FastQC Theoretical GC Content files found, now using fastqc_theoretical_gc_hg38_txome.txt
[WARNING]          fastqc : Multiple FastQC Theoretical GC Content files found, now using fastqc_theoretical_gc_mm10_txome.txt
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```
Please help me isolate the problem. Bioinformatics newbie so not sure how to proceed from here.
Thanks,
Busi

**Comment by Hammarn** [comment]
Hi Mlotshwa! 
Phil is on vacation, som I'm giving this a shot instead. 
I suspect that something's "wrong" or at least different with your input file. Can you share the file that caused the issue? I.e the htseq log file.
I laso noted that you are running the latest version of MultiQC from the master branch. This is a development version and possibly unstable. While you wait you could try installing MultiQC version 0.9 (which should be stable) through pip or conda;
http://multiqc.info/docs/#installing-multiqc

**Comment by Mlotshwa** [comment]
I have this version multiqc:
multiqc: 0.9.1a0-py27_0 bioconda
Removed and reinstalled via conda to confirm. Not sure where  find the htseq log file. I ran multiqc on a folder of fastqc results on my server.
Thanks

**Comment by Hammarn** [comment]
aha, so you are only trying to run on fastqc files? interesting! This is odd and @ewels will probably have to dig deeper into this when he is back (in about a month). 
For now I suggest that you run only the fastqc module e.g;
```
multiqc -m fastqc .
```

**Comment by Mlotshwa** [comment]
I tried to install the 1.0 version previously but it gave me an error during installation; not sure why it appears to be running now when 0.9 is installed via conda. How do I remove 1.0? I can't find an uninstall.py in the directory.

**Comment by ewels** [comment]
Hi both,

Sorry for my absence in this thread! I'm back now so should hopefully be able to help. @Hammarn - your confusion about the development version is because @chapmanb has been adding development versions of MultiQC to the bioconda channel, so the default version if installed through bioconda is the development version: https://github.com/bioconda/bioconda-recipes/commits/master/recipes/multiqc

@Mlotshwa - I'm not sure about how common having an `uninstall.py` file is? I've not come across that convention before. But you should be able to uninstall any conda package using `conda uninstall` - see the [main conda docs](https://conda.io/docs/commands/conda-uninstall.html).

Anyway, all of this version stuff is sort of beside the point - the error report points to code that shouldn't have been changed between the two versions, so it shouldn't make any difference.

I suspect that the first error is being triggered because the HTSeq stderr log file contains other stuff apart from HTSeq logs. This shouldn't be problem, I try to write MultiQC modules in such a way that they tolerate this. I'll try to replicate the error myself and fix it.

The second error, the slamdunk module, is more interesting. It's probably the same thing but I'm curious as to why it's picking up slamdunk files at all. That module looks for files containing the string `'# slamdunk summary'`, and as far as I was aware the slamdunk tool is currently unpublished and not really used by anyone. @Mlotshwa - are you using slamdunk? Do you know which file triggers this error?

Anyway, I'll look into making the code more tolerant fix both of this errors. @Mlotshwa - if you could send over some files that trigger the problem then that would save me some time, as the first step will be to try to replicate the bug at my end...

Many thanks both,

Phil

**Comment by jcamunas** [comment]
Hey just to let you know that I am finding a similar error message when MultiQC finds htseq output (bioconda distribution). I get exactly the same message both for python3 and python2 environments. I can send you example htseq output files if you need.  Error messsage below:

[ERROR  ]         multiqc : Oops! The 'htseq' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module htseq raised an exception: Traceback (most recent call last):
  File "/scratch/users/jcamunas/resources/anaconda3/envs/python2/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/scratch/users/jcamunas/resources/anaconda3/envs/python2/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/htseq/htseq.py", line 31, in __init__
    parsed_data = self.parse_htseq_report(f)
  File "/scratch/users/jcamunas/resources/anaconda3/envs/python2/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/htseq/htseq.py", line 62, in parse_htseq_report
    assigned_counts += int(s[1])
ValueError: invalid literal for int() with base 10: 'count '

**Comment by ewels** [comment]
Hi @jcamunas,

If you could please send over some logs that trigger the error then I'll take a look. Thanks!

Phil

**Comment by jcamunas** [comment]
Here a couple of output files from htseq.

[counts.zip](https://github.com/ewels/MultiQC/files/881252/counts.zip)

**Comment by ewels** [comment]
Great stuff, thanks @jcamunas! Looks like your files had an extra header line that I'd not seen in these files before. I've modified the code so that this doesn't cause MultiQC to crash. Let me know if you have any more problems.

Phil

**Comment by jcamunas** [comment]
Hi Phil,

I tried to update multiqc from conda distribution (python3) but i still get the same errors. Same with pip install. Will it take longer to upgrade in conda distribution, or am I doing something wrong? Thanks!!

**Comment by ewels** [comment]
Hi @jcamunas,

You need to install from GitHub directly - the changes won't make it to conda or PyPI (`pip`) until I push a release.

This should install the development version:

```bash
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

Phil
