### ISSUE TITLE
Dynamic plots are not displaying in Chrome

### ISSUE THREAD

**Issue by remiolsen** [ewels/MultiQC#396]
Recently (possibly after a Chrome update), the highcharts plots in MultiQC is not displaying. The browser console gives the following error:
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
The trace points to this [line](https://github.com/ewels/MultiQC/blob/cfa376084beeb0705026ecdd6c7802d7f06478d3/multiqc/templates/default/assets/js/multiqc.js#L28)

Now, I was able to 'fix' this by turning off the following option in Crome: `Settings > Advanced > Content settings (under Privacy) > Block third-party cookies and site data`. But I can swear I've always had this option turned on for a long while.

**Comment by ewels** [comment]
Hmm, that's annoying. Short term fix is to wrap that JS in a try / catch block so that it doesn't trip up the whole page (PRs welcome!). Longer term fix will require some reading though.

**Comment by ewels** [comment]
I haven't been able to find any easy solutions for getting `localStorage` to work with the `file://` protocol. I've updated the code to catch these errors so that the rest of the report javascript continues to work. It also replaces the _Save Config_ panel of the report toolbox with a longer message explaining what's gone wrong and how to change browser settings to fix it (configs are saved using localStorage).

Phil
