### ISSUE TITLE
Downloading raw data of per base sequence content plots

### ISSUE THREAD

**Issue by veronikaherzog** [ewels/MultiQC#398]
In the MultiQC HTML report with results from FastQC, attempting to export the _Per-Base Sequence Content_ plot results in the following error:

```
"Error: Couldn't export data from fastqc_seq."
```

Thanks!

**Comment by ewels** [comment]
Hi @veronikaherzog,

I re-wrote your issue a little so that I remember our discussion when I come to see it again. Hope this is ok!

Phil

**Comment by ewels** [comment]
Note to self - this isn't just the plot output, but also when exporting the raw data (I think).

**Comment by ewels** [comment]
To elaborate on this issue - the problem is that this plot is custom-built, rather than using HighCharts. The data structure is also difficult to export into a single text file (three dimensions - bases x length x samples). So, to export the data I need to write some custom javascript and also decide _how_ to represent the exported data. This isn't trivial. Suggestions for format welcome!

As a minimum, I guess I should probably put in a more helpful error message.

Phil
