### ISSUE TITLE
Implement number formatting for report tables

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#406]
Numbers in tables don't seem to have the same formatting as HighCharts (specifically, spaces between thousands in numbers). Should work with existing back end: `decimalPoint_format` and `thousandsSep_format`. See http://multiqc.info/docs/#number-formatting

**Comment by vladsaveliev** [comment]
Hi Phil,

Wanted to bring my 5 cents on number formatting. I usually use small spaces of 0.2em size, but instead of adding actual spaces, I put an extra margin to the characters. This way a user can copy a number from the report and insert it into a calculator or a spreadsheet without need to remove my separators. And it looks like this:

![image](https://cloud.githubusercontent.com/assets/1575412/23228470/ab0ffe6c-f94d-11e6-9c51-c94d7fac2c09.png)

The CSS for this looks as follows:
```
.hs {
  margin-left: 0.2em; }   /* 230<span class="hs"></span>000 */
```
And here is my JS to format a number (I don't separate 4-digit numbers as I think the readability issues start only with 5 digit-long numbers):
```
if (num > 9999) {
    str += num.toFixed(0).replace(/(\d)(?=(\d\d\d)+(?!\d))/g, '$1<span class=\'hs\'></span>');
} else {
    str += num.toFixed(0);
}
```
Just FYI, here is the full version of my `toPrettyString` function that also handle floats: https://github.com/vladsaveliev/NGS_Utils/blob/master/ngs_utils/reporting/static/scripts/utils.js#L70

Another trick is to align numbers to the right (or in a more general case of fractional numbers, by decimal point position). It makes the difference between numbers like 5522770 and 552277 in your example more clear. 

I used the same code to format number in QUAST reports, you can take a look at live examples: http://quast.bioinf.spbau.ru/static/icarus/s_aureus/report.html

I hope this ideas might be of some help!

**Comment by ewels** [comment]
Many thanks for the input @vladsaveliev - you've actually described exactly what I was planning to do for spaces 😁  Your JS implementation looks cleaner than [what I've done before](https://github.com/ewels/genomics-status/blob/master/run_dir/static/js/base.js#L225-L237) though, might emulate your approach there.

Earlier versions of MultiQC did have the numbers right-aligned as you say (I agree that it's easier to interpret), however I found that when the table columns were wide this made the numbers get quite far from the column header.  In your QUAST screenshot you have the numbers right aligned to each other, but left aligned as a whole to the column - how do you do this? When I follow your [link](http://quast.bioinf.spbau.ru/static/icarus/s_aureus/report.html) to the live report the numbers appear to be left-aligned for me:
![image](https://cloud.githubusercontent.com/assets/465550/23252934/e564d172-f9b2-11e6-81d0-269b6e7a6644.png)

Phil

**Comment by vladsaveliev** [comment]
Phil,

In my QUAST link, the numbers are not aligned because the table is transposed: rows correspond to metrics, and columns correspond to samples. So the numbers within one column are not comparable, thus there is no reason to align them to each other. 

I uploaded a live example of the first screenshot with aligned numbers: http://quast.bioinf.spbau.ru/static/targQC.html

To align, I loop through each column contents and pre-calculate the element widths, then determine the widest number and set the required shifts from the left border for the remaining numbers by setting them `margin-left`. So I don't set the actual `align: right`. The code for that is not as nice, and also written in CoffeeScript, sorry about that:
https://github.com/vladsaveliev/NGS_Utils/blob/db800c8fdf62229dff03b4b35c3c2216a625c5a1/ngs_utils/reporting/static/scripts/build_total_report.coffee#L127
I didn't have any noticeable performance issues with that, however there might be some in very large tables. I can take a look at this weekend and try it with MultiQC and evaluate the performance.

**Comment by ewels** [comment]
ok, nice! Glad to hear that there isn't some kind of CSS magic that I wasn't aware of :) Could it be quicker / less resource intensive to use a right-margin / padding instead of left? Then it would be a single value for all cells in the column (quicker browser rendering). You'd also only need the widest element, so could be fractionally quicker to compute..

It certainly is a nice effect anyway, though as you say performance is always an issue with MultiQC. I've been meaning to rewrite the [chroma.js](http://gka.github.io/chroma.js/) functionality that I use for colouring cells in tables in Python so that it runs at report generation time instead, to speed up rendering. I'm sure that there are quite a few other improvements I could make too. The MultiQC JS code is now very long and sprawling, and not particularly pretty to look at!

**Comment by vladsaveliev** [comment]
You are right that a right-align is a more clear solution. But because I
also used this code to align fractional numbers by decimal point, simple
right-align didn't work for me. The bottleneck seems to be the "width()"
jQuery call which is needed to be done for each cell anyway.

Pre-calculation is always better, and it should work for colors for sure! I
implemented my heatmaps in JS originally but later re-implemented in python.

**Comment by ewels** [comment]
Ok, number formatting now implemented (default is `.` for decimal and a gap for thousands (not a space when copied). These can be changed with the same config options used for plots.

@vladsaveliev - I had a play with aligning numbers on the decimal point. In the end I left it out, as I don't want to add any more javascript to tables if I can avoid it, as they can get very big. There's even a lot of CSS in them as it is. Hopefully the background bars give enough context for varying numbers of digits. I tried adding a `nbsp;` in the Python for missing digits, which sort of worked but not quite due to kerning. Monospace fonts would fix this but I think that they're harder to read. I may come back to this in the future though.. :)
