### ISSUE TITLE
Module request: vcftools

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#411]
Requested in #311 by @jcgrenier:

> One could think of some more high level QC. One that could use the output of relatedness, or relateness2 command from the newest version of vcftools that could be used to see if two RNASeq samples of different condition are the same individual or if they are from the same family. A simple triangular heatmap could do the job.

[http://vcftools.sourceforge.net/man_latest.html#OUTPUT OPTIONS](http://vcftools.sourceforge.net/man_latest.html#OUTPUT%20OPTIONS)

**Comment by ewels** [comment]
Missed a bit:
> A standard heatmap could be enough to plot the pairwise values coming from the vcftools analysis.

**Comment by jcgrenier** [comment]
Hi @ewels,

Thanks for coming back on this. I'm putting an example for each one of the programs actually. So one example which was done using VCFtools with the option relatedness2. The classic relatedness option is doing file of the same format.
[YP.QCheck.VQ30.GQ20.DP10.miss50.relatedness.relatedness2.txt](https://github.com/ewels/MultiQC/files/810747/YP.QCheck.VQ30.GQ20.DP10.miss50.relatedness.relatedness2.txt)

The second example is resulting from the --genome option from PLINK 1.9 (or 1.08p).
The column that interests us is the 10th one, which represents the PIHAT value, which is a combination of multiple other metrics. 

The last column could be used as well as a checkup for the samples (barplot). The ratio is supposed to be at 2. So if it's larger, the two samples are most probably related. The status you will see in the RT column will be super correlated in my example, since there's pedigree information in the hapmap dataset. Most of the time, if you are building your own, you won't have any information there. Furtheremore, the numbers look clean here since it's from a genotyping array. When you compare sequencing samples, the numbers will vary much more because of the missing data.

https://www.cog-genomics.org/plink2/ibd

[hapmap3_r2_b36_fwd.consensus.qc.poly.PIHAT.genome.txt.gz](https://github.com/ewels/MultiQC/files/810916/hapmap3_r2_b36_fwd.consensus.qc.poly.PIHAT.genome.txt.gz)


Note that I've added a ".txt" extension to the files so that I could put them in the post.
So normally, you should look for a ".relatedness2" for vcftools and a "genome" for PLINK.
Another thing that could be interesting is to only plot some barplots representing samples admixture. This value could be a QC to be sure that your sample is really coming from the good population you are studying or a result in itself. Having it plotted in the MultiQC could be pretty cool too!

Here, I'm putting an example of a test runned on some african populations.
To get this file, I'm taking the output of admixture software (the .Q file), for which in this case, I've asked for an estimation of 2 ancestral populations (K=2). The input was a .ped file coming from PLINK. The order of the samples in the Q file is the same as in the input file, so I've extracted the 2 first columns of the .ped file (one could take the .fam from the binary format too) that I've joined to the .Q file.

[Biku_Rura_Gabon_twa_kiga_HGDPafr_1perc_rec12_noXY_noRepIndiv_relTwa_pihat02.2.Q.withIDs.txt](https://github.com/ewels/MultiQC/files/810984/Biku_Rura_Gabon_twa_kiga_HGDPafr_1perc_rec12_noXY_noRepIndiv_relTwa_pihat02.2.Q.withIDs.txt)

 https://www.genetics.ucla.edu/software/admixture/

Thanks for your help! Those additions will probably help a ton those ones working in population genetics!

JC

**Comment by ewels** [comment]
@mwhamgenomics working on this..

**Comment by jcgrenier** [comment]
Hi @ewels and @mwhamgenomics , 
Awesome! I'm gonna test this really soon and come back to you!
Thanks for working on this incredible tool again!

JC

**Comment by mwhamgenomics** [comment]
Hi there!
The module's got relatedness2 for now but there's definitely more that can be done with all the other stuff vcftools can do, so I'll hopefully come back to this sometime soon. Also, anyone else interested in contributing would be welcome.

**Comment by ewels** [comment]
Speaking of which... #546 😉

**Comment by ewels** [comment]
Hi all,

I'm going to close this issue now as @mwhamgenomics and @ehsueh have added support for some of the VCFTools commands.

If anyone would like to see support for additional VCFTools output, please open a separate issue so that we can keep these bite-sized :)

Phil
