### ISSUE TITLE
custom content plot type 'table' not working

### ISSUE THREAD

**Issue by mohammedkhalfan** [ewels/MultiQC#414]
Love MultiQC! Big thanks to the authors! I am trying to include some general stats in our MultiQC reports, I'm trying to use custom content in the form of a csv or tsv. I would like it to be presented in table format. Taking one right from the docs/examples, it works if the plot_type is set to 'bargraph', as it is in the example, but if I change this to 'table', or 'generalstats', it complains about not being able to parse custom data, everything else being the same. Example of file contents and error log (2 examples):

File 1 (WORKS):
```
# title: 'Output from my script'
# description: 'This output is described in the file header. Any MultiQC installation will understand it without prior configuration.'
# section: 'Custom Data File'
# format: 'tsv'
# plot_type: 'bargraph'
# pconfig:
#    id: 'custom_bargraph_w_header'
#    ylab: 'Number of things'
Category_1    374
Category_2    229
Category_3    39
Category_4    253
```

LOG FROM MultiQC:
```
[INFO   ]         multiqc : This is MultiQC v0.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]  custom_content : .: Found 1 samples (bargraph)
[INFO   ]          fastqc : Found 12 reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

FIle 2 (changed 'bargraph' to 'table', NO LONGER WORKS):
```
# title: 'Output from my script'
# description: 'This output is described in the file header. Any MultiQC installation will understand it without prior configuration.'
# section: 'Custom Data File'
# format: 'tsv'
# plot_type: 'table'
# pconfig:
#    id: 'custom_bargraph_w_header'
#    ylab: 'Number of things'
Category_1    374
Category_2    229
Category_3    39
Category_4    253
```

LOG FROM MultiQC:
```
[INFO   ]         multiqc : This is MultiQC v0.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[WARNING]  custom_content : Not able to parse custom data in HK3FCAFXX_mqc.csv
[INFO   ]          fastqc : Found 12 reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

I tried taking out the pconfig lines, no luck. Tried removing all the header lines, it works as a bargraph. But I need it to display in table form! Please advise. Thank you very much!

**Comment by ewels** [comment]
Hi @mohammedkhalfan,

Many thanks for the detailed report - I'll have a look. The custom content module is pretty new and still needs a lot of testing, so finding out when it breaks like this is really helpful!

Phil

**Comment by ewels** [comment]
Ok, I've fixed a couple of bugs and it now works. However, it produces this, which is probably not what you were expecting:

![image](https://cloud.githubusercontent.com/assets/465550/23501597/c3c04cd6-ff34-11e6-9758-674b6ec92b2b.png)

That's because MultiQC expects tables to have a header row. So it takes the first line of the data and uses the second column as the table header (`374`). Adding in a header line gives the desired effect:
```
# plot_type: 'table'
Sample_Name   My_Number
Category_1    374
Category_2    229
Category_3    39
Category_4    253
```
![image](https://cloud.githubusercontent.com/assets/465550/23501664/08194ca2-ff35-11e6-9ca8-27531f55fdec.png)

I realise that the documentation for all of this is fairly non-existent. Apologies for this, I'll try to get some more written soon.

Phil

**Comment by mohammedkhalfan** [comment]
Hi,

Thanks for your quick reply! I tried with the latest code and am having the same problem, but a different error now (in addition to the original):

```
[INFO   ]         multiqc : This is MultiQC v0.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[WARNING]  custom_content : Not able to parse custom data in HK3FCAFXX_demux_report_mqc.tsv
[INFO   ]          fastqc : Found 4 reports
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
Traceback (most recent call last):
  File "../MultiQC/build/scripts-3.4/multiqc", line 581, in <module>
    multiqc()
  File "/opt/local/tubo/env/python3/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/local/tubo/env/python3/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/local/tubo/env/python3/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/local/tubo/env/python3/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "../MultiQC/build/scripts-3.4/multiqc", line 570, in multiqc
    log.move_tmp_log(logger)
AttributeError: 'module' object has no attribute 'move_tmp_log'
```
Here is my input file:

```
# title: 'Run Summary Title'
# id: 'run_summary'
# section_name: 'Run Summary'
# format: 'tsv'
# plot_type: 'table'
Sample_Name   My_Number
Category_1    374
Category_2    229
Category_3    39
Category_4    253
```

One note: I can get it to work with json data. The problem is that the columns of the table don't appear in a consistent order. Same input file, but multiqc output can be different (different order of columns). I guess this is a json thing.

**Comment by ewels** [comment]
Hi @mohammedkhalfan,

It looks like you're still running the v0.9 release of MultiQC - to use my recent changes you need to grab a copy of the latest development version (v0.1dev). You can do that with the following command:

```bash
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

I just ran it with the file you pasted above and it worked fine.

Regarding the order of columns from the JSON data. This is an interesting point that I hadn't thought of. It's because the JSON object is loaded into Python as a `dict()` object and these are intrinsically unordered. As a result, the columns will appear in a random order as you say.

I've just changed the way that the JSON and YAML are loaded so that the order of columns is remembered (using an `OrderedDict()` instead). I have a tested a [couple of files](https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/embedded_config/test_JSON_table_mqc.json) and it now seems to work nicely. Thanks for bringing this problem to my attention! Again, this should now work if you grab the development version.

Cheers,

Phil

**Comment by caleblareau** [comment]
@ewels piggy backing on this issue just because there's a clear working example--

In a custom content table, is there a straightforward way to make the values in the tables integers instead of floats? My input is an integer but I always get these .0s appended (see your comment / screen shots on March 2)

**Comment by ewels** [comment]
Hi @caleblareau,

Yes - I think you should be able to use `'format': '{:,.0f}'` to specify the number formatting in the table. eg: _(untested)_:

```
# plot_type: 'table'
# pconfig:
#     format: '{:,.0f}'
Sample_Name   My_Number
Category_1    374
Category_2    229
Category_3    39
Category_4    253
```

Give that a try and let me know how you get on! :)

Phil
