### ISSUE TITLE
Save sample name pairs at run-time, button to switch in report

### ISSUE THREAD

**Issue by jfear** [ewels/MultiQC#418]
I was wondering if it is possible to rename samples using the config. I see how to rename samples using the interactive report by pasting a tab separated mapping of sample id to sample name, but this is not saved when the report is served and accessed from multiple machines. 

1) Is there away to add renaming to the config so that this is done as part of the pipeline
2) Is is there a way to save the settings from the report so that other users will have the same settings?

thanks
Justin

**Comment by ewels** [comment]
Hi Justin,

#### Can sample renaming be done at report generation time via a config file?
I'm afraid that currently it is not possible. One of the longest running MultiQC github issues is related to this, now sat open for over a year (#132), but I've never got around to working on it. Partly because I've never really crystallised exactly how it would work.

What you're asking for here is slightly more specific - I would hazard a guess that you have a situation where samples have an internal naming convention and you'd like more meaningful names. I've written functionality to do this for our sequencing facility as part of the [MultiQC_NGI plugin](https://github.com/ewels/MultiQC_NGI) (see example report [here](http://multiqc.info/examples/ngi-rna/Test_NGI_Project_multiqc_report.html), with blue buttons to switch between sample name types). This works by saving a list of name pairs to insert into the report which are then put into the toolbox rename fields.

Is this the kind of functionality that you're looking for? I could probably generalise this and get MultiQC to accept a file of sample name pairs (or an arbitrary number of sample name replacements?) which would be saved within the report.

#### Is is there a way to save the settings from the report so that other users will have the same settings?
Again, the answer is no. Early versions of MultiQC actually _did_ have this functionality - it was possible to save settings from the report toolbox to a file and then load this file again. If such a config file was in the same directory as the HTML it would automatically be loaded. However, it never really worked very well (lots of difficulties with browser security, due to loading local files with `file://` instead of `http://`). Also, as reports became increasingly condensed to a single HTML file, it didn't make sense to spread functionality across multiple files.

It is impossible to make changes to the report in a web browser which are then perpetuated within that file. Web sandboxing prevents this. The current save system which uses browser storage is about as close as I've been able to get, but this isn't shareable between people.

These problems are the reason that I originally wrote the archaic issue #132. If you can think of any other ways that they could be approached I'd be keen to hear them!

Cheers,

Phil

**Comment by jfear** [comment]
Thanks Phil. 

Yes it looks like the MultiQC_NGI plugin would do what I am looking for. I am processing a bunch of files downloaded from SRA, (i.e., sample names are `SRR####`). When others look at the reports I would like to map a more descriptive sample name. Using the renaming mechanism works fine, but would be nice to provide the mapping via a file and then either use those names or have the big blue button like in MultiQC_NGI_plugin. Just trying to avoid having to send instructions of how to use the renaming mechanism when I share the reports. 

thanks
Justin

**Comment by ewels** [comment]
Yup, ok great. The MultiQC_NGI plugin is tied to our infrastructure, but I can write a generalised version of this for sure. I think it would be very helpful. Thanks for the suggestion!

Phil

**Comment by ewels** [comment]
ps. I made a mini side-project for the SRA out of frustration at exactly this which could be of interest in the short term: https://ewels.github.io/sra-explorer/

**Comment by ewels** [comment]
pps. I guess I could also get MultiQC to recognise SRA identifiers (`/SRR\d{3-8}/`) and automatically query the NCBI API to get nice sample names, pulling these in for the new functionality described above.. Could be pretty slick!

**Comment by ewels** [comment]
Hi @jfear,

I've just implemented this in the development version - if you could give it a spin and let me know if you run into any problems that would be great! Instructions are in the docs here: http://multiqc.info/docs/#bulk-sample-renaming

No automated SRA api calls yet, but this makes it significantly easier to write such functionality.. Just add to the `sample_names_rename_buttons` and `sample_names_rename` MultiQC config options.

Cheers,

Phil
