### ISSUE TITLE
Module request: nonpareil

### ISSUE THREAD

**Issue by ekopylova** [ewels/MultiQC#474]
Nonpareil: Nonpareil uses the redundancy of the reads in a metagenomic dataset to estimate the average coverage and predict the ammount of sequences that will be required to achieve "nearly complete coverage", defined as ≥95% or ≥99% average coverage. [Link to website](http://enve-omics.ce.gatech.edu/nonpareil/).

Examples of coverage curve, log and output files on tool [website](http://enve-omics.ce.gatech.edu/nonpareil/results?jid=example1).

Coverage, actual effort and required effort all important values.

Thanks!

**Comment by ekopylova** [comment]
I added output files in [PR #38](https://github.com/ewels/MultiQC_TestData/pull/38).

**Comment by iimog** [comment]
I looked into the four provided log files. It appears that they do not contain the numbers you are interested in. Instead those have to be calculated frorm the `.npo` file using the `Nonpareil.curve()` R function (see the [documentation](http://nonpareil.readthedocs.io/en/latest/curves.html)). As this is a non-standard function and there is no standardized way how the calculated values are stored alongside the log files those can not be easily integrated into MultiQC reports.

The actual effort can be read from the `.npo` file directly but neither the required effort nor the coverage (those require the model to be fitted). I assume that the actual effort alone is not useful? Are there any other numbers that can be read from the log files directly?

**Comment by ewels** [comment]
Hi @ekopylova,

I'm going to close this issue for now as I can't see how we're going to be able to make a standard module with useful summary statistics for this tool as it stands. Please do come back with comments if you're able to and we can reopen the issue.

Phil

**Comment by fgvieira** [comment]
I've recently created a [snakemake wrapper](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/nonpareil/plot.html) to plot the results from `nonpareil`, but it would be nicer to have the plots on MultiQC.

Since we need to run `Nonpareil.curve()` to estimate the model, I could add an output to the wrapper with the model data for input to MultiQC.
Would it make sense?

**Comment by ewels** [comment]
Please move this to a new issue, it'll get lost here otherwise 🙏🏻 

But short answer: you'll need to generate the plot data and save it to a file that MultiQC can pick up and plot. Importing `.RData` is non-ideal for many reasons (technically difficult but also will be much slower and not scale well).
