### ISSUE TITLE
picard CollectInsertSizeMetrics median insert size bug

### ISSUE THREAD

**Issue by npilshchikova** [ewels/MultiQC#478]
**Description of bug:**

When running on Picard CollectInsertSizeMetrics results, MultiQC summary table always contains incorrect Median insert size values while Insert Size plot looks correct.

For example, for the file below Median insert size from MultiQC report is 89 bp when real `MEDIAN_INSERT_SIZE` is 128 bp.

* **File that triggers the error:**
[insert_size_metrics_S52.txt](https://github.com/ewels/MultiQC/files/1085147/insert_size_metrics_S52.txt)

* **Operating System:**
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-72-generic x86_64)

* **Python Version:**
Python 2.7.12

* **Method of MultiQC installation:**
`pip`

**Comment by ewels** [comment]
Hi @npilshchikova,

Thanks for reporting this, it looks like a nasty bug. The Picard CollectInsertSizeMetrics is a tricky file to parse as it usually reports information for different read orientations separately (see the [test data files](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/picard/InsertSizeMetrics/P1339_1001.collectInsertSize.txt) for an example). There is no overall report of sample-level statistics, so the MultiQC module has to calculate these itself. It does this from this histogram data directly, which _is_ sample level.

Clearly this calculation is going wrong for your samples. I've just had a look at the report from the test data in [ewels/MultiQC_TestData](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/picard/InsertSizeMetrics), and all of these values seem to be correct. So I'm not sure what's going wrong specifically for yours.

Anyway, I'll take a look into it and get back to you..

Cheers,

Phil

**Comment by ewels** [comment]
Hi @npilshchikova,

I tracked it down in the end - it was simply because I had used a `dict` instead of `OrderedDict`, so the sequence of keys was random. For whatever reason, this wasn't affecting the other reports that I'd tested it with. Switching the two now gives the correct value - `127 bp` (1bp different to the picard result, the data in the histogram is slightly less than that in the overall report for some reason).

Thanks for spotting and reporting this bug! Let me know if you have any trouble with the fix.

Phil
