### ISSUE TITLE
feature request - preseq lc_extrap curves

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#49]
For example, for a paired-end bam file, preseq lc_extrap can be run like this:
 
```
Input file(s):	SAMPLE.bam
Output file(s):   SAMPLE.preseq.lc_extrap.tsv
Tool(s):      	preseq lc_extrap
 
$ preseq lc_extrap
	-B –P  
	-o SAMPLE.preseq.lc_extrap.tsv  
	SAMPLE.bam
```
The output of preseq lc_extrap can be plotted in a curve indicating the ratio of “number of molecules (M)” and “number of distinct molecules (M)”. See below a description of three examples from the preseq website (http://smithlabresearch.org/software/preseq/challenge/)

Instructions on how to install this software and its dependencies can be found at http://smithlabresearch.org/software/preseq

**Comment by ewels** [comment]
Yup, absolutely - we routinely run preseq here too, so I've been planning to write this into MultiQC as well.

I'll probably model it on our [existing plotting script for preseq](https://github.com/ewels/ngi_visualizations/tree/master/ngi_visualizations/preseq_complexity_curves)..

**Comment by ewels** [comment]
@avilella - that's done. Let me know if it works for you, I wasn't super happy for the way that it finds files (currently just searches for the string `TOTAL_READS	EXPECTED_DISTINCT`

This is what the output looks like:

![image](https://cloud.githubusercontent.com/assets/465550/10454539/89e46244-71b5-11e5-879a-0286c5393305.png)

**Comment by vladsaveliev** [comment]
Hi Phil, 

I'm wondering if you have MultiQC-based code for preseq with the extended features for displaying depth instead of counts and dots with current counts, like in your matplotlib-based visualization  https://github.com/ewels/ngi_visualizations/tree/master/ngi_visualizations/preseq_complexity_curves
I'm thinking of tackling it in my custom plugin for MultiQC and provide the required extra metadata though command line, but wanted to first check if you already done that.

-
Vlad

**Comment by ewels** [comment]
Hi @vladsaveliev,

This isn't something I've done yet, no. It's been in the back of my mind for a while though - it would certainly be nice to have. The X coverage thing should be pretty easy and I _think_ that you should be able to plot the additional dots by using the [`extra_series`](http://multiqc.info/docs/#additional-data-series) pconfig option.

As you touch on - the problem is getting in this metadata. I was thinking about this last night after I read your comment. The natural way to do this is by using the MultiQC config file (as done for lots of other modules - eg. [FastQC Theoretical GC Content](http://multiqc.info/docs/#theoretical-gc-content)). I think it would make sense to do the same here, however it is a bit of a pain not being able to specify these variables on the command line when running MultiQC.

To get around this, I propose adding a new core feature to MultiQC - a generic command line option to specify any config variables at runtime. I could try to parse any given string as yaml and put that into the config.  For example, `--cvar preseq:genome:hg18` / `--cvar preseq:genome_size:3156105057` in this case. If yaml parsing fails I could just take the string as a key and set it to `True` (eg. `--cvar export_plots`).

Do you think this is feasible? Would this work in your scenario? The read count dots would be harder to do by command line as you need sample name and value for every sample which could get pretty long quite quickly. But you could put them in a config file I guess.

Phil

**Comment by vladsaveliev** [comment]
Phil, thanks a lot for your reply,

In my case, I actually already pass some metadata in a json file using the command line extension, and apply it in a code that is fired by hooks https://github.com/AstraZeneca-NGS/NGS_Reporting/blob/master/MultiQC_az/multiqc_az/multiqc_az.py (by the way - I'm a big fan of how extensible MultiQC is).
So it would be just natural for me to keep using this mechanism to pass metadata for preseq. I guess I can do that as well with a config file, but I want to keep general MultiQC settings and project-specific metadata separately in my pipeline.

However I think your idea of passing yaml data via the command line is just brilliant. When it comes to specifying some small metadata like genome build for a quick MultiQC run, it would be an overkill to create a config file. So it would be nice to have this, and I imagine command line settings would override those specified in config files.

Vlad

**Comment by vladsaveliev** [comment]
Hi Phil, 

I tried to bring up the code for real counts:  https://github.com/vladsaveliev/MultiQC/commit/f2f7367070da49484c1c0b3d8cf932fa54be8c90
however I got stuck into 2 issues:
- I'm not sure if it's possible to add dots to `extra_series` for a line graph. In my code just for the sake of testing I used a workaround of small lines of 1px size, and I'm wondering if updates into core must be brought in order to implement dots correctly.
-  Secondly, I'm not sure how to make dots the same color as related lines (but keeping using the default colors at the same time).

If you have any advice or ideas on that for me, or just thinking of implementing it yourself - anything would be great. Of course, no rush with that, put any priority on that as you like.

(I probably should have started a new thread for that, but hoping that would be quick)

**Comment by ewels** [comment]
Hi Vlad,

I've made a new issue for the command line config thing: #460

Re: your plugin and JSON data - that's totally fine of course. But as this is a feature that's been requested by a few people it would be nice if we could make it a core function that you tie into with your plugin (rather than being totally specific to your code). But I think we're already on the same page here.

> _I'm not sure if it's possible to add dots to `extra_series` for a line graph_

Quite possibly not, sorry. I haven't tried - it was a bit of a guess :) I'll take a look into sorting this out.

> _How to make dots the same color as related lines_

The default HighCharts colours follow a [default schema](http://api.highcharts.com/highcharts/colors):
```javascript
colors: ['#7cb5ec', '#434348', '#90ed7d', '#f7a35c', '#8085e9',  '#f15c80', '#e4d354', '#2b908f', '#f45b5b', '#91e8e1']
```

So as long as you know the order of your samples in the plot, you should be able to rotate through the same colours. NB: The sample names _may_ be sorted alphabetically. They are for the bar plot - not sure off the top of my head whether they are for the line plot also.

Finally - I've only quickly skimmed your code, but I think it could be better to use the normal MultiQC file loading procedure for the counts files? That's what we did for the FastQC GC content addition - has a few benefits such as easier / consistent method for users to set their own file patterns. Also there's some stuff in that core function such as handling of weird encoding types and other edge cases.

Phil

**Comment by vladsaveliev** [comment]
Phil,

That's right, I added that code the way it can be pulled into the main code base. In fact I'm just following the way the FastQC theoretical GC is implemented, and that's why I'm not quite following about the "file loading procedure" - are you suggesting adding the normal counts file into search patterns, and use `find_log_files`? Because FastQC doesn't use that, and explicitly calls `io.open`: https://github.com/ewels/MultiQC/blob/master/multiqc/modules/fastqc/fastqc.py#L443 (here I agree that I should be using `io.open` instead of `open` as it handles encoding, but I'm guessing you meant something more than just replacing `open` with `io.open`?)

Thanks for the explanation on colors. I was hesitant to specify them explicitly because it adds code duplication, but I'm guessing that's okay since the colors are originally specified in an external js library `highcharts.js` without a clear way to abstract them.

Vlad

**Comment by ewels** [comment]
Yup, true - the line you highlighted is for setting a config path that is used for all runs. The [code above it](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/fastqc/fastqc.py#L432) uses the regular file input system though. I'd forgotten about the secondary config-path thing. Either / both are fine I guess :)

I have previously thought of adding the possibility to customise the default HighCharts colours using the `HighCharts.colours` api point linked to above. But I can't see a big demand for that so it probably won't happen. So fine to go ahead and hardcode I think.

Phil

**Comment by vladsaveliev** [comment]
Cool, thanks Phil, it's clear now for both questions.

**Comment by ewels** [comment]
Command line config thing written and working 👍  Shout if / when you need anything from me, otherwise I'll wait for the PR :)

NB: Hoping to get a release out this week..

**Comment by vladsaveliev** [comment]
Nice. Meanwhile I figured out how to add dots (super straightforward!). Will polish the code and prepare a PR here and into MultiQC_TestData as well.

**Comment by vladsaveliev** [comment]
After starting using Preseq regularly in production, we realised that the most useful view is depth versus input (molecule counts). Not counts vs unique counts or depth vs depth. In other words, the most interesting information one gets from these plots is how the resulting depth changes with the changing amount of molecules. 

So what do you think about making the X axis always showing the molecule numbers, even if the Y shows the depth? Or at least put them in a tooltip. I'm going to make this change and send some examples to demonstrate the idea.

**Comment by vladsaveliev** [comment]
Like this:
![screen shot 2017-09-02 at 04 11 22](https://user-images.githubusercontent.com/1575412/29991694-818c0954-8f94-11e7-9eca-fd671e800805.png)

Maybe even make a switch between "depth vs depth" / "depth vs molecules"?

**Comment by vladsaveliev** [comment]
And take read_count_multiplier into account: 
![screen shot 2017-09-02 at 05 03 36](https://user-images.githubusercontent.com/1575412/29992071-b340a034-8f9b-11e7-9f2f-4ed3d52a64fe.png)

**Comment by ewels** [comment]
Hi @vladsaveliev,

I certainly see the logic - this means that you can see the rate of return (increased coverage) with increased sequencing depth, which is less abstract. Makes sense!

Seeing as this plot requires addition to the user config file anyway, how about extending these config variables to let the user decide what to show - reads or coverage, on each axis?

Definitely a big +1 for using `read_count_multiplier` for the tooltip too 👍 

Phil
