### ISSUE TITLE
TypeError: 'NoneType' object has no attribute  error when using custom config file

### ISSUE THREAD

**Issue by kplaney** [ewels/MultiQC#502]
**Description of bug:**
Getting error `TypeError: 'NoneType' object has no attribute` when using custom config file.  I tried re-running it with most of our custom configs commented out and I'm still getting the same error. I am running it as a root user. I tried the `~/.multiqc_config.yaml` route because adding it to the install directory and using an environment variable to specify where the config file is did not cause multiqc to find / recognize the config file.

**Error log:**
```python
  File "/usr/local/bin/multiqc", line 668, in <module>
    multiqc()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/multiqc", line 187, in multiqc
    config.mqc_load_userconfig(config_file)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/utils/config.py", line 103, in mqc_load_userconfig
    mqc_load_config(os.path.expanduser('~/.multiqc_config.yaml'))
  File "/usr/local/lib/python2.7/dist-packages/multiqc/utils/config.py", line 124, in mqc_load_config
    mqc_add_config(new_config, yaml_config)
  File "/usr/local/lib/python2.7/dist-packages/multiqc/utils/config.py", line 169, in mqc_add_config
    if os.path.exists(v):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

* **File that triggers the error:**
    [*](https://github.com/ewels/MultiQC/blob/master/multiqc_config_example.yaml)  Our personal YAML file and the untouched example config file on G-thub produces this error.

* **Operating System:**
    * eg. Debian Jessie
* **Python Version:**
    * tested on both Python 2.7 and 3.5 - slightly different messages but both say `TypeError: 'NoneType' object has no attribute`
* **Method of MultiQC installation:**
    * eg. both `pip` and github manual install

**Comment by ewels** [comment]
Hi @kplaney,

Thanks for this bug report, sounds like I've broken something. Is this the development version? Is there a version / commit hash that you're running from? The reason I ask is that I [made some changes](https://github.com/ewels/MultiQC/commit/5489c7c35edd0f112b4ea4e0db0b611826ff7888) to how the config file loading is handled yesterday so I may have broken it then.

Cheers,

Phil

**Comment by ewels** [comment]
Hi @kplaney,

I've just tracked this error down. It's because of the config line `custom_logo: null`. I added some code that checks that this file exists and it breaks when it's `None` (`null` in yaml).

I've updated this code to skip this check if the new config option evaluates to `False`. I've also added this config file to the automated testing so that future errors like this are flagged.

General question: I've been thinking of removing the `multiqc_config_example.yaml` file for a while now as it only describes a fraction of the available config options and tends not to be maintained properly (as happened here). Would you object to this? I'm interested to know how and why you used it basically :)

Thanks,

Phil
