### ISSUE TITLE
Question: Mass Chromatogram or Classic linegraph

### ISSUE THREAD

**Issue by lecorguille** [ewels/MultiQC#535]
Hi,
First of all, great job. MultiQC is really what we missed to compare graphs accross samples (specially for the FASTQC repport). Far better than Excel (what a shame :smile: ) !

I’m wondering if you have a module to display generic 2 columns tabular files like that:

```
"Retention Time"        "TIC"
2503.69308488001        44464
2505.25808488001        44632
2506.82308488001        45232
2508.38808488001        46200
2509.95308488001        46592
2511.51808488001        46376
2513.08308488001        45760
```

My purpose is to display layers of [Mass Chromatogram TIC](https://en.wikipedia.org/wiki/Mass_chromatogram#Total_ion_current_.28TIC.29_chromatogram)

I have already look at the Custom content and manage to display graph which look correct 👍 
But I don't get axis label, graph title ... And it seems that you don't consider that it's a steady feature.

So my questions are:
 - Do you already have a generic module to display this kind of basic graph?
 - Else: Do you think that it's better to write a module to deal with generic 2 columns tables or a specific dedicated module for Mass Chromatograms?
 - In all cases: Can you point me a module which fit the most with what I want, as a starting point
 - In all cases: Do I have to write a module or a plugin?

Thanks a lot

**Comment by ewels** [comment]
Hi @lecorguille,

Glad you like MultiQC! 

Is the output from a standard released tool or a custom script? As in, will other people have similar data in the same format? If so, then it's probably best to write a new module to handle it so that other people can benefit. If it's custom output, then using _Custom Content_ should be fine.

In MultiQC terminology, a module is a chunk of Python that handles output from a specific tool. It can be part of the main MultiQC package or separately installed. A plugin hook is a point in the MultiQC execution where you can tie in your own arbitrary Python code to do stuff.

Note that you can add configuration to _Custom Content_ plots to add things like axis labels and titles. If it's a custom script then you can add it as a header to the file. If not, then you can add it to your MultiQC configuration file. The docs need to be rewritten really sorry. But see an example of header lines config [here](https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/embedded_config/test_table_mqc.txt#L1-L2) and in a MultiQC config file [here](https://github.com/ewels/MultiQC_TestData/blob/master/data/custom_content/plot_config.yaml#L47-L60) (see [docs](http://multiqc.info/docs/#separate-configuration-and-data-files)). The docs contain possible options - hopefully you can find everything in the docs (eg. [here](http://multiqc.info/docs/#line-graphs)), but feel free to ask if you need help.

If writing a new module, see the relevant [docs](http://multiqc.info/docs/#writing-new-modules). The [cutadapt module](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/cutadapt/cutadapt.py) is usually a fairly good starting point for reference, and contains a line plot similar to what you want to generate here.

I hope this helps! Let me know if you have any questions.

Phil

**Comment by lecorguille** [comment]
Cool!

This example help me a lot
```
# title: 'Output from my script'
# description: 'This output is described in the file header. Any MultiQC installation will understand it without prior configuration.'
# section: 'Custom Data File'
# format: 'tsv'
# plot_type: 'bargraph'
# pconfig:
#    id: 'custom_bargraph_w_header'
#    ylab: 'Number of things'
Category_1    374
Category_2    229
Category_3    39
Category_4    253
```

It will be enough for the first version. I will see later for a module/plugin.

Do you mind if I propose this *Custom Content* support in the [Galaxy wrapper](https://github.com/EnginesOn/galaxy_tools)?

**Comment by ewels** [comment]
Great! Yes if you like, that's no problem!

A module is probably nicer in the long run, if nothing else the tool then shows up on the the MultiQC homepage and has documentation. Going by the example you pasted above it should be a pretty quick one to write ;)

I'll close this issue now, but feel free to add to it if you have any questions..

Phil
