### ISSUE TITLE
HsMetrics : Module picard raised an exception

### ISSUE THREAD

**Issue by Char-Al** [ewels/MultiQC#568]
Hi Phil,

Thanks for the works on MultiQC.

**Description of bug:**
The Picard module seems to have an error with HsMetrics, at least mine.
I have the exactly same error with an old version before:
    - v0.9;
    - python 2.7;
    - same os (elementary OS 0.4 Loki based on "Ubuntu 16.04.2 LTS");
    - pretty sure that I install it with the manual method.
Then I uninstall it and reinstall with pip.

**MultiQC Error log:**
```
============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "/home/charles/miniconda3/bin/multiqc", line 411, in multiqc
    output = mod()
  File "/home/charles/miniconda3/lib/python3.6/site-packages/multiqc/modules/picard/picard.py", line 60, in __init__
    n['HsMetrics'] = HsMetrics.parse_reports(self)
  File "/home/charles/miniconda3/lib/python3.6/site-packages/multiqc/modules/picard/HsMetrics.py", line 173, in parse_reports
    tbases = _add_target_bases(data)
  File "/home/charles/miniconda3/lib/python3.6/site-packages/multiqc/modules/picard/HsMetrics.py", line 242, in _add_target_bases
    data_clean[s][int(h.replace("PCT_TARGET_BASES_", "")[:-1])] = data[s][h] * 100.0
TypeError: can't multiply sequence by non-int of type 'float'
============================================================
```

* **File that triggers the error:**
    * [HsMetrics.tsv.zip](https://github.com/ewels/MultiQC/files/1262996/HsMetrics.tsv.zip)
* **MultiQC Version:**
    * MultiQC v1.2
* **Operating System:**
    * elementary OS 0.4 Loki based on "Ubuntu 16.04.2 LTS"
* **Python Version:**
    * python3.6
* **Method of MultiQC installation:**
    * pip

**Comment by ewels** [comment]
Thanks @Char-Al - I get the same error. The problem is because Picard uses machine locale settings, so in some situations (mostly Germany & France) it uses commas (`,`) instead of full-stops (`.`) to denote the decimal place. This is what's happened in your HsMetrics file.

This is (a) extremely annoying from the point of MultiQC and (b) almost impossible to do anything about. In this case it means that MultiQC can't convert the numbers to floats and leaves them as strings. This then triggers the above error.

In some cases I'm able to search for a string that I know should be a decimal that can never be over 1000 and detect the decimal place marker. Then if it's a comma I can switch these throughout the input file. Whether I can do this or not depends on the input file though. I'll have a look and see what I can do.

If possible, the best solution is for you to update your server settings so that Picard uses `.`, but I understand that this isn't always possible (or desirable).

Phil

**Comment by ewels** [comment]
ps. I just googled this to see what the majority of the world uses, and it's more balanced than I expected:

![map](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/DecimalSeparator.svg/940px-DecimalSeparator.svg.png)
![key](https://user-images.githubusercontent.com/465550/29866022-6626a378-8d77-11e7-819c-08bf3b177555.png)

I wish that everyone could just agree on one date and number formatting system! 😉

**Comment by ewels** [comment]
Hi @Char-Al,

I think this is fixed now. The HsMetrics file has a bunch of percentage values which are always between 0-1. I've updated the code to check these first for each file to look for commas. If found, they're switched for `.` before saving the parsed value. This then makes everything work downstream and the module now works.

Hope this fixes the problem for you - let me know how you get on!

Cheers,

Phil

**Comment by Char-Al** [comment]
HI Phil,

Thank you for responsiveness.
It seems to be ok !
Great ! 

_"I wish that everyone could just agree on one date and number formatting system! :wink:"_
Totally agree and furthermore the same separator, in France we use ";" as separator on csv files :sob:

Thanks again !

All the best,

Charles.
