### ISSUE TITLE
Changes to the Prokka module - author seeks advice

### ISSUE THREAD

**Issue by tseemann** [ewels/MultiQC#587]
Hello,

I am the author of Prokka, which you support: http://multiqc.info/docs/#prokka

Prokka outputs a folder of files - the folder and prefix are user options - as per follows:
```
foo.err  foo.faa  foo.ffn  foo.fna  foo.fsa  foo.gbk  
foo.gff  foo.log  foo.sqn  foo.tbl  foo.tsv  foo.txt
```
I believe that multiqc currently uses the `foo.txt` file (see below):
```
organism: Genus species strain
contigs: 1
bases: 56520
CDS: 63
```
I also understand this file is not ideal, as it has no headings, or software version etc.

This file is fairly new and most people don't use it, so there is opportunity to make it better, and I seek your advice on how to best make it work within your framework.

Any advice appreciated!

**Comment by ewels** [comment]
Hi @tseemann,

Thanks for getting in touch! I wasn't aware of the other files that Prokka made (the MultiQC module was written by @boulund) - would any of those be more appropriate for MultiQC to parse?

In terms of the text file, as you say - an additional header line would be really helpful as it would make the file search a lot more specific to prokka. Adding the version number would also be really good: we have a future feature in the works to pull out software version numbers where available so that would certainly be helpful.

My favourite way to find files is by having some kind of standard filenaming convention (as it's fastest - we don't need to open any files). For example, having a standard suffix - `foo_prokka.txt`. But I know that not everyone agrees with me on that point and it's a pretty marginal improvement.

Finally - if you have any suggestions for how the MultiQC module could be improved (new information / new plots etc) then let us know..

Thanks,

Phil

**Comment by boulund** [comment]
Cool. I made it as a quick 'n dirty module at a request of @thorellk, who wanted something to summarize Prokka results in MultiQC. There's definitely room for improvement, and I appreciate any discussion in that direction! :)

**Comment by ewels** [comment]
Closing this issue now - please comment or reopen if I can of any help!

Phil
