### ISSUE TITLE
Report with raw and trimmed fastqc results

### ISSUE THREAD

**Issue by royfrancis** [ewels/MultiQC#620]
Is it possible to create a report with two separate modules (tabs) of FastQC results. ie; FastQC results for raw files and FastQC results for trimmed files. They have the same names. Or should they?

**Comment by ewels** [comment]
Hi @royfrancis,

This is something that has been under much discussion since I first released MultiQC. Typically, they either all end up in the same plot together, or they overwrite each other semi-randomly (depending on your [sample name cleaning setup](http://multiqc.info/docs/#sample-name-cleaning)).

However - a new feature merged recently allows you to run modules multiple times with different filename filters if you wish (see the [docs](http://multiqc.info/docs/#order-of-modules)). One of the main use cases of this was for exactly what you describe, and the docs have an example config for that. Note that it's only available in v1.3dev (which I hope to release today).

The above setup will insert two FastQC sections into your report. This still isn't as slick as I would like and doesn't handle things like read 1 / read 2 grouping and averaging. I have written a separate new feature to handle this kind of sample grouping which is sat in #576 awaiting proper testing. I will merge this as soon as v1.3 is released so that it can undergo testing in the v1.4 development version for a while before stable release. This will hopefully ship with "sensible defaults" for FastQC which may pick up your situation without any custom configuration setup needed.

Shout if you have any questions, and let me know how you get on making this work! It's all pretty new, so it's good to get feedback about how easy it is to set up and how well it works.

Cheers,

Phil
