### ISSUE TITLE
Certain Picard metrics files are not recognized with newer Picard versions

### ISSUE THREAD

**Issue by riederd** [ewels/MultiQC#655]
**Description of bug:**

MulitQC 1.3 does not recognize certain metrics files from picard 2.16.0, seen with:

- MarkDuplicates
- HsMetrics

**MultiQC Error log:**

no error, log available, picard metrics files are just not recognized.

* **File that triggers the error:**

MarkDuplicates and HsMetrics metrics files generated with Picard version 2.16.0 

* **Command used to run MultiQC**
    * `multiqc .`
* **MultiQC Version:**
    *  MultiQC v1.3
* **Operating System:**
    * CentOS 7.4
* **Python Version:**
    * Python 2.7.14
* **Method of MultiQC installation:**
    * pip

Patches that fixes the issues are attached.
[PicardMetricsPatches.zip](https://github.com/ewels/MultiQC/files/1614418/PicardMetricsPatches.zip)

**Comment by michaelmayer2** [comment]
I can see the same issue with other metrics like CollectRnaSeqMetrics and so I suppose this is more of a generic problem with the picard/MultiQC interaction. 

picard 2.5.0 seems to work fine with latest MultiQC but newer versions simply do not write the headers prefixed with picard.analysis any more. (e.g. in picard 2.5.0 it would write "# picard.analysis.CollectRnaSeqMetrics..." but in later versions it would just write "# CollectRnaSeqMetrics" and then MultiQC cannot detect that this is picard generated data. Strangely enough in ##METRICS_CLASS picard.analysis is nicely prefixed.

While the suggested fix above probably works I am not sure if we fix a problem that was actually created by picard and should be rather fixed in picard ?

**Comment by ewels** [comment]
Thanks both. I guess the easiest solution is to make the strings more generic as in the patch, but for all Picard subbmodules (also in the [search patterns](https://github.com/ewels/MultiQC/blob/master/multiqc/utils/search_patterns.yaml#L211-L243) used to find the files).

I think it may be a little ambitious to hope for the Picard team to update the logging output 😉 I guess that they are generated automatically by the Java classes somehow, hence they can vary quite a bit. The more generic names will hopefully be sufficient and still specific enough.

Phil

**Comment by riederd** [comment]
Phil,
I think that might be the best solution. Using a regex should do the trick.

**Comment by ewels** [comment]
Hi @michaelmayer2, @riederd,

I've just pushed a change to address this problem. It works with the test data that I have, however I don't have any example data for the newer versions of Picard so please pull the development version and have a go for me.

If you're able to submit some new example files to ewels/MultiQC_TestData that would be brilliant.

Thanks,

Phil

**Comment by ewels** [comment]
I’m going to close this issue now but please let me know if you still have problems.

Phil

**Comment by riederd** [comment]
Thanks! I'll report if I still see problems.

Dietmar

**Comment by tooba65** [comment]
Hi 
I have the same problem with EstimateLibraryComplexity as the multiqc can not detect them to summerize!

**Comment by ewels** [comment]
Hi @tooba65,

I only just found this issue sorry, please make new issues as comments on closed issues are easy to miss. When you do, please post a few more details - ideally an example input file that is not working - so that I can try to replicate the problem at my end to help.

Phil
