### ISSUE TITLE
bcl2fastq2 ZeroDivisionError

### ISSUE THREAD

**Issue by aledj2** [ewels/MultiQC#661]
Hi Phil,

Just ran the latest version of multiqc and have the following error from the bcl2fastq module.

Have attached the file which produced the error

[Stats.json.gz](https://github.com/ewels/MultiQC/files/1623091/Stats.json.gz)

```python
Module bcl2fastq raised an exception: Traceback (most recent call last):
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.4-py2.7.egg/EGG-INFO/scripts/multiqc", line 427, in multiqc
    output = mod()
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.4-py2.7.egg/multiqc/modules/bcl2fastq/bcl2fastq.py", line 21, in __init__
    self.parse_file_as_json(myfile)
  File "/home/dnanexus/Miniconda/lib/python2.7/site-packages/multiqc-1.4-py2.7.egg/multiqc/modules/bcl2fastq/bcl2fastq.py", line 171, in parse_file_as_json
    run_data[lane]["percent_Q30"] = (float(run_data[lane]["yieldQ30"]) / float(run_data[lane]["total_yield"])) * 100.0
ZeroDivisionError: float division by zero
```

**Comment by aledj2** [comment]
Is a pretty horrible hack but have put some of the division lines in a try except statement, setting value to NA if it fails - not sure if that's appropriate

I'm not sure if it's even a real issue or if I've got a dodgy stats file.


[bcl2fastq.py.gz](https://github.com/ewels/MultiQC/files/1623145/bcl2fastq.py.gz)

**Comment by ewels** [comment]
Sorry @aledj2, you just missed the v1.4 release - I pushed it out in a bit of a rush as pip installations were suddenly failing due to an upstream dependency change.

Sounds like a pretty common edge case scenario that comes up quite a bit in MultiQC. Here your total_yield must be 0. Doesn't really matter if you have a weird file or not - if you managed to trigger it then other people can presumably do the same, doesn't hurt to handle it nicely. Catching the error and setting to NA sounds like a sensible way to handle it.

Could you open a PR for the changes? They look fine. For shorter code could perhaps use an inline conditional instead:

```python
run_data[lane]["percent_Q30"] = (float(run_data[lane]["yieldQ30"]) / float(run_data[lane]["total_yield"])) * 100.0 if float(run_data[lane]["total_yield"]) > 0 else 'NA'
run_data[lane]["percent_perfectIndex"] = (float(run_data[lane]["perfectIndex"]) / float(run_data[lane]["total"])) * 100.0 if float(run_data[lane]["total"]) > 0 else 'NA'
run_data[lane]["mean_qscore"] = float(run_data[lane]["qscore_sum"]) / float(run_data[lane]["total_yield"]) if float(run_data[lane]["total_yield"]) > 0 else 'NA'
```

...but I'm not sure that it's any cleaner and certainly not easier to read. So stick with the try / except I think. Could you limit to `except ZeroDivisionError` though please.

Cheers,

Phil
