### ISSUE TITLE
Flat to interactive plots

### ISSUE THREAD

**Issue by mukarram-ak** [ewels/MultiQC#670]
Hello,

I am wondering if there's any way to convert the already generated MultiQC html report that has flat plots to another new report with HighCharts plots (without running another run of MultiQC)?

Thanks before,
Kadir

**Comment by ewels** [comment]
Hi Kadir,

Unfortunately no - the flat images are used mostly so that the raw data doesn't have to go into the report (embedding so much data makes the HTML files huge). So the plot data needed for interactive plots never goes into that HTML.

It is possible to export all plot data to text files when running MultiQC ([`--export`](http://multiqc.info/docs/#exporting-plots)), but again that has to be specified at run time. However, if a recent version of MultiQC then there may be a file called `multiqc_data/multiqc_data.json` exported, which also contains all of the plot data. This is designed for use by the upcoming [MegaQC](https://github.com/ewels/MegaQC), which is able to replicate most MultiQC plots interactively. You're welcome to try out MegaQC and submit this JSON file, though please note that it's very buggy and undocumented at this time. In a few more months it will hopefully be a lot more polished! You can of course also extract this data from the JSON yourself and plot it in R, or whatever other system you like.

I hope this helps!

Phil
