### ISSUE TITLE
Use OrderedDict for consistent output files format

### ISSUE THREAD

**Issue by RoxaneLS** [ewels/MultiQC#676]
The order of the columns in MultiQC output files is random, which means it is different from one report to another.

* `head -n1 MyRun1/multiqc_data/multiqc_fastqc.txt | cut -f2` --> `adapter_content`
* `head -n1 MyRun2/multiqc_data/multiqc_fastqc.txt | cut -f2` --> `overrepresented_sequences`
* `head -n1 MyRun3/multiqc_data/multiqc_fastqc.txt | cut -f2` --> `per_base_n_content`

This is an issue when parsing those files with a third party tool.

Could you pls look into using `OrderedDict` in order to keep the order of columns consistent across runs ?

**Comment by ewels** [comment]
Hi @RoxaneLS,

I can't replicate this - I tried running on a few different FastQC files and my `multiqc_data/multiqc_fastqc.txt` columns always had the same order. This is backed up by the code, which sorts the columns alphabetically.

What are your input files and MultiQC version? Could you send something over so that I can replicate the behaviour?

Cheers,

Phil

**Comment by RoxaneLS** [comment]
Ok same thing here, it seems to be ordered when using the dev version.

Also as it turns out there is no need to collate the data for chronQC, it (is supposed) to read within the files and sort the info out itself - still having some issues though.

Thanks anyway, you can probably close this. I just need to use the dev version - or perhaps a more recent release one? I'm using v1.2 at the moment.

**Comment by ewels** [comment]
Ok great, then yes I've already fixed this then. Version 1.2 is from August, so quite a lot has changed since then. You can see the releases with their changelogs here: https://github.com/ewels/MultiQC/releases

It's a good idea to always use at least the latest release. Hopefully when you run MultiQC it should tell you that a new version is available (if it has access to the internet to check). When you hit problems it can sometimes be useful to try running the latest development version before asking for help as I have a terrible memory for which issues I've already fixed. The first step for me is always to try to replicate the problem though, and I'm always running the latest development version myself.

In this case, the v1.4 release is quite recent so I imagine that running 1.5dev isn't necessary.

Phil

**Comment by RoxaneLS** [comment]
Sure, sorry about that. will make sure to try things on the dev version before asking in the future. Cheers
