### ISSUE TITLE
dedup coverage calculations on preseq plot

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#68]
Adding a couple of extra text boxes above the preseq plot, so that the mouse-over dialog information at any given point in the curve dynamically gives dedup cov values:

numcycles: 300 (or 2x150, or 2x125)
genomesize: 3,000,000,000

Mouse over dialog:
```
sample id
XXX total, YYY unique, AA totalcov, BB dedupcov 
```

where we can calculate `AA = (XXX * numcycles) / genomesize` and `BB = (YYY * numcycles) / genomesize`

**Comment by ewels** [comment]
To be clear - `numcycles` means average read length in this context? Nice idea! I'll need to have a think about how to implement this though.

**Comment by avilella** [comment]
Yes, numcycles as the best proxy multiplier to go from total fragments
(preseq) to total bases (coverage). I presume there may be constraints in
how to hook this up together in javascript, but I am not the expert :-p

**Comment by ewels** [comment]
Yup - we did [exactly this](https://github.com/ewels/ngi_visualizations/tree/master/ngi_visualizations/preseq_complexity_curves#using-coverage-instead-of-read-counts) in our python preseq plotting library.

The javascript is not difficult _per se_, it's just a case of how to work it into the MultiQC helper functions.

**Comment by ewels** [comment]
_Note to self:_ This needs to have logic within the module that knows whether a flat plot will be used or not. Same will be necessary elsewhere. Needs a bit of thought.

**Comment by ewels** [comment]
Ok, having given this more thought, I think it's going to be quite a lot of work. Because of the abstraction of the plotting code it's quite a lot of work to change the data interactively. It would be fine to have a second dataset to show which would be Human 2x125bp, but with the different potential variables it has to be a front end JS solution. This in turn needs to modify the datastructures in the report but be possible to revert and I think will basically break everything unless a lot of code is written. Even if this is all written, it will still only ever work for the HighCharts plots and not matplotlib.

Whilst the feature would be nice, there are other things that I'd rather spend the time on writing code for, so I'm going to close this issue for now. Sorry!
