### ISSUE TITLE
MultiQC on several BUSCO files

### ISSUE THREAD

**Issue by marijazmf** [ewels/MultiQC#685]
Hi,

I have issue running MultiQC on several BUSCO files. Even though all files are named differently (always starting with `short_summary_...`) MultiQC provides me result of last file only. 
I suppose it has something to do with a naming. It looks like all names are split by `_` and only first part of the name is used (`short`). 

I am looking forward to your solution. 

Best,
Marija

**Comment by ewels** [comment]
Hi @marijazmf,

This was a strange one, but you're completely right! It happens also with [my test data](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/BUSCO/version_2).

After digging around with lots of `print` statements in various places I finally tracked it down. It was due to some overly aggressive file name cleaning parameters that had been added at some point. It should now be fixed in the v1.5dev development version.

Thanks for reporting! Shout if you find any other problems.

Phil
