### ISSUE TITLE
Default renaming profile on report opening

### ISSUE THREAD

**Issue by rfenouil** [ewels/MultiQC#692]
Dear Phil,

I find the bulk renaming options very useful to reformat ugly sample name to something more useful.
However when I open the report, the original (ugly) names are showing by default.
Would it be possible to add an option specifying which naming scheme to apply on opening ?

Thank you !

**Comment by ewels** [comment]
Hi @rfenouil,

Revisiting an ancient issue here. I have never implemented your solution because (a) it would be technically difficult but more importantly, (b) I consider the original sample names to be the "true" references for each sample, and don't really want these hidden by default.

However, it's not all bad news. I just added a new core option `--replace-names` in abb8798b2d37c019e800b4043ae107a1dba4d0b0. Documentation is here: https://multiqc.info/docs/#sample-name-replacement

This does a hard swap of substrings / uses regular expressions _during report generation_. This means that the original ugly names never make it to the HTML report, and the replaced names are treated as the "true" sample name. It's 3 years late and it's not what you asked for, but hopefully this is useful for you! 😅 

This is now generally available in v1.11dev of MultiQC and will be released very soon. Let me know if you get a chance to play with it and have any suggestions.

Thanks,

Phil
