### ISSUE TITLE
rnaseq report from the qualimap tools

### ISSUE THREAD

**Issue by tomsing1** [ewels/MultiQC#73]
The [qualimap](http://qualimap.bioinfo.cipf.es/) command line tool can generate different reports, e.g. 
* `bamqc` (already supported by MultiQC)
* `rnaseq`, 
* `counts`
* ...

Would it be possible to add support for the `rnaseq` report to MultiQC as well?

**Comment by ewels** [comment]
Absolutely! Yes, we just wrote the `bamqc` module because that's what we use here, so we had some example reports easily available.

I just had a dig and found the example data from the qualimap docs - an [RNA seq report](https://github.com/kokonech/kokonech.github.io/tree/master/qualimap/kidney_rnaseqqc) and [counts](https://github.com/kokonech/kokonech.github.io/tree/master/qualimap/glcn_mice_counts).

Is there anything specific that you'd like taken from the qualimap analysis? I'm thinking:

- [ ] [`Reads aligned`](https://github.com/kokonech/kokonech.github.io/blob/master/qualimap/kidney_rnaseqqc/rnaseq_qc_results.txt#L14) (general stats table)
- [ ] [`Aligned to genes`](https://github.com/kokonech/kokonech.github.io/blob/master/qualimap/kidney_rnaseqqc/rnaseq_qc_results.txt#L18) (general stats table)
- [ ] [`Reads genomic origin`](https://github.com/kokonech/kokonech.github.io/blob/master/qualimap/kidney_rnaseqqc/rnaseq_qc_results.txt#L24-L28) (bar plot - percentages / counts of exonic, intronic, intergenic)
- [ ] [`Coverage Profile Along Genes (Total)`](https://github.com/kokonech/kokonech.github.io/blob/master/qualimap/kidney_rnaseqqc/raw_data_qualimapReport/coverage_profile_along_genes_(total).txt) (line chart)

It would be nice to have a [Coverage Histogram (0-50X)](http://rawgit.com/kokonech/kokonech.github.io/master/qualimap/kidney_rnaseqqc/qualimapReport.html#Transcript coverage histogram) and the [Junction Analysis](http://rawgit.com/kokonech/kokonech.github.io/master/qualimap/kidney_rnaseqqc/qualimapReport.html#Junction Analysis) plots too, but I can't find any raw data for those.. Did I miss anything?

Phil

**Comment by tomsing1** [comment]
Great! Yes, those are the sections I would be most interested in as well.

**Comment by ewels** [comment]
Hi @tomsing1,

I've just added this in for you - it works for me with the test data available on the Qualimap website. If you could have a go with the development version on some of your reports, that would be great!

Cheers,

Phil
