### ISSUE TITLE
matplotlib 2.2.2 issue

### ISSUE THREAD

**Issue by sonderkar** [ewels/MultiQC#732]
**Description of bug:**
I have just updated from version 1.3 to 1.5 and now MultiQC chrashes. From the errors I get I suspect an issue with the version og matplotlib, which is version 2.2.2 on my system

**MultiQC Error log:**

```
[INFO   ]         multiqc : This is MultiQC v1.5
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Traceback (most recent call last):
  File "/services/tools/anaconda/4.4.0/bin/multiqc", line 767, in <module>
    multiqc()
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/services/tools/anaconda/4.4.0/bin/multiqc", line 413, in multiqc
    template_mod = config.avail_templates[config.template].load()
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (matplotlib 2.2.2 (/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages), Requirement.parse('matplotlib<=2.1.0'))
```

* **Command used to run MultiQC**
    * `multiqc .`
* **MultiQC Version:**
MultiQC v1.5
* **Operating System:**
 Linux x86_64
* **Python Version:**
Python 2.7.14 :: Anaconda custom (64-bit) (Anaconda 4.4.0)

**Comment by ewels** [comment]
Hi @sonderkar,

How did you install MultiQC? Usually when you run the installation these kinds of requirement conditions are automatically solved.

Phil

**Comment by sonderkar** [comment]
Hi Phil, Thanks for the quick reply.
I'm actually not sure, I have had the admin on a HPC system to install it -  I have already asked them to try to re-install. However, is it true that multiqc depends on an older version of matplotlib - version 2.2.2. is installed on the HPC system.
/Mads

**Comment by ewels** [comment]
The v1.5 release of MultiQC requires `matplotlib<=2.1.0`, yes. This is because that release contained bugs which caused MultiQC to crash - see https://github.com/matplotlib/matplotlib/issues/10476 and https://github.com/matplotlib/matplotlib/issues/10784.

Both of these have since been fixed and the latest releases of matplotlib - 2.2.2 actually works fine with MultiQC but this wasn't released at the time of the v1.5 MultiQC release.

Version 1.6dev of MultiQC has [updated this requirement](https://github.com/ewels/MultiQC/blob/e50a2b8a9161365dea861372d03e3c3958d0ed26/setup.py#L41) to `matplotlib>=2.1.1` which solves your problem. But if you want to run a stable release of MultiQC (recommended) then you'll need to wait for the v1.6 release for this.

There are a few ways to get around this, for instance monkeypatching the installation for your specific system, or using an isolated python environment (eg. [bioconda](https://bioconda.github.io/) or [singularity](http://singularity.lbl.gov/) with a [container](https://hub.docker.com/r/ewels/multiqc/)).

Let me know if I can help with this.

Phil

**Comment by ewels** [comment]
Ok, closing this issue now - let me know if there's anything else 👍

**Comment by sonderkar** [comment]
Hi Phil, thanks for the help, I consulted the admins on th HPC system, and I ended up making a conda enviroment with the specific packages, which I have then distributed to all the bioinformaticians who run the pipeline (not best solution), but now I have a working 1.5 version :-)
