### ISSUE TITLE
Add library information to Salmon report

### ISSUE THREAD

**Issue by jaclyn-taroni** [ewels/MultiQC#733]
Hi @ewels,

Thanks for this tool! We at [Alex's Lemonade](https://github.com/AlexsLemonade) are interested in using MultiQC to generate quality control reports for our [refine.bio](http://www.refine.bio) project (https://github.com/AlexsLemonade/refinebio). 

We will be using Salmon for our RNA-seq pipeline and we would like to report additional QC information to users (related: https://github.com/AlexsLemonade/refinebio/issues/131#issue-298390191 and https://github.com/AlexsLemonade/refinebio/issues/187#issuecomment-379735105). 

Would it be possible to include/display the following information from a (quasi-mapping mode) Salmon run in the form of a table:

* `library_types` from `aux_info/meta_info.json` 
* `compatible_fragments_ratios` and `strand_mapping_bias` from `lib_format_counts.json` 

Thanks again!

**Comment by ewels** [comment]
Cool! Yes I can certainly have a look. [Everything](https://github.com/ewels/MultiQC/blob/e50a2b8a9161365dea861372d03e3c3958d0ed26/multiqc/modules/salmon/salmon.py#L33) in the `meta_info.json` file is parsed already, so that’s just a case of displaying it in the report. The other stuff shouldn’t be too difficult as long as the file isn’t huge.

It looks like my [example test data](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/salmon/sample_1) may be out of date as that file is a `.txt` instead of `.json`. Do you guys have an example Salmon output that I could add to develop around please? Just dropping a zip file on this issue is fine (or PR to the test data repo).

We have a MultiQC hackathon event next week so this would be a great beginner project for someone there..

**Comment by jaclyn-taroni** [comment]
Great, thank you! Here is an example Salmon output: [DRR016125_quant.zip](https://github.com/ewels/MultiQC/files/1924186/DRR016125_quant.zip) It was run using the latest release of Salmon (`v0.9.1`).

Please let me know if you need anything else!

**Comment by ewels** [comment]
That's perfect, thank you!

**Comment by rspreafico-vir** [comment]
If this module gets revisited, would it be possible also to provide individual files from Salmon's output (such as `aux_info/meta_info.json`) to MultiQC and still figure out the sample name? Right now the full output is required by MultiQC, whereas for other tools typically a single log file is sufficient.

**Comment by ewels** [comment]
@rspreafico-vir - apologies for the ridiculously long 2 year delay in responding to your request!

The reason that Salmon needs the full output is because the [`meta_info.json` files](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/salmon/v0.9.1/DRR016125_quant/aux_info/meta_info.json) do not contain the input filename. As such, using the full file path is the only method I could think of to get a sample name for each sample. 

Looking now, I guess we could parse `cmd_info.json` for the input file paths. But that would still require passing the entire directory to MultiQC in order to be able to maintain that association, so I guess it would not really bring any benefit.

**Comment by megumi-mori** [comment]
Hi @ewels! 
I found this ticket on the difficulty project board! 
I think I can figure out how to make the requested tables from the `lib_format_counts.json` file. 
But I don't know how to display the `library_types`, which seems to require a table of strings. If I could get a pointer I can get working on this ticket.

**Comment by ewels** [comment]
Just had a quick look - it's an array, but I guess that most of the time it's a single string per sample? So I think we can just join with a comma and add as a column to the general stats table (maybe hidden by default?). Can try to have a look when I'm back at work, but feel free to have a play 👌🏻

**Comment by megumi-mori** [comment]
Ok, thanks! I just didn't know the table can handle strings. 
I started making a subsection under Salmon to display a table - should I instead include the info in the general stats? 
Thanks!

**Comment by ewels** [comment]
Yeah, just use `"scale": False` for the column config if using Strings. Then MultiQC doesn't try to add a bar underneath it and the formatting is simpler / better.

I think as it's just a single column, better to add to the General Stats table 👍🏻 Can perhaps hide it by default (or better still - hide if all values are the same across all samples, show if not). Using `"hidden": True`.
