### ISSUE TITLE
Cannot find InterOp files

### ISSUE THREAD

**Issue by nuin** [ewels/MultiQC#753]
**Description of bug:**
I am not able to make MultiQC to see my InterOp summary files. 

* **File that triggers the error:**
[test.interop.txt](https://github.com/ewels/MultiQC/files/1972442/test.interop.txt)

* **Command used to run MultiQC**
    * `multiqc . -f -c multiqc_config.yaml`

In the configuration I have
```yaml
    interop:
        fn: '*.interop.txt'
```

* **MultiQC Version:**
    * 1.5
* **Operating System:**
    * macOS High Sierra 10.13.2
* **Python Version:**
    * Python 3.6.5
* **Method of MultiQC installation:**
    * pip

Any help appreciated. I tried a new type of of file (GATK VariantEval) and it was caught successfully. 

Thanks

**Comment by ewels** [comment]
Hi @nuin,

MultiQC isn't finding your files because the search pattern name is wrong - it should be `interop/summary`:

https://github.com/ewels/MultiQC/blob/2b30e8cc3be0ae7dc17726403bcfea0ae843a942/multiqc/utils/search_patterns.yaml#L203-L204

Also you need the `sp` key, so the full file should be:

```yaml
sp:
    interop/summary:
        fn: '*.interop.txt'
```

(If the file is called `multiqc_config.yaml` and is in the working directory, it will be found automatically too, so no need for `-c` here).

However, now that MultiQC finds your file, it breaks:

```
$ multiqc -f . -m interop

[INFO   ]         multiqc : This is MultiQC v1.6.dev0 (885c16b)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]         multiqc : Only using modules interop
Searching 3 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'interop' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./test.interop.txt
============================================================
Module interop raised an exception: Traceback (most recent call last):
  File "/Users/philewels/GitHub/MultiQC/scripts/multiqc", line 425, in multiqc
    output = mod()
  File "/Users/philewels/GitHub/MultiQC/multiqc/modules/interop/interop.py", line 25, in __init__
    parsed_data = self.parse_summary_csv(f['f'])
  File "/Users/philewels/GitHub/MultiQC/multiqc/modules/interop/interop.py", line 107, in parse_summary_csv
    if data[1] == '-':
IndexError: list index out of range
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

Looks like this is a bug..

Phil

**Comment by ewels** [comment]
Sounds good! Note that your output files look pretty different to the ones that we used when writing the module: https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/interop/summary

So even when you can get MultiQC to pick up the files, we still need to fix the code so that it works with them.

**Comment by ewels** [comment]
Great! Making progress :)

It [looks like](https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/interop/summary#command) the example files were generated with `--csv=1`:

```
interop_summary --csv=1 sequencer_upload_dir > interop_summary.csv
```

If you're able to change this, it may fix the MultiQC error...

Phil

**Comment by nuin** [comment]
Giving it a try now, do you want me to close the ticket if it works OK?

**Comment by ewels** [comment]
Sure :)

**Comment by nuin** [comment]
Works fine, had to update my InterOp version.

Thanks again.

**Comment by ewels** [comment]
Great! Thanks for letting me know.
