### ISSUE TITLE
MultiQC module is incompatible with latest version of Macs2

### ISSUE THREAD

**Issue by raivivek** [ewels/MultiQC#758]
Hi,

Looks like the the `macs2` module of MultiQC is not compatible with the latest version (`MACS version 2.1.1 20160309`, see [changelog](https://github.com/taoliu/MACS/blob/master/ChangeLog)).

Please see the fields from a sample `macs2` run file pasted below:

```
# Command line: callpeak -t ...
# ARGUMENTS LIST:
# name = Liv55
# format = BAM
# ChIP-seq file = ['..'.]
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff for narrow/strong regions = 5.00e-02
# qvalue cutoff for broad/weak regions = 1.00e-01
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is on
# Paired-End mode is off

# tag size is determined as 111 bps
# total tags in treatment: 136688956
# Sequencing ends will be shifted towards 5' by 100 bp(s)
# d = 200
chr     start   end     length  pileup  -log10(pvalue)  fold_enrichment -log10(qvalue)  n
chr1    564857  565125  269     65.15   17.66218        3.37754 13.91025        Liv55
```

These do not match the fields in [macs2.py](https://github.com/ewels/MultiQC/blob/6ce7cc301cd97add6c28137a633ed07981d0b358/multiqc/modules/macs2/macs2.py#L47-L54) or the [example data file](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/macs2/macs2_output_peaks.xls).

Let me know what you think!

```
vivekrai❯ macs2 --version
macs2 2.1.1.20160309
vivekrai❯ python --version
Python 2.7.14 :: Anaconda, Inc.
```

**Comment by ewels** [comment]
Great, thanks for the detailed report!

**Comment by cpavanrun** [comment]
This was fixed earlier (b4a2fbe9553c88ae4fdd434c237d1347a377b072). For refrence I have added an example MACS2 file to the test data.

@raivivek, which version are you running of MultiQC?

**Comment by raivivek** [comment]
@cpavanrun I'm using v1.5, seems to be the latest release.
```
$ multiqc --version
multiqc, version 1.5
```

**Comment by cpavanrun** [comment]
This is strange. Strange indeed. v1.5 definitively has the mentioned fix in it. Let's investigate.

The above pasted example content is not good enough for close scrutiy because of the fine details of tabular indentation. Could you share/attach the a file with an exact copy of the file which is giving you trouble? You can ommit the actual peak details and rename the data-finenames for obvious privacy reasons.

**Comment by ewels** [comment]
For reference, this is the new test data from @cpavanrun: https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/macs2/macs2_output2_peaks.xls

@raivivek - when I run the data you pasted it worked, it's just that there's no plot and some table columns are missing. This is simply because those data are not present in your file. I've just updated the MultiQC code to tolerate this better - eg. to not try to display a bargraph if there is no bargraph data. Hopefully this is sufficient for you.

I wonder if the values are missing because you ran with `Broad region calling` set to `on` above. This probably affects the calculations and resulting summary stats from MACS2.

**Comment by ewels** [comment]
Closing now as resolved the problem with MultiQC. But please let me know if you think that there's anything else we can change here, and how you get on with the new code.
