### ISSUE TITLE
undefined symbol error in matplotlib while running multiqc

### ISSUE THREAD

**Issue by srajedwin** [ewels/MultiQC#779]
**Description of error:**
 When I run MultiQC, I exeperienced error messages:

```
/app/python/3.5.1/lib/python3.5/site-packages/matplotlib/_path.cpython-35dm-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
```

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.5
[INFO   ]         multiqc : --pdf specified. Using non-interactive HTML template.
[INFO   ]         multiqc : Template    : simple
Searching 4 files..  [####################################]  100%
##### ERROR! MatPlotLib library could not be loaded!    #####
##### Flat plots will instead be plotted as interactive #####
/app/python/3.5.1/lib/python3.5/site-packages/matplotlib/_path.cpython-35dm-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
##### ERROR! MatPlotLib library could not be loaded!    #####
##### Flat plots will instead be plotted as interactive #####
/app/python/3.5.1/lib/python3.5/site-packages/matplotlib/_path.cpython-35dm-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

```

* **Command used to run MultiQC**
    * `multiqc --file-list file_list.txt --pdf -o TEST_DIR`
* **MultiQC Version:**
    * MultiQC v1.5
* **Operating System:**
    * Linux version 2.6.32-696.30.1.el6.x86_64
* **Python Version:**
    * Python 3.5.1
* **Method of MultiQC installation:**
    *  pip

Could you please suggest me a way to fix this issue. Thank you

**Comment by ewels** [comment]
Hi @srajedwin,

This isn't a problem with MultiQC, but rather a problem with your MatPlotLib installation. This happens quite a bit and 9 times out of 10 it's fixed if you use conda environments (see the MultiQC docs here: http://multiqc.info/docs/#installing-multiqc)

Note that  although MultiQC is throwing a warning about the problem, it's still running as usual. You have no output files because MultiQC hasn't found any files that it understand (`No analysis results found.`). Please see the docs for more (note that MultiQC doesn't run other tools for you - it only parses existing analysis files).

Finally - the PDF functionality is very limited, _does_ require MatPlotLib and is likely to be removed in a future version. I would advise not using it unless totally necessary.

Phil

**Comment by srajedwin** [comment]
Thanks much, Phil!
