### ISSUE TITLE
featurecounts plot by strand

### ISSUE THREAD

**Issue by gk7279** [ewels/MultiQC#789]
Dear @ewels 

Thank you for a fantastic tool.

I am trying to plot featurecounts summary files. Here are the current cases with featurecounts in MultiQC v1.5

1. If we have one summary file per sample, it works.
2. If we have one summary file for multiple sample, it works.

How about I have multiple summary files for multiple samples that are strand separated? How can I induce this into my plot? I calculate reads for forward, reverse and both strand by using the `-s 0`, `-s 1` and `-s 2` options in featurecounts.

Thank you for your time.

**Comment by ewels** [comment]
Hi @gk7279,

So the short answer is that you need to get MultiQC to treat each type of processing separately - in other words, it needs to think that you have three samples instead of one. MultiQC get's the "sample names" for featureCounts from the log file, from the input filename. As you have the same input filename for each run it means that the sample name will be the same and they will overwrite one-another. If you run in verbose mode (`-v`) or check `multiqc.log` you should see `DEBUG` statements saying that samples are being overwritten.

Luckily, there's a pretty easy way to get around this. If you have your files in different directories, you can tell MultiQC to append the directory name onto the sample name. Then they will no longer be unique and will not be overwritten. You can do this with the `-d`/`--dirs` option. Use the `--dirs_depth` option to clean it up if necessary. You can read more about this in the documentation, [here](http://multiqc.info/docs/#not-enough-samples-found) [here](http://multiqc.info/docs/#sample-names-prefixed-with-directories) and [here](http://multiqc.info/docs/#clashing-sample-names).

I hope this helps! Let me know if you need any further help, or better still if you get it working!

Phil
