### ISSUE TITLE
Add option to copy original plots

### ISSUE THREAD

**Issue by guillermo-carrasco** [ewels/MultiQC#8]
The option to show the original plots is very useful, but it breaks if you move the `MultiQC_report` resulting directory to a location where you don't have access to the original plots. i.e I ran MultiQC in our cluster, downloaded the resulting `zip` file to my laptop for better visualization, and the `FastQC` plots (the original ones) are not there. 

What about something like `--copy-original`?

**Comment by ewels** [comment]
That's a bug, the FastQC module [should be](https://github.com/ewels/MultiQC/blob/master/multiqc/fastqc/__init__.py#L59-L66) copying the original plots already..

Are these FastQC reports zipped or unzipped? Is multiqc throwing any errors?

**Comment by guillermo-carrasco** [comment]
the reports are unzipped, and nope MultiQC isn't throwing any error. There is a `pass` statement in that `except` statement so... it may be that `IOError`, let me debug with my data.

**Comment by guillermo-carrasco** [comment]
Indeed, this is how my `fastqc` directory looks like:

```
(master)[gcarrasco@login01 MultiQC]$ ls ../fastqc
fastqc_data.txt     Per_base_N_content.tsv         Per_base_sequence_quality.tsv  Per_sequence_quality_scores.tsv  Sequence_Length_Distribution.tsv
fastqc_report.html  Per_base_sequence_content.tsv  Per_sequence_GC_content.tsv    Per_tile_sequence_quality.tsv
```

so no original plots there either. 

In any case, some kind of warning instead of a silent `pass` would be nice, don't you think?

**Comment by ewels** [comment]
Is that your original fastqc directory? Has it been parsed by something else? I'm impressed that MultiQC is picking up anything if so :)

Yeah, the `IOError` pass was because older versions of FastQC don't have the adapter plot, which lead to the entire module crashing. You're right of course though, it should probably print a logging `debug` message at least.

**Comment by guillermo-carrasco** [comment]
Hmm yes, its being parsed by `bcbio` actually, [check](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/qcsummary.py#L419). Does MultiQC support `fastqc` 0.11+? I think it does not generate the Images directory anymore.

**Comment by ewels** [comment]
Yeah, I've been testing it with 0.11.2. It now embeds the plots into the HTML so that it can be shared without the images directory, but the `Images` directory is still generated for the the zip file as well.

It looks like `bcbio` is just ignoring the Images directory - it just moves out the report and the `fastqc_data.txt` file.

This isn't standard FastQC behaviour, so I'm not keen to change the way that multiqc is handling this. However, it should be possible to get the front end javascript to display a nice error if it can't find the image.

**Comment by guillermo-carrasco** [comment]
nope, you shouldn't take care of this, as you say this is not standard `FastQC` behaviour, I'll see if I can think of something. Thanks Phil! I'll close this issue, as it is not really an issue :)

**Comment by ewels** [comment]
If you find a moment, you could try playing with [this](https://api.jquery.com/error/) :wink: 

Low priority though..

**Comment by guillermo-carrasco** [comment]
:+1:
