### ISSUE TITLE
export of static images breaks barplot in rsem module

### ISSUE THREAD

**Issue by andreasleha** [ewels/MultiQC#801]
**Description of bug:**
The rsem module contains a barplot of read assignment.  This has the switch between 'Percentages' and 'Number of Reads'.
This switching breaks (the plot always shows the percentages) if multiqc is run with the `-p` option.

**File that triggers the error:**
Use the following sample `rsem_output.cnt` file:

    170 7208 0 7378
    7208 0 4012
    12505 3
    0	170
    1	3196
    2	2824
    3	1105
    4	69
    5	14
    Inf	0

**MultiQC run details:**
 - Command used to run MultiQC:
    `multiqc .` works as expected.

 - Command used to run MultiQC:
    `multiqc -p .` produces faulty html report as expected.

**Additional Info:**

 - MultiQC Version: [MultiQC v1.6.dev0]
 - Operating System: [RHEL 7.5 (Maipo)]
 - Python Version: [Python 3.5.0]
 - Method of MultiQC installation: [manual]

**Comment by ewels** [comment]
Yep, you're absolutely right, I can reproduce this. Super weird! I'll take a look.

**Comment by ewels** [comment]
That was a good one! It was due to the good old Python variable mutability - when you specify `-p` both the MatPlotLib and HighCharts plot code is run in succession. The MatPlotLib code was calculating the percentage values, but through several levels of referencing it was updating the original values. This normally doesn't matter, as they're not used again, _except_ for when `-p` is used.

Once tracked down it wasn't too hard to make a deep copy of those values, then everything works as expected.

Thanks for reporting the bug @andreasleha!

**Comment by andreasleha** [comment]
Just to say:  thanks for looking into this!
