### ISSUE TITLE
Picard HsMetrics module to show usable bases

### ISSUE THREAD

**Issue by pancheto** [ewels/MultiQC#831]
**Is your feature request related to a problem? Please describe.**
Only 25 out of 57 Picard HsMetrics' reports are parsed by MultiQC. I see the need for keeping the table narrow, but I would like to decide which columns to parse, if not all, and not only be limited to display or hide them. In particular, I am interested in 2 columns (`PCT_USABLE_BASES_ON_BAIT` and `PCT_USABLE_BASES_ON_TARGET`) which are very informative to know how well a sequencing experiment performed.

By the way, the `MAX_TARGET_COVERAGE` column is being parsed although its header description (The maximum coverage of reads that mapped to target regions of an experiment.) is not being displayed.

**Describe the solution you'd like**
I would like to have a configuration option to add or remove columns from Picard HsMetrics module.

**Describe alternatives you've considered**
I have not find a way to show these 2 columns (or any other) but to edit `HsMetrics.py` module directly.

**Additional context**
Being these columns percentages printed out as fractions, there is an additional issue displaying them through multiqc since there is only room for 1 decimal place. I have modified their values by multiplying them by 100 manually, but being able to configure this would be also great.

Let me just add a big thank you for such a great tool.

**Comment by chadisaad** [comment]
I'm not sure that they are used. They are removed her:
https://github.com/ewels/MultiQC/blob/master/multiqc/modules/picard/HsMetrics.py#L203

**Comment by ewels** [comment]
Hi both,

Thanks again for your issue / work on this. I've just refactored the code that generates this table so that it can be altered in the MultiQC config. I also added the two columns you wanted @pancheto, so that they are now shown by default.

The code should basically work as before, but now there are two new config options documented here: https://multiqc.info/docs/#hsmetrics

> You can customise the columns shown in the HsMetrics table with the config keys `HsMetrics_table_cols` and `HsMetrics_table_cols_hidden`. For example:
> 
> ```yaml
> picard_config:
>     HsMetrics_table_cols:
>         - NEAR_BAIT_BASES
>         - OFF_BAIT_BASES
>         - ON_BAIT_BASES
>     HsMetrics_table_cols_hidden:
>         - MAX_TARGET_COVERAGE
>         - MEAN_BAIT_COVERAGE
>         - MEAN_TARGET_COVERAGE
> ```
> 
> Only values listed in `HsMetrics_table_cols` will be included in the table.
> Anything listed in `HsMetrics_table_cols_hidden` will be hidden by default.

**Note:** Loads of columns are still shown by default. It would be great if we could trim this list of defaults down quite a lot. Any suggestions for a minimum list of the most useful columns? At the moment the table is so wide that it is not very usable.

Phil

**Comment by jamigo** [comment]
thank you for the update! we'll be glad to use it in the next release.

regarding which columns to show, I agree that the table is too wide, but it's difficult to narrow it, since it helps both upstream and downstream analysts and they do require different table columns. we've reordered them to show the ones we're more interested in first, and that can be more than enough for most users.
