### ISSUE TITLE
MultiQC 1.7.dev0 not detecting cutadapt(module) trimming reports

### ISSUE THREAD

**Issue by munemdx** [ewels/MultiQC#855]
**Description of bug:**
I am using **MultiQC version 1.7.dev0** to compile all the quality control data into one report. It does detect fastQC .html reports and put them in the final report but it does not detect the trim logs created by cutadapt. What is the file format required by MultiQC in order to recognise **cutadapt** trimlog files. I have files ending in **.rtf** format. I tried with **.txt** format too but it does not work. Just a reminder, I have all my log files and .html reports in the same directory.

**MultiQC Error log:**
```
There is no such error log.

```

**File that triggers the error:**
There is no error, it smoothly runs but skips the detection of **cutadapt** log files. I have tried minimum and full log files from cutadapt but it does not detect.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC:  multiqc .
 - MultiQC Version: MultiQC v1.7.dev0
 - Operating System: macOS Sierra 10.12.6
 - Python Version: Python 3.6.6 :: Anaconda, Inc.
 - Method of MultiQC installation: conda

**Comment by ewels** [comment]
Hi @munemdx,

You can see the example files that I wrote the cutadapt module around here: https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/cutadapt

MultiQC uses a [search pattern](https://github.com/ewels/MultiQC/blob/8a04d4b929e8eb2b9ea75fc05494005aca3311ae/multiqc/utils/search_patterns.yaml#L203-L206) for the cutadapt logs, so the filename should have no effect. What version of cutadapt are you using? You can see in the above link that very old versions need a different search pattern (see [the docs](https://multiqc.info/docs/#module-search-patterns) for how to customise this).

If you're able to attach a cutadapt log file to this issue I can take a look.

Phil

**Comment by munemdx** [comment]
Hi @ewels,
I am using cutadapt version 1.18. I tried but it didn't work out may be the older version is buggy. I can try the newest one.

**Comment by ewels** [comment]
1.18 is pretty recent, so it's more likely that it's been updated and MultiQC doesn't yet support the new format. Could you (or @marcelm) post an example of the log file please?

Phil

**Comment by munemdx** [comment]
Dear @ewels ,

Here is the script and example.

This is cutadapt 1.18 with Python 3.6.6
Command line parameters: --cores=2 -u -2 -o ER85A0.fastq ER85A0.fastq.gz --report=full
Processing reads on 2 cores in single-end mode ...
Finished in 34.99 s (5 us/read; 11.12 M reads/minute).

=== Summary ===

Total reads processed:               6,482,368
Reads with adapters:                         0 (0.0%)
Reads written (passing filters):     6,482,368 (100.0%)

Total basepairs processed:   423,042,470 bp
Total written (filtered):    410,077,734 bp (96.9%)

**Comment by marcelm** [comment]
The log file format hasn’t changed in 1.18, in particular not the search pattern: `This is cutadapt`. I have added a new reporting option `--report=minimal`, though, which looks totally different and will not be recognized by MultiQC. However, `--report=full`, which @munemdx is using, will give the previous behaviour.

> If I try --info-file function, I get this error: [...]

I guess you tried to add the `--info-file` option because the example log file that @ewels linked to contains it. The option does not  change the report format, so that will not help.

You should explain this a bit more:

> I have files ending in .rtf format. I tried with .txt format too but it does not work.

`.rtf` is a format for documents. Just like `.doc`/`.docx` and similar, it is not a plain-text format. MultiQC needs the Cutadapt report to be in plain text. Sorry if the following is wrong, but my wild guess is that you ran Cutadapt in the terminal and then copied the output into a Word document, which you then saved to disk. If that is correct, you should instead use the greater-than symbol `>` to redirect Cutadapt’s report to a file directly like this:
```
cutadapt --cores=2 -u -2 -o ER85A0.fastq ER85A0.fastq.gz > cutadapt.log
```
This ensures that the log file is in the correct format (plain text). You can then open that file afterwards in any text editor, or use `cat cutadapt.log` to look at it. This also holds for other tools, not only Cutadapt.

**Comment by munemdx** [comment]
Dear @marcelm ,

Thanks for the help. It works now! I used above script shared by you and it creates log file which is detected by MultiQC.

**Comment by marcelm** [comment]
Great! Glad I could help.

**Comment by ewels** [comment]
Great stuff! Thanks both.

**Comment by SarveshSurve** [comment]
I have a similar issue. I am running the multiqc version 1.17 and it says: "No analysis results found. Cleaning up.."
I have 38 log files in the folder. 
Following is the command used for cutadapt: 
cutadapt \
        -o ${sample}_R1.trim.001.fastq.gz \
        -p ${sample}_R2.trim.001.fastq.gz \
        ../01_raw/${sample}_R1_001.fastq.gz ../01_raw/${sample}_R2_001.fastq.gz \
        -m 10 -q 20 --nextseq-trim=10 > $sample.cutadapt.report

I even tried changing the extension of log files to .txt and still the same output

**Comment by ewels** [comment]
Hi @SarveshSurve,

Please create [a new issue](https://github.com/MultiQC/MultiQC/issues/new?assignees=&labels=&projects=&template=bug_report.yml) using the template. This issue is years old and almost certainly unrelated.

I'd also recommend reading the [docs on troubleshooting](https://multiqc.info/docs/usage/troubleshooting/#no-logs-found-for-a-tool) and the [cutadapt module](https://multiqc.info/modules/cutadapt/).

Thanks!

Phil
