### ISSUE TITLE
Request for Bioconda version of  multiqc, 1.7.dev

### ISSUE THREAD

**Issue by chansigit** [ewels/MultiQC#870]
**Is your feature request related to a problem? Please describe.**
Please publish MultiQC1.7 dev version at Bioconda and PyPI for 1.6 has so many errors.

**Describe the solution you'd like**
Make MultiQC1.7dev available at bioconda 

**Describe alternatives you've considered**
Make MultiQC1.7dev available at pypi

**Additional context**
Non

**Comment by ewels** [comment]
Yes, I need to do a v1.7 release really. I'll try to get it done this week.

**Comment by ewels** [comment]
I don't want to do a release just yet with so many open PRs open and waiting. I have scheduled two afternoons into my calendar in two week's time so that I should have time to sit down and work with this (I have _lots_ of meetings these days). I'll try to push the release as an early Christmas present.. 🎅
