### ISSUE TITLE
MultiQC HiCPro KeyError 'mapped_R1'

### ISSUE THREAD

**Issue by ab1887** [ewels/MultiQC#901]
**Description of bug:**
MultiQC breaks while running on HiCPro v2.10.0 

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'output/'
Searching 126 files..  [####################################]  100%          
[ERROR  ]         multiqc : Oops! The 'hicpro' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    output/hic_results/data/HiC-dpnII-FTC-133/HiC-dpnII-FTC-133.mRSstat
============================================================
Module hicpro raised an exception: Traceback (most recent call last):
  File "/research/bsi/tools/biotools/python/2.7.10/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/research/bsi/tools/biotools/python/2.7.10/lib/python2.7/site-packages/multiqc/modules/hicpro/hicpro.py", line 40, in __init__
    data['percent_mapped_R1'] = float(data['mapped_R1']) / float(data['total_R1']) * 100.0
KeyError: 'mapped_R1'
============================================================
[INFO   ]         bowtie2 : Found 4 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

```

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.
[HiC-dpnII-FTC-133.mRSstat.txt](https://github.com/ewels/MultiQC/files/2871074/HiC-dpnII-FTC-133.mRSstat.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [eg. `multiqc output`]
 - MultiQC Version: [eg. MultiQC v1.7]
 - Operating System: Red Hat Enterprise Linux Server release 6.10
 - Python Version: [eg. Python 2.7.10]
 - Method of MultiQC installation: pip

 **Additional context**
The MultiQC does generate an HTML but it only contains Bowtie reports  and not the HiC results reports. The "output" directory is any standard output directory from HiC-Pro.

**Comment by ewels** [comment]
Hi @ab1887,

Sorry to hear that you're having problems. I guess you uploaded the file you did because of the log message:
>   If possible, please include a log file that triggers the error - the last file found was:
    output/hic_results/data/HiC-dpnII-FTC-133/HiC-dpnII-FTC-133.mRSstat

I think that this is false in this case though - MultiQC is actually [looking](https://github.com/ewels/MultiQC/blob/e0cbe2b6b9ed3c5c128bc5c110da0ab0f9da6dc7/multiqc/utils/search_patterns.yaml#L283-L286) for files that contain the string `Min rest. site distance`, which look like these: https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/hicexplorer

When I run MultiQC on just the file you supplied, it doesn't find anything to parse. I guess that you'll have the same. Could you look back into your data folder and dig out the hicexplorer log files and try running MultiQC on just them? If you get the same error, please could you try attaching them again?

Thanks,

Phil

**Comment by zyqfrog10** [comment]
Hi @ewels @nservant ,
I encountered the exact same error. It could not identify 'mapped_R1'.
I've attached my stats files from the HiC-Pro 2.10.0.
[CHiC_ESC_rep1.zip](https://github.com/ewels/MultiQC/files/3130228/CHiC_ESC_rep1.zip)

I checked the files. There is no 'mapped_R1' since the R1 and R2 are separately reported (?). Anyway, it would be nice if you could help us resolve this issue. Appreciated.

Thanks,
Ada

**Comment by nservant** [comment]
Hi Ada,
The MultiQC module requires HiC-Pro 2.11.0 version.
Sorry for that.
Nicolas

**Comment by zyqfrog10** [comment]
I see. Thanks for prompt response @nservant 
Ada

**Comment by ewels** [comment]
Hi both,

Thanks for the help @nservant. I'll close this issue now, let me know if there's anything else that needs to be done with MultiQC.

Phil
