### ISSUE TITLE
Oops! The 'tophat' MultiQC module broke

### ISSUE THREAD

**Issue by onuryukselen** [ewels/MultiQC#904]
**MultiQC Error log:**
```python
Module tophat raised an exception: Traceback (most recent call last):
    File "/usr/local/bin/multiqc", line 440, in multiqc
      output = mod()
    File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/tophat/tophat.py", line 31, in __init__
      parsed_data = self.parse_tophat_log(f['f'])
    File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/tophat/tophat.py", line 94, in parse_tophat_log
      parsed_data['unaligned_total'] = parsed_data['total_reads'] - parsed_data['aligned_total']
  KeyError: 'total_reads'
```

**File that triggers the error:**
[control_rep1.1.align_summary.txt](https://github.com/ewels/MultiQC/files/2898509/control_rep1.1.align_summary.txt)
[exper_rep1.1.align_summary.txt](https://github.com/ewels/MultiQC/files/2898510/exper_rep1.1.align_summary.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc -e general_stats -d -dd 10 .`
 - MultiQC Version: MultiQC v1.7
 - Operating System: ubuntu:16.04
 - Method of MultiQC installation: pip

**Comment by ewels** [comment]
Hi @onuryukselen,

Sorry that it's taken me so long to get to your issue. Could you confirm what tool these logs came from please? I'm guessing not TopHat - they look very different to the [other tophat data files](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/tophat/paired_end/ERR458837_1_val_tophat.align_summary.txt) that I've seen, but very similar to the [bowtie2](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/bowtie2/paired_end/bt2_pe_log.txt) / [HiSAT2](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/hisat2/v2.0.4/hisat2_PE.txt) logs.

If you indeed did not run TopHat, then the error is probably because TopHat is erroneously trying to parse the files because of their filename (`'*align_summary.txt'`) and then crashing. When I try to run MultiQC the Tophat module crashes but bowtie2 runs and I get a functional report. So actually, everything works 😅 

Phil

**Comment by ewels** [comment]
Ok, I've made the TopHat module more stringent with it's data checks, so it now ignores your example file. Hopefully this is all. Thanks for reporting the error!

Phil
