### ISSUE TITLE
Remove mention of bbmap scafstat from docs

### ISSUE THREAD

**Issue by mticlla** [ewels/MultiQC#914]
This is the content of the scafstat report
```
#name	%unambiguousReads	unambiguousMB	%ambiguousReads	ambiguousMB	unambiguousReads	ambiguousReads	assignedReads	assignedBases
chr2	6.86244	102.627009	0.33133	4.870395	682800	32967	748910	112305834
...
```

MultiQC v1.8.dev.0
BBmap v38.39

**Comment by ewels** [comment]
Hi @mticlla,

I'm afraid that MultiQC does not yet support scafstat output from bbmap. Please see the documentation for the list of supported commands: https://multiqc.info/docs/#bbmap

Phil

**Comment by mticlla** [comment]
Hi ewels,
The list for BBmap includes scafstats.

Monica

**Comment by ewels** [comment]
I'm sorry, you're right! I looked at the list of bbmap module files (https://github.com/ewels/MultiQC/tree/master/multiqc/modules/bbmap) which didn't contain scafstats. I think the documentation is wrong, because when searching for `scafstats` in the repository I only get the docs page: https://github.com/ewels/MultiQC/search?q=scafstats&type=Code

@boulund - any ideas if `scafstats` should be supported?

**Comment by boulund** [comment]
Hi!

That looks doable, sorry for accidentally including it in the docs if it's not implemented. What data from the scafstats files would you like to see in the plots/tables in the MultiQC report @mticlla? 

I've got a few issues to work on regarding the BBMap module that have been lying in wait since last year, but have been put aside due to lack of time. I'm sorry to say I have no time frame for this work, and would greatly appreciate any help.

**Comment by ewels** [comment]
For now I will update this issue to be about removing `scafstat` from the docs. If you'd like support for it added, please make a new issue using the issue template (and uploading example log files etc).

Phil

**Comment by boulund** [comment]
Made a PR #1054
