### ISSUE TITLE
Add support for Python 3.7

### ISSUE THREAD

**Issue by grzadr** [ewels/MultiQC#958]
I think it is a very simple request. Reasons for it:

1. Next Debian stable will be based on Python 3.7, 
2. Docker image for Jupyter notebook uses Python 3.7 as a default and is "pinned" in conda environment.

**Comment by ewels** [comment]
Does MultiQC not already support Python 3.7?

**Comment by TMiguelT** [comment]
Seems to work fine:

```bash
 $ python --version        
Python 3.7.1

$ megaqc run      
This is MegaQC v0.1.dev1

 * Environment: test
 * Debug mode: off
 * Environment: test
 * Database type: sqlite
 * Database path: sqlite:////home/michael/Programming/MegaQC/megaqc.db
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

**Comment by grzadr** [comment]
During installiation via conda I receive following message
```
UnsatisfiableError: The following specifications were found to be in conflict:
- multiqc==1.6 -> python[version='>=3.5,<3.6.0a0'] -> openssl[version='>=1.0.2p,<1.0.3a']
- python==3.7.3
```

**Comment by ewels** [comment]
Hmm, I wonder if this is due to the matplotlib version pinning: https://github.com/bioconda/bioconda-recipes/blob/b9491a29b5b5477b53b43fef9e6d1162fd66db6e/recipes/multiqc/meta.yaml#L14-L31

This pin is there because matplotlib dropped support for py2k, forcing MultiQC to do the same. It's getting increasingly difficult to maintain support for Python 2.. 😕 I wonder if I can have this line in the recipe twice - once with `# [py3k]` and no upper limit and once with `# [py2k]` and the upper limit..

```yaml
    - matplotlib >=2.1.1,<3.0.0 # [py2k]
    - matplotlib >=2.1.1 # [py3k]
```
@bgruening / @dpryan79 - any thoughts on whether this should work?

**Comment by dpryan79** [comment]
Why not just use the latter without `# [py3k]`?

**Comment by ewels** [comment]
That is an excellent question.. I wonder why I added it in the first place. I guess it was failing somewhere and I assumed it was needed on the conda recipe as well. That's a much easier solution!

**Comment by ewels** [comment]
ok, PR made. Hopefully this will resolve the problem... 🤞

**Comment by ewels** [comment]
@grzadr - could you please try pulling the latest version from conda and seeing if it now works? Thanks!

**Comment by dpryan79** [comment]
The updated version has fixed some of my pipelines at least :)

**Comment by ewels** [comment]
Great! Thanks :)

**Comment by TMiguelT** [comment]
I just encountered this error today:

```bash
$ conda install -c bioconda multiqc python=3.7
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - multiqc
  - python=3.7
Use "conda search <package> --info" to see the dependencies for each package.
```

Conda was attempting to install multiqc version `bioconda/linux-64::multiqc-0.9.1a0-py27_4`, which is the one that was just published. So I think this issue still exists?

**Comment by dpryan79** [comment]
@TMiguelT This is due to the following:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - spectra=0.0.11 -> networkx==2.0 -> python=3.6
```

So either `networkx` needs to be built for python 3.7 or spectra needs to not require that particular version. Anyway, this is outside the purview of MultiQC, just use python 3.6.

**Comment by TMiguelT** [comment]
Hmm, but I get the exact same error with python 3.6. I think it must be another package that's causing the conflict.

**Comment by dpryan79** [comment]
You'll get python 3.6 if you don't specify a version. Note that you probably want `-c conda-forge -c bioconda` if you're already specifying channels manually.

**Comment by TMiguelT** [comment]
No, if I don't specify a version it forces me to downgrade back to python 2.7

**Comment by dpryan79** [comment]
You seem to be using an environment with other things in it. Use `conda create -c conda-forge -c bioconda -n multiqc multiqc` instead. That get you a python 3.6 environment with multiqc.

**Comment by hannah413** [comment]
I am trying to build a conda environment from a .yml file that contains nothing but multiqc=1.7. I am unable to do so successfully. I understand that this is because I am not including conda-forge in my allowed channels.

Several of my colleagues and I avoid using conda-forge due to the frequency of clobbering issues associated with that channel. Is there any way to install a multiqc version that uses python 3 and does not depend on conda-forge? I am able to successfully install previous a previous multiqc (v.0.9) but it is not ideal for our purposes.

Thanks.

**Comment by dpryan79** [comment]
There is no way to install MultiQC in conda without the conda-forge channel. I'm not sure why that's not working for you, since `conda create -n mqc python=3.7 multiqc` works and installs multiqc 1.7 for me. The clobbering warnings can be ignored (I actually don't get any for MultiQC, there are a lot of those with perl packages).

**Comment by ewels** [comment]
@hannah413 If you _really_ don't want to use conda-forge, then there are other ways to install MultiQC which don't use conda at all - see the docs: https://multiqc.info/docs/#installing-multiqc (but I usually recommend using conda wherever possible).
