### ISSUE TITLE
Use jinja to create plots

### ISSUE THREAD

**Issue by juanesarango** [ewels/MultiQC#971]
This is a **question** or **discussion** about a current implementation.

Jinja is very powerful to create html templates, as it's used for the main report structure. Why is not used too to create the `plots` too?

It just feels very cumbersome that if someone wants to add a custom plot component, he/she would need to create an escaped html-string using python so it can be passed to the context in the `plot` variable of the section. 
Wouldn't be easier just to add a jinja template or macro inside the current templates for every plot component?

For example the table is created by formatting a bunch of python strings.
With jinja, I strongly believe it could improve readability and maintenance of the components.

**Comment by ewels** [comment]
Hi @juanesarango,

An excellent question. I'm not sure that I have a particularly satisfying answer for you, other than this is just the way that I wrote it when I first sat down in the first days of MultiQC (when it was only intended to be a small internal tool for our group, and I had no idea how it would grow). However, I'm not sure that I agree that jinja templating in all cases is more clear. For many of the plots and tables, there is such a lot of conditional logic happening that I think the jinja templates would themselves become pretty incomprehensible.

Having said this, if there are specific chunks of code that you think could be improved, I'd be happy to look in to refactoring this. Or better still, you can via a pull-request 😉 If you do submit a PR, please start off with a small one so that we can discuss approaches though.

Cheers,

Phil

**Comment by juanesarango** [comment]
Phil, thanks for your answer! I love the project and in my team we're active users of it. I would be happy to help and contribute in the near future starting with some small refactoring. I will let you know!
