### ISSUE TITLE
multiqc not working well with salmon logs

### ISSUE THREAD

**Issue by tamuanand** [ewels/MultiQC#994]
**Description of bug:**
MultiQC is not behaving correctly with salmon outputs. In general only 1 sample info ends up getting reported.

I am using MultiQC 1.7 downloaded from bioconda 

 **Additional context**
 I found this issue also being reported recently - https://github.com/ewels/MultiQC/issues/960#issuecomment-486979966

Thanks in advance.

**Comment by ewels** [comment]
Hi @tamuanand,

Have you checked the docs about this? https://multiqc.info/docs/#not-enough-samples-found

Note that the Salmon module takes sample names from the _directory name_ that the logs are in. If all of your Salmon results directories have the same name, you will only get one sample in your report.

I believe that the comment you linked to wasn't a bug - it was multiple samples having identical curves and being plotted exactly on top of one another.

Phil

**Comment by tamuanand** [comment]
Hi Phil,

In my case my directories are 
```
salmon_Sample_A
salmon_Sample_B
salmon_Sample_C
```
and so on...

Within each of those directories, this is the structure (which is auto-created by salmon quant command)
```
logs  - directory which has the file salmon_quant.log
aux_info  
quant.sf
cmd_info.json  
lib_format_counts.json  
libParams  
```

You wrote

> Note that the Salmon module takes sample names from the directory name that the logs are in. 

Does it mean that I should probably change the 'logs' directory name to salmon_SampleA_logs, salmon_SampleB_logs etc and then give multiQC a try?

Thanks.

**Comment by ewels** [comment]
Ok, let me look.. The Salmon module looks for two filetypes: https://multiqc.info/docs/#salmon - let's just talk about `meta_info.json` for now. Once it finds that file, it gets the sample name from the parent of it's parent directory (two up): https://github.com/ewels/MultiQC/blob/f2ec3d488c9acffdd30e280f04abd8ab0c58de72/multiqc/modules/salmon/salmon.py#L30-L31

So in this case it's the directory that contains `aux_info/meta_info.json` (based on the [example data for salmon](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/salmon/v0.9.1/DRR016125_quant/aux_info/meta_info.json)). If your file structure is `salmon_Sample_A/aux_info/meta_info.json` then you _should_ be fine..

I would guess that this comes down to some kind of weird staging issue in the nextflow process. I've had similar stuff before. Can you do `tree -a` command of the nextflow MultiQC work directory so that we can see what the file structure is please?

Phil

**Comment by ewels** [comment]
NB: Some of that nextflow code looks quite familiar 😉 - it may be of interest to you that the next release of [nf-core/rnaseq](https://github.com/nf-core/rnaseq/) will have Salmon as an option for the aligner. It's already been merged into the `dev` branch [here](https://github.com/nf-core/rnaseq/blob/45da2622066683fd9cfcfbe57bbf0cbe12d284e2/main.nf#L1177-L1181).

**Comment by ewels** [comment]
> I tried mousing over the fragment length distribution graph, but try as much as I could, I could not see any other sample names on the mouseover.

You won't - if the values are _identical_ then it will only be possible to get a tooltip for the topmost plotted sample. I think this is down to one of the ways in which Salmon can work, where it uses a fixed insert length distribution assumption, which is why it's identical for all samples. I should probably look for this in the MultiQC code and add a warning if it's detected I guess... PRs welcome??

**Comment by tamuanand** [comment]
Hi Phil

> NB: Some of that nextflow code looks quite familiar 

- You are right --  I m a NextFlow greenhorn - just 2 weeks digging around github codebases, and into my 3rd active day of  hands-on coding for production workflows. For now, I am using 2 of the nf-core workflows as my reference/encylopedia and I have [actually reached out to you here](https://github.com/nf-core/rnaseq/issues/259#issuecomment-513643267). Needless to state one of the references for me is the [nf-core/rnaseq workflow](https://github.com/nf-core/rnaseq).

- I have also reached out to you and Paolo to see if I can attend the Sep 2019 workshop 

Back to this thread -  I do not believe it is NF staging issue and the reason I say that is -- I also did  this _outside of my NF workflow on the final output directories which have my salmon_Sample_A, salmon_sample_B subfolders_

`multiqc . `

I still see the same behaviour - I can see the salmon statistics table with info for all samples, but the graph shows only 1 sample - so it could be what you mention 

>  I think this is down to one of the ways in which Salmon can work, where it uses a fixed insert length distribution assumption, which is why it's identical for all samples. 

I don't know if this matters - I am using salmon v0.14.1 

Let me know if you still need the tree -a command output.

Thanks again,

**Comment by ewels** [comment]
Hi @tamuanand,

Cleaning up issues, basically I don't think that there's anything wrong here - it sounds to me like everything is behaving as expected. That is - the plot data for all samples is identical. You can test this by downloading the plot data from the report and plotting it yourself in excel.

Closing this issue now, if you think that there's still something odd then let me know and I can reopen.

Phil

**Comment by matmu** [comment]
I had the same issue and indeed it turned out that the values for all samples were exactly the same. You can also check this by hiding a specific sample in the multiqc html report.

**Comment by bwlang** [comment]
This is not the most useful plot.

In the experiment I'm looking at we see variable read lengths (ONT) from fastqc, but salmon seems to be reporting all the same lengths.
Seems like salmon would need changes to fix this, or maybe that's not what the fragment length distribution is about and 
 this module should be dropped since it's not really reflecting anything about the experiment.

@rob-p or @k3yavi
Any thoughts on the fragment length distribution and how it should be used? I'm happy to share data if it's helpful.
